### PR TITLE
Make tab min width option available only when scrollable tab strip is enabled

### LINKED ISSUE #54699: Make "Minimum tab width" setting visible only if brave://flags/#brave-scrollable-tab-strip is enabled
### Description

In 1.90.x the "Minimum tab width" setting is always visible, regardless of the value of brave://flags/#brave-scrollable-tab-strip. AFAIK this setting will only be useful if this flag is enabled, so we may want to consider only showing this setting when the flag is enabled. 

cc @rebron @sangwoo108 

### Steps to reproduce

1. Using 1.90.x, navigate to brave://flags
2. Confirm brave://flags/#brave-scrollable-tab-strip is not enabled
3. Navigate to brave://settings/appearance
4. See "Minimum tab width" under the "Tabs" section

### Actual result

https://github.com/user-attachments/assets/7c591000-f066-44cf-b1eb-8c64b58fc404

### Expected result

"Minimum tab width" only shown when brave://flags/#brave-scrollable-tab-strip is enabled

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

```
Brave | 1.90.106 Chromium: 147.0.7727.102 (Official Build) beta (arm64)
-- | --
Revision | c6d6a9660a9c6017b69985b737f2dd56e7b49b2f
OS | macOS Version 26.4.1 (Build 25E253)
```

```
Brave | 1.91.51 Chromium: 147.0.7727.56 (Official Build) nightly (arm64)
-- | --
Revision | 3b1e888d90485fb32fb8c713bb5cbe819faa713d
OS | macOS Version 26.4.1 (Build 25E253)
```

### Channel information

- [ ] release (stable)
- [x] beta
- [x] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

cc @brave/qa-team @brave/user-support-team

### PR DESCRIPTION
**Pull request by sangwoo108**
When scrollable tab strip is disabled, having wider min width could interfere with user experience. They'll lose ability to see more tabs at once.

Resolves https://github.com/brave/brave-browser/issues/54699

### CODE REVIEW

File: browser/ui/views/tabs/brave_tab_strip.cc [hunk 1]
```diff
@@ -79,6 +80,12 @@ BraveTabStrip::BraveTabStrip(
       controller_->GetBrowserWindowInterface()->GetProfile()->GetPrefs(),
       base::BindRepeating(&BraveTabStrip::OnTabMinWidthModePrefChanged,
                           base::Unretained(this)));
+  scrollable_horizontal_tab_strip_.Init(
```
Comment (sangwoo108) [inline browser/ui/views/tabs/brave_tab_strip.cc]: should be guarded with flag

File: browser/ui/views/tabs/brave_tab_strip.cc [hunk 2]
```diff
@@ -79,6 +81,14 @@ BraveTabStrip::BraveTabStrip(
       controller_->GetBrowserWindowInterface()->GetProfile()->GetPrefs(),
       base::BindRepeating(&BraveTabStrip::OnTabMinWidthModePrefChanged,
                           base::Unretained(this)));
+  if (base::FeatureList::IsEnabled(tabs::kBraveScrollableTabStrip)) {
+    scrollable_horizontal_tab_strip_.Init(
+        brave_tabs::kScrollableHorizontalTabStrip,
+        controller_->GetBrowserWindowInterface()->GetProfile()->GetPrefs(),
+        base::BindRepeating(
+            &BraveTabStrip::OnScrollableHorizontalTabStripPrefChanged,
+            base::Unretained(this)));
```
[the remark this answers is not in the document]
Comment (sangwoo108) [reply browser/ui/views/tabs/brave_tab_strip.cc:90]: Safe to have unretained of this, as it's RAII styl callback registration.

File: browser/ui/views/tabs/brave_tab_strip.cc [hunk 3]
```diff
@@ -362,7 +372,16 @@ void BraveTabStrip::OnTabMinWidthModePrefChanged() {
...
 
+void BraveTabStrip::OnScrollableHorizontalTabStripPrefChanged() {
+  InvalidateTabContainerLayout();
+}
+
 brave_tabs::TabMinWidthMode BraveTabStrip::GetTabMinWidthMode() const {
+  PrefService* prefs =
+      controller_->GetBrowserWindowInterface()->GetProfile()->GetPrefs();
+  if (!brave_tabs::IsScrollableHorizontalTabStripEnabled(prefs)) {
+    return brave_tabs::TabMinWidthMode::kDefault;
```
Comment (netzenbot) [inline browser/ui/views/tabs/brave_tab_strip.cc:383]: The new guard in `GetTabMinWidthMode()` (returning `kDefault` when scrollable tab strip is disabled) is a behavior change with no corresponding test. [ARCH-062](https://github.com/brave/brave-core/tree/master/docs/best-practices/architecture.md#ARCH-062) requires at least one test for user-visible behavior changes. A unit test on `BraveTabStrip::GetTabMinWidthMode()` verifying it returns `kDefault` when the scrollable tab strip pref/flag is off would cover this.

File: browser/ui/views/tabs/brave_tab_strip.cc [hunk 4]
```diff
@@ -362,7 +372,16 @@ void BraveTabStrip::OnTabMinWidthModePrefChanged() {
   InvalidateTabContainerLayout();
 }
 
+void BraveTabStrip::OnScrollableHorizontalTabStripPrefChanged() {
+  InvalidateTabContainerLayout();
+}
+
 brave_tabs::TabMinWidthMode BraveTabStrip::GetTabMinWidthMode() const {
+  PrefService* prefs =
+      controller_->GetBrowserWindowInterface()->GetProfile()->GetPrefs();
```
Comment (netzenbot) [inline browser/ui/views/tabs/brave_tab_strip.cc:381]: nit: `prefs` is assigned once and never modified — prefer `const PrefService* prefs = ...` to communicate intent. `IsScrollableHorizontalTabStripEnabled` already takes `const PrefService*`, so this compiles cleanly. ([Prefer `const` for Local Variables Where Possible](https://github.com/brave/brave-core/tree/master/docs/best-practices/coding-standards.md#CS-064))

Comment (fallaciousreasoning) [reply browser/ui/views/tabs/brave_tab_strip.cc:381]: this feels too aggressive

File: browser/ui/views/tabs/brave_tab_strip.cc (hunk 3 above)
Comment (fallaciousreasoning) [reply browser/ui/views/tabs/brave_tab_strip.cc:383]: seems like a good idea

**Review by fallaciousreasoning — APPROVED** [review]
lgtm % a unittest

File: browser/ui/views/tabs/brave_tab_strip.cc (hunk 4 above)
Comment (sangwoo108) [reply browser/ui/views/tabs/brave_tab_strip.cc:381]: haha yeah, Maybe the obsession with constness led to Rust, eventually

File: browser/ui/views/tabs/brave_tab_strip.cc (hunk 3 above)
Comment (sangwoo108) [reply browser/ui/views/tabs/brave_tab_strip.cc:383]: Good call. Done!

File: browser/ui/BUILD.gn [hunk 5]
```diff
@@ -1518,13 +1518,17 @@ source_set("unit_tests") {
       "brave_layout_constants_unittest.cc",
       "brave_scheme_utils_unittest.cc",
       "managed_ui_unittest.cc",
+      "tabs/brave_tab_prefs_unittest.cc",
```
[the remark this answers is not in the document]
Comment (sangwoo108) [reply browser/ui/BUILD.gn:1521]: Adding a unit test, so should be fine with circular dependency.
