### PR TITLE
[query-filter] Skip version update on failed parsing

### LINKED ISSUE #55124: Skip version update on failed parsing and improve testing
### Description

We should skip the version update if we were unable to [parse the json contents](https://sourcegraph.com/r/github.com/brave/brave-core/-/blob/components/query_filter/browser/query_filter_component_installer.cc?L53). 

We should add support to pass a callback to this method [OnQueryFilterFileRead](https://sourcegraph.com/r/github.com/brave/brave-core/-/blob/components/query_filter/browser/query_filter_component_installer.cc?L44), which would allow to better test the ComponentReady functionality [here](https://sourcegraph.com/r/github.com/brave/brave-core/-/blob/components/query_filter/browser/query_filter_component_installer_unittest.cc?L181-206) 

@fmarier @cdesouza-chromium for visibility on this issue.

### PR DESCRIPTION
**Pull request by r0hit0303**
This change updates the query filter component installer to skip updating version if the json file parsing failed. 

This change also adds logic to supply test only callback which gets fired after the component installer attempted to parse the json. This facilitates testing the ComponentReady functionality e2e. 

Resolves https://github.com/brave/brave-browser/issues/55124

### CODE REVIEW

File: components/query_filter/browser/query_filter_component_installer.cc [hunk 1]
```diff
@@ -97,14 +98,20 @@ void QueryFilterComponentInstallerPolicy::ComponentReady(
   VLOG(1) << "Component ready, version " << version.GetString() << " in "
           << install_dir.value();
 
+  base::OnceClosure on_file_loaded_callback =
+      on_file_loaded_callback_for_testing_.is_null()
```
Comment (cdesouza-chromium) [inline components/query_filter/browser/query_filter_component_installer.cc]: Don't make this a callback that is a member of this class. Callbacks have a shared ptr inside, which involves control blocks, so we are wasting memory. Is it the case that during tests we don't instantiate more than one instance of `QueryFilterComponentInstallerPolicy` at a time? If so, we can do just:

```cxx
namespace {
// Used by tests to receive a failure signal
base::OnceClosure* g_on_file_loaded_callback_for_testing_ = nullptr;
}  // namespace
```

Then have:
```cxx
  void QueryFilterComponentInstallerPolicy::SetOnFileLoadedCallbackForTesting(base::OnceClosure& callback) {
    g_on_file_loaded_callback_for_testing_ = &callback;
  }
```

Then in `OnQueryFilterFileRead` do:

```
void OnQueryFilterFileRead(const base::Version& version,
                           const std::string& json_data) {
  // ...
  // ...
  if (g_on_file_loaded_callback_for_testing_) {
     CHECK_IS_TEST();
     CHECK(!g_on_file_loaded_callback_for_testing_.is_null());
     std::move(*g_on_file_loaded_callback_for_testing_).Run();
  }
}
```

This way we have only a single pointer that is guaranteed to be on the stack.

File: components/query_filter/browser/query_filter_component_installer_unittest.cc [hunk 2]
```diff
@@ -166,18 +166,18 @@ TEST_F(QueryFilterComponentInstallerTest, TestComponentReady) {
 
   // Initiate component ready which would load the json file and populate the
   // query filter data.
+  base::RunLoop run_loop;
   component_updater::QueryFilterComponentInstallerPolicy policy;
+  policy.set_on_file_loaded_callback_for_testing(run_loop.QuitClosure());
```
Comment (cdesouza-chromium) [inline components/query_filter/browser/query_filter_component_installer_unittest.cc]: Use something like this class in your tests:

```cxx
namespace {
class ScopedFileLoadedCallbackForTesting {                                                                                                                                                                             
   public:                                                                                                                                                                                                                 
    ScopedFileLoadedCallbackForTesting(                                                                                                                                                                                    
        QueryFilterComponentInstallerPolicy& policy,                                                                                                                                                                       
        base::OnceClosure callback)                                                                                                                                                                                        
        : policy_(policy), callback_(std::move(callback)) {                                                                                                                                                                
      policy_->SetOnFileLoadedCallbackForTesting(&callback_);
    }                                                                                                                                                                                                                      
                  
    ~ScopedFileLoadedCallbackForTesting() {
      policy_->SetOnFileLoadedCallbackForTesting(nullptr);
    }                                                                                                                                                                                                                      
   
    ScopedFileLoadedCallbackForTesting(                                                                                                                                                                                    
        const ScopedFileLoadedCallbackForTesting&) = delete;
    ScopedFileLoadedCallbackForTesting& operator=(
        const ScopedFileLoadedCallbackForTesting&) = delete;                                                                                                                                                               
   
   private:                                                                                                                                                                                                                
    raw_ref<QueryFilterComponentInstallerPolicy> policy_;
    base::OnceClosure callback_;
  };
}  namespace
```
This will mange the pointer assignment and making sure we won't get it wrong, and it will also own the callback.

File: components/query_filter/browser/query_filter_component_installer_unittest.cc [hunk 3]
```diff
@@ -166,18 +166,18 @@ TEST_F(QueryFilterComponentInstallerTest, TestComponentReady) {
 
   // Initiate component ready which would load the json file and populate the
   // query filter data.
+  base::RunLoop run_loop;
```
Comment (cdesouza-chromium) [inline components/query_filter/browser/query_filter_component_installer_unittest.cc]: We are encouraged to not use `base::RunLoop`. Let's just use:
```cxx
base::test::TestFuture<void> future; 
component_updater::QueryFilterComponentInstallerPolicy policy;
ScopedFileLoadedCallbackForTesting scoped(policy_, future.GetCallback());
policy.ComponentReady(version, GetInstallDirectoryPath(), base::DictValue());
ASSERT_TRUE(future.Wait());

**Review by cdesouza-chromium — COMMENTED** [review]
Thanks Rohit.. we are nearly there. Just a few things that you were not aware of.

File: components/query_filter/browser/query_filter_component_installer_unittest.cc (hunk 3 above)
Comment (r0hit0303) [reply components/query_filter/browser/query_filter_component_installer_unittest.cc]: Sorry missed this. I was under the impression that this was fine because we were passing the callback explicitly to make the wait more deterministic, and that RunUntillde was not permitted (because it waited only for the current message loop to be over, and our test/callback could arrive after undeterministically). 

However, indeed as you said from the testing best practices it seems future is [preferable](https://github.com/brave/brave-core/blob/master/docs/best-practices/testing-async.md#-always-use-basetesttestfuture-over-runloop-for-callbacks). I missed it but I'll make sure to keep it mind for future. Thanks! :)

File: components/query_filter/browser/query_filter_component_installer.cc (hunk 1 above)
Comment (r0hit0303) [reply components/query_filter/browser/query_filter_component_installer.cc]: > Callbacks have a shared ptr inside, which involves control blocks, so we are wasting memory. 

I might be wrong here but I don't think that's the case i.e having an overhead of a control block(like std::shared_ptr for internal ref_counts and weak_ptr counts) with base::OnceClosure (which is an alias for base::OnceCallback). There could be situations though that the functor itself which is binded to could be arbitrarily large (in contrast with lambdas) but that would never be the case for us here. Going through the codebase we have:

1) base::OnceCallback internally holds one member variable of type [internal::BindStateHolder](https://source.chromium.org/chromium/chromium/src/+/main:base/functional/callback.h;drc=30b305c5f320177757a739df0d0b60820684fa17;bpv=1;bpt=1;l=276) which intern holds a [scoped_refptr\<BindStateBase\>](https://source.chromium.org/chromium/chromium/src/+/main:base/functional/callback_internal.h;drc=30b305c5f320177757a739df0d0b60820684fa17;l=158) and that in turn is already a [nullptr](https://source.chromium.org/chromium/chromium/src/+/main:base/memory/scoped_refptr.h;drc=30b305c5f320177757a739df0d0b60820684fa17;l=366). 

2) To be 100% sure I also added logs to check the size in real time and indeed found that base::OnceCallback had allocated only 8 bytes. 

```
[51481:13966464:ERROR:brave/components/query_filter/browser/query_filter_component_installer.cc:106] sizeof: on_file_loaded_callback8
[51481:13966464:ERROR:brave/components/query_filter/browser/query_filter_component_installer.cc:108] sizeof: on_file_loaded_callback pointer8
```
Therefore, I don't think there's any difference memory wise doing the current way or the way you are proposing. 

-- 
> Then in OnQueryFilterFileRead do:

I think that code wouldn't take into account the early returns we have in place which would result in not firing our callback at all.  I think a cleaner way could be to rely on the [Then](https://chromium.googlesource.com/chromium/src/+/HEAD/docs/callback.md#chaining-callbacks) functionality to chain the callback, which would then unconditionally call any registered callbacks after the  `OnQueryFilterFileRead` : 

```
void FireCallbackIfNeeded() {
  if (g_on_file_loaded_callback_for_testing_) {
    CHECK_IS_TEST();
    CHECK(!g_on_file_loaded_callback_for_testing_->is_null());
    std::move(*g_on_file_loaded_callback_for_testing_).Run();
  }
}

  base::ThreadPool::PostTaskAndReplyWithResult(
      FROM_HERE,
      {base::MayBlock(), base::TaskShutdownBehavior::SKIP_ON_SHUTDOWN,
       base::TaskPriority::BEST_EFFORT},
      base::BindOnce(
          &ReadQueryFilterFile,
          install_dir.AppendASCII(query_filter::kQueryFilterJsonFile)),
      base::BindOnce(&OnQueryFilterFileRead, version)
          .Then(base::BindOnce(&FireCallbackIfNeeded)));
```
If there was no other reason to use global variable I feel having it as a member variable and making `FireCallbackIfNeeded` as a member method would be more comprehensible, unless you have strong objections in which case I'm happy to change.

Comment (cdesouza-chromium) [reply components/query_filter/browser/query_filter_component_installer.cc]: `.Then` is a no go there, because we only need that for test. Production code should not have these types of hoops for test only code. We should NOT be binding `DoNothing` there in production.

Regarding the pointer, I guess `scoped_refptr` only attaches the control block once engaged, as `shared_ptr` in chromium is shared from this, so in disengaged mode it has only a pointer.

However, the pointer is still better. It is either a pointer, or a `NoDestructor` for that value to be global, and I don't see any gain in that if we are using it only for tests, and with something managing the setting of the pointer. If we use a `NoDestructor` here, it will cause cache syncs, etc, and we don't want that, so let's use just the pointer.

File: components/query_filter/browser/query_filter_component_installer_unittest.cc (hunk 2 above)
Comment (r0hit0303) [reply components/query_filter/browser/query_filter_component_installer_unittest.cc]: Done

File: components/query_filter/browser/query_filter_component_installer_unittest.cc (hunk 3 above)
Comment (r0hit0303) [reply components/query_filter/browser/query_filter_component_installer_unittest.cc]: Done

File: components/query_filter/browser/query_filter_component_installer.cc (hunk 1 above)
Comment (r0hit0303) [reply components/query_filter/browser/query_filter_component_installer.cc]: Done. Switched to using a global variable like you suggested.

**Review by cdesouza-chromium — APPROVED** [review]
LGTM

**Comment by r0hit0303** [comment]
Thanks Claudio for the review.
