### PR TITLE
Hide Survey Panelist in settings for Origin builds

### LINKED ISSUE #54584: do not show "Survey Panelist" in Origin builds
### Description

Remove "Survey Panelist" from brave://settings/privacy for Origin builds.

### Steps to reproduce

1. Using Brave Origin build navigate to brave://settings/privacy
2. Look at "Data Collection" section
3. Survey Panelist is displayed and you're able to click on it/access brave://settings/surveyPanelist

### Actual result

Example | Example
--- | ---
Image | Image

### Expected result

Survey panelist removed from settings

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

Brave Origin	1.91.59 Chromium: 147.0.7727.56 (Official Build) nightly (arm64) 
Revision	6ece7d48e4819cb74588dad704ff962a44517306
OS	macOS Version 15.7.4 (Build 24G517)

### Channel information

- [ ] release (stable)
- [ ] beta
- [x] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

_No response_

### PR DESCRIPTION
**Pull request by bbondy**
Resolves https://github.com/brave/brave-browser/issues/54584

Shows there is no item in Data Collection:
Screenshot 2026-04-17 at 1 08 59 PM

## Summary

- Hide the Survey Panelist row in `brave://settings/privacy` → Data Collection on Brave Origin. The `isSurveyPanelistAllowed` loadTimeData boolean is now also false when `BUILDFLAG(IS_BRAVE_ORIGIN_BRANDED)` is set, or when the user has upgraded a regular build to Brave Origin (`brave_origin::IsBraveOriginPurchased()`). This drops the link row, the subpage registration in `privacy_page_index.ts`, and the `pageVisibility.surveyPanelist` entry all at once.
- Also force the backend opt-in check (`UserHasOptedInToSurveyPanelist()` in `brave_ads`) and the virtual pref `[virtual]:is_survey_panelist` to `false` on Origin. Without this, a user who had previously opted in and then upgraded to Origin would have the toggle removed from settings, but the feature (90-day ad-event retention, `is_survey_panelist` ads targeting) would keep running invisibly with no way to turn it off.

## Test plan

- [ ] On a Brave Origin branded build, `brave://settings/privacy` → Data Collection does not show the Survey Panelist row; navigating directly to `brave://settings/surveyPanelist` does not surface the subpage.
- [ ] On a regular (non-branded) build with Origin purchased, the row is also hidden.
- [ ] On a regular build with Origin not purchased and the `BraveNTPBrandedWallpaperSurveyPanelist` feature enabled, the row still appears and still toggles the pref as before.
- [ ] With the pref pre-seeded to true, entering the Origin state (branded build or purchased) causes `UserHasOptedInToSurveyPanelist()` to return false (verified via ad event retention falling back to 2 days) and the virtual pref `[virtual]:is_survey_panelist` to report false.

### CODE REVIEW

File: browser/ui/webui/brave_settings_ui.cc [hunk 1]
```diff
@@ -254,10 +254,15 @@ void BraveSettingsUI::AddResources(content::WebUIDataSource* html_source,
...
   html_source->AddBoolean("isSurveyPanelistAllowed",
                           base::FeatureList::IsEnabled(
                               ntp_background_images::features::
-                                  kBraveNTPBrandedWallpaperSurveyPanelist));
+                                  kBraveNTPBrandedWallpaperSurveyPanelist) &&
+                              !brave_origin::IsBraveOriginPurchased());
+#endif
   html_source->AddBoolean(
       "isPlaylistAllowed",
       base::FeatureList::IsEnabled(playlist::features::kPlaylist) &&
```
Comment (netzenbot) [inline browser/ui/webui/brave_settings_ui.cc:268]: nit: This `#endif` closes a 9-line `#if BUILDFLAG(IS_BRAVE_ORIGIN_BRANDED)` block. Per BS-045, blocks > 3 lines should include a comment on `#endif` (e.g., `#endif  // BUILDFLAG(IS_BRAVE_ORIGIN_BRANDED)`). https://github.com/brave/brave-core/tree/master/docs/best-practices/build-system.md#BS-045

Comment (bbondy) [reply browser/ui/webui/brave_settings_ui.cc:268]: Fixed in 53b22f082d5.

**Review by Douglashdaniel — APPROVED** [review]
LGTM!
