### PR TITLE
Fix crash in BraveTabStrip::UpdateOrientation() with upstream vertical tabs

### LINKED ISSUE #54419: [macOS] Crash after enabling vertical tabs
### Description

The Brave browser on macOS (Sequoia 15.7.4) crashes after enabling vertical tabs, and the Brave browser cannot be opened since.

### Steps to reproduce

1. Download the stable version of Brave browser (v1.89.132)
2.Enable vertical tabs in brave://flags/
3. In the settings, set the appearance to vertical tabs, then close the Brave browser. After that, you will not be able to open the Brave browser.

### Actual result

Brave browser cannot be opened.

### Expected result

The Brave browser can be opened and used normally.

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

v1.89.132

### Channel information

- [x] release (stable)
- [ ] beta
- [ ] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [x] with Brave Rewards disabled
- [x] in the latest version of Chrome

### Miscellaneous information

_No response_

### PR DESCRIPTION
**Pull request by simonhong**
When Chromium's vertical tabs feature is enabled, TabStrip::Initialize() is never called
so tab_container_ remains null. This caused a crash in SetAvailableWidthCallback() during startup.
Early return when Brave vertical tabs are not supported.

Resolves https://github.com/brave/brave-browser/issues/54419

### CODE REVIEW

File: browser/ui/views/frame/vertical_tabs/vertical_tab_strip_browsertest.cc [hunk 1]
```diff
@@ -2312,3 +2312,27 @@ INSTANTIATE_TEST_SUITE_P(,
...
+  ~UpstreamVerticalTabsCrashTest() override = default;
+
+ private:
+  base::test::ScopedFeatureList scoped_feature_list_;
+};
+
+IN_PROC_BROWSER_TEST_F(UpstreamVerticalTabsCrashTest, NoCrashOnStartup) {
+  // Simulate the user choosing "Side" in Tab strip position settings,
+  // then opening a new window. Previously this crashed in
+  // BraveTabStrip::UpdateOrientation() because tab_container_ was null.
```
Comment (netzenbot) [inline browser/ui/views/frame/vertical_tabs/vertical_tab_strip_browsertest.cc]: nit: The comments say "was crashing" and "Previously this crashed" — these reference historical behavior rather than what the code does now. Prefer something like "Verifies no crash when kVerticalTabs is active and kVerticalTabsEnabled is set, since tab_container_ may be null in that configuration." ([Comments Must Make Sense to Future Readers of the Codebase](https://github.com/brave/brave-core/tree/master/docs/best-practices/coding-standards.md#CS-019))

File: browser/ui/views/tabs/brave_tab_strip.cc [hunk 2]
```diff
@@ -305,6 +305,13 @@ bool BraveTabStrip::ShouldShowPinnedTabsInGrid() const {
 }
 
 void BraveTabStrip::UpdateOrientation() {
+  // When Chromium's upstream vertical tabs feature is active,
```
Comment (netzenbot) [inline browser/ui/views/tabs/brave_tab_strip.cc]: nit: This is a workaround for upstream behavior, but there's no link to a Chromium bug. Per [CS-023](https://github.com/brave/brave-core/tree/master/docs/best-practices/coding-standards.md#CS-023), please file an upstream issue (or find an existing one) and add the link here so this guard can be removed once the upstream fix lands.

File: browser/ui/views/frame/vertical_tabs/vertical_tab_strip_browsertest.cc [hunk 3]
```diff
@@ -2312,3 +2312,27 @@ INSTANTIATE_TEST_SUITE_P(,
...
+  browser()->profile()->GetPrefs()->SetBoolean(prefs::kVerticalTabsEnabled,
+                                               true);
+  CreateBrowser(browser()->profile());
+}
```
Comment (netzenbot) [inline browser/ui/views/frame/vertical_tabs/vertical_tab_strip_browsertest.cc:2341]: nit: The test verifies no crash by surviving `CreateBrowser()`, but per TI-029, browser tests should verify at least one observable side effect. Consider asserting the returned `Browser*` is non-null or that the tab strip model has the expected tab count. ([Verify Observable Side Effects in Browser Tests](https://github.com/brave/brave-core/tree/master/docs/best-practices/testing-isolation.md#TI-029))

File: browser/ui/views/tabs/brave_tab_strip.cc (hunk 2 above)
Comment (simonhong) [reply browser/ui/views/tabs/brave_tab_strip.cc]: It's not an upstream bug. TabStrip::Initialize() is not used by vertical tab mode.
Updated that comment.

File: browser/ui/views/frame/vertical_tabs/vertical_tab_strip_browsertest.cc (hunk 3 above)
Comment (simonhong) [reply browser/ui/views/frame/vertical_tabs/vertical_tab_strip_browsertest.cc:2341]: Fixed.

File: browser/ui/views/frame/vertical_tabs/vertical_tab_strip_browsertest.cc (hunk 1 above)
Comment (simonhong) [reply browser/ui/views/frame/vertical_tabs/vertical_tab_strip_browsertest.cc]: Updated comments.

File: browser/ui/views/tabs/brave_tab_strip.cc [hunk 4]
```diff
@@ -305,6 +305,14 @@ bool BraveTabStrip::ShouldShowPinnedTabsInGrid() const {
...
+  // TabStrip::Initialize() is never called because it's only used by
+  // horizontal tab mode so tab_container_ remains null.
+  // This method must bail out early to avoid crashing when accessing it.
+  if (!tabs::utils::SupportsBraveVerticalTabs(GetBrowserWindowInterface())) {
+    return;
+  }
```
Comment (sangwoo108) [inline browser/ui/views/tabs/brave_tab_strip.cc]: If there's no call sites except AddedToWidget(), how about early return there and make this CHECK()?

**Review by sangwoo108 — APPROVED** [review]
LGTM

File: browser/ui/views/tabs/brave_tab_strip.cc (hunk 4 above)
Comment (simonhong) [reply browser/ui/views/tabs/brave_tab_strip.cc]: Updated in that way. thanks!

**Review by netzenbot — APPROVED** [review]
