### PR TITLE
[iOS] Fix add to playlist button does not show up

### LINKED ISSUE #55040: [iOS] Add to Playlist button doesn't show up after switch to another short video
### Description

Add to Playlist button doesn't show up after switch to another short video

https://github.com/user-attachments/assets/118d4b88-d23b-49cf-9525-1f57391e75cf

### Steps to reproduce

1. open youtube
2. go to shorts tab
3. verify the add to playlist button appears in toolbar 
4. swipe up to the next short video 

### Actual result

add to playlist button disappears while the video is playing 

### Expected result

add to playlist button should be available for user to tap

### Reproduces how often

Intermittent issue

### Brave version

nightly 

### Device/iOS version

all

### Affected browser versions

- [ ] latest AppStore
- [ ] latest TestFlight
- [ ] previous TestFlight

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] in the latest version of mobile Safari

### Miscellaneous information

_No response_

### PR DESCRIPTION
**Pull request by nuo-xu**
`updateURLBar()` reads `tab.playlistItem` inside `DispatchQueue.main.async` which deferred to the next run loop cycle. But `PlaylistScriptHandler` is also a tab observer, and its `tabDidUpdateURL` fires synchronously and immediately clears `tab.playlistItem` to nil via `updatePlaylistURLBar(state: .none, item: nil)`. By the time `updateURLBar`'s async block actually runs, `tab.playlistItem` is already nil.
The changes is to ensure `updateURLBar` reflects the playlist state at the moment it was called, before any observer chain side-effects run asynchronously

Resolves https://github.com/brave/brave-browser/issues/55040

Test:
Please refer to the issue

### CODE REVIEW

File: ios/brave-ios/Sources/Brave/Frontend/Browser/BrowserViewController/BrowserViewController.swift [hunk 1]
```diff
@@ -1825,8 +1825,9 @@ public class BrowserViewController: UIViewController {
 
     updateRewardsButtonState()
 
+    let playlistItem = tab.playlistItem
     DispatchQueue.main.async {
-      if let item = tab.playlistItem {
+      if let item = playlistItem {
```
Comment (kylehickinson) [inline ios/brave-ios/Sources/Brave/Frontend/Browser/BrowserViewController/BrowserViewController.swift:1830]: Lets clean this up a bit so that all the logic checks happen synchronously and only the `updatePlaylistURLBar` call happens async on main that way we dont possibly add other race conditions. example:

```
let playlistItem = tab.playlistItem
let state = ...
DispatchQueue.main.async {
  self.updatePlaylistURLBar(tab: tab, state: state, item: playlistItem)
}
```

Comment (kylehickinson) [reply ios/brave-ios/Sources/Brave/Frontend/Browser/BrowserViewController/BrowserViewController.swift:1830]: Actually I guess that will cause issues with CoreData (`PlaylistItem`) needing to run on main anyways…

**Review by kylehickinson — APPROVED** [review]

**Review by netzenbot — APPROVED** [review]

**Comment by hffvld** [comment]
#### 🟢 Verification PASSED using the following:

```
Device/OS:
- iPhone 14 / iOS 26.4.2

Brave:
- Build: 1.92 (61)
- BraveCore: 1.92.61 (148.0.7778.167)
```

#### STEPS:
1. Launch Brave
2. Open YT in the new tab
3. Go to `Shorts` tab > *Verify that `Add to Playlist` button is shown in the toolbar*
4. Scroll through the shorts list > *Verify that `Add to Playlist` utton is shown in the toolbar*

#### ACTUAL RESULTS:
- Verified that the `Add to Playlist` button is displayed in the toolbar while scrolling through the `Shorts` list.
- Verified that the `Add to Playlist` button is displayed in the toolbar when opening a regular video on YT, followed by opening another video.
- Verified that videos can be added to a `Playlist` via the `Add to Playlist` button in the toolbar, `Hamburger menu > Add to Playlist`, or by long-pressing and selecting `Add to Brave Playlist`.

#### SCREENSHOT / SCREENCAST:

| Shorts | Regular video |
|:-:|:-:|
| <video src="https://github.com/user-attachments/assets/1a57c2e4-562a-4b99-bd3d-03c546ce5eb1"></video> | <video src="https://github.com/user-attachments/assets/946827c8-bfda-4be4-b5ce-db8dbdcf10e6"></video> |
