### PR TITLE
Cached adblock dat

### LINKED ISSUE #27161: Cache adblock DATs clientside for better performance on browser startup
## Test plan
See https://github.com/brave/brave-browser/issues/27161#issuecomment-4315136728

## Description
_Note: The benchmarks below are outdated following the migration of adblock-rust to Flatbuffers, yet the motivation and theory are still valid_

We switched adblock lists to be served as plaintext components rather than serialized DATs in https://github.com/brave/brave-core/pull/15077. Loading adblock lists from plaintext is _slightly_ slower than loading from a serialized DAT, although it leaves us the option of serializing them clientside to the newer uncompressed format which can be deserialized _significantly_ faster. As per https://github.com/brave/brave-core/pull/15077:

> ### Performance analysis
> 
> Benchmarking `adblock-rust` on my own computer shows a minor perf impact related to list parsing at startup, of an additional ~56ms or 32% regression for the entire set of default lists. Note that an additional change can allow adblock-rust to cache compiled DATs in uncompressed format after updates, resulting in a significant improvement to engine load time over the current `master` branch. I've left the caching for a followup to minimize the number of changes in this PR.
> 
> The benchmark results below show the engine load times for the current `master` configuration, the configuration as of this PR, and the configuration with caching, respectively (middle time value is average).
> 
> ```
> from_dat                 time:   [173.66 ms 174.88 ms 176.32 ms]
> from_plaintext           time:   [228.08 ms 230.97 ms 233.52 ms]
> from_uncompressed_dat    time:   [46.191 ms 46.777 ms 47.546 ms]
> ```

Brave should create a cached adblock DAT whenever lists are modified, and load this on startup to reduce load at browser-launch. Also, there is currently no code in place to prevent pages from loading before the adblock engines are ready, so this is important to help ads be caught on startup.

### PR DESCRIPTION
**Pull request by bridiver**
Resolves https://github.com/brave/brave-browser/issues/27161

### CODE REVIEW

File: components/brave_shields/content/browser/ad_block_service.cc [hunk 1]
```diff
@@ -86,43 +161,56 @@ void AdBlockService::SourceProviderObserver::OnFilterSetCallbackLoaded(
...
+           AdblockResourceStorageBox storage, base::FilePath cache_file,
+           base::Time timestamp) {
+          if (engine) {
+            engine->Load(std::move(*filter_set.get()), *storage);
+            base::WriteFile(cache_file, engine->Serialize());
+          }
+        },
+        adblock_engine_->AsWeakPtr(), std::move(filter_set_),
+        std::move(storage), cache_file, timestamp_);
+    local_state_->SetInt64(cache_timestamp_pref_,
```
Comment (bridiver) [inline components/brave_shields/content/browser/ad_block_service.cc]: you can't set the timestamp until after the file is written or you create a race condition

File: components/brave_shields/content/browser/ad_block_service.cc [hunk 2]
```diff
@@ -193,18 +261,36 @@ AdBlockService::AdBlockService(
...
+        base::Time cache_timestamp = local_state->GetTime(pref_name);
+
+        if (timestamp <= cache_timestamp && cache_timestamp != base::Time() &&
+            !(cache_timestamp > base::Time::Now())) {
+          // Skip updates that have already been cached.
+          return false;
+        }
+        return true;
+      },
+      base::Unretained(local_state_));
```
Comment (bridiver) [inline components/brave_shields/content/browser/ad_block_service.cc]: this isn't safe, fixing

Comment (bridiver) [reply components/brave_shields/content/browser/ad_block_service.cc]: actually it is safe, but going to clean this up anyway to get rid of the lambda here

File: ios/brave-ios/Sources/Brave/Frontend/Browser/BrowserViewController/BrowserViewController.swift [hunk 3]
```diff
@@ -391,7 +391,7 @@ public class BrowserViewController: UIViewController {
       screenTimeViewController = STWebpageController()
     }
 
-    braveCore.adblockService.registerFilterListChanges { [weak self] _ in
+    braveCore.adblockService.registerFilterListChanges { [weak self] _, _ in
```
Comment (EliHini) [inline ios/brave-ios/Sources/Brave/Frontend/Browser/BrowserViewController/BrowserViewController.swift]: 👍

File: ios/brave-ios/Sources/Brave/WebFilters/FilterListResourceDownloader.swift [hunk 4]
```diff
@@ -139,7 +139,7 @@ extension AdblockService {
     GroupedAdBlockEngine.EngineType
   > {
     return AsyncStream { continuation in
-      registerFilterListChanges({ isDefaultFilterList in
+      registerFilterListChanges({ isDefaultFilterList, _ in
```
Comment (EliHini) [inline ios/brave-ios/Sources/Brave/WebFilters/FilterListResourceDownloader.swift]: 👍

File: components/brave_shields/content/browser/ad_block_subscription_filters_provider.cc [hunk 5]
```diff
@@ -69,6 +71,13 @@ std::string AdBlockSubscriptionFiltersProvider::GetNameForDebugging() {
   return "AdBlockSubscriptionFiltersProvider";
 }
 
+void AdBlockSubscriptionFiltersProvider::CacheTimestampAndNotifyObservers(
+    bool engine_is_default,
```
Comment (atuchin-m) [inline components/brave_shields/content/browser/ad_block_subscription_filters_provider.cc]: nit: can we just use `engine_is_default_`?

File: components/brave_shields/content/browser/ad_block_subscription_filters_provider.cc [hunk 6]
```diff
@@ -91,8 +100,27 @@ void AdBlockSubscriptionFiltersProvider::OnDATFileDataReady(
       dat_buf, flow));
 }
 
-void AdBlockSubscriptionFiltersProvider::OnListAvailable() {
-  NotifyObservers(engine_is_default_);
+void AdBlockSubscriptionFiltersProvider::OnListAvailable(bool force_new) {
+  if (force_new) {
```
Comment (bridiver) [inline components/brave_shields/content/browser/ad_block_subscription_filters_provider.cc]: something is definitely not right here, I think this should work just like the component provider so fixing now

File: components/brave_shields/core/browser/ad_block_component_filters_provider.cc [hunk 7]
```diff
@@ -120,10 +132,43 @@ void AdBlockComponentFiltersProvider::OnComponentReady(
...
 }
 
+void AdBlockComponentFiltersProvider::OnComponentReady(
+    const base::FilePath& path) {
+  TRACE_EVENT(
+      "brave.adblock", "AdBlockComponentFiltersProvider::OnComponentReady",
+      perfetto::TerminatingFlow::FromPointer(this), "path", path.value());
+
+  base::ThreadPool::PostTaskAndReplyWithResult(
+      FROM_HERE, {base::TaskPriority::BEST_EFFORT, base::MayBlock()},
```
Comment (atuchin-m) [inline components/brave_shields/core/browser/ad_block_component_filters_provider.cc]: `BEST_EFFORT` means sometimes when we have free cycles. usually it's not what we want.

Comment (bridiver) [reply components/brave_shields/core/browser/ad_block_component_filters_provider.cc]: oops, yep, will fix

Comment (atuchin-m) [reply components/brave_shields/core/browser/ad_block_component_filters_provider.cc]: and the following work (triggered by NofityObservers) uses `USER_BLOCKING`

File: components/brave_shields/content/browser/ad_block_subscription_filters_provider.cc [hunk 8]
```diff
@@ -69,6 +77,35 @@ std::string AdBlockSubscriptionFiltersProvider::GetNameForDebugging() {
...
+    update->Set(GetCacheKey(), base::TimeToValue(info.last_modified));
+  }
+  NotifyObservers(engine_is_default_, info.last_modified);
+}
+
+std::string AdBlockSubscriptionFiltersProvider::GetCacheKey() const {
+  return list_file_.BaseName().RemoveExtension().MaybeAsASCII();
+}
+
+base::Time AdBlockSubscriptionFiltersProvider::timestamp() const {
```
Comment (atuchin-m) [inline components/brave_shields/content/browser/ad_block_subscription_filters_provider.cc]: nit: according to CC it should be `GetTimestamp()`

Comment (bridiver) [reply components/brave_shields/content/browser/ad_block_subscription_filters_provider.cc]: yeah I was thinking about it as a simple accessor, but it's not in some cases

File: components/brave_shields/core/browser/ad_block_component_filters_provider.cc [hunk 9]
```diff
@@ -103,15 +113,17 @@ void AdBlockComponentFiltersProvider::UnregisterComponent() {
...
-    const base::FilePath& path) {
-  TRACE_EVENT(
-      "brave.adblock", "AdBlockComponentFiltersProvider::OnComponentReady",
-      perfetto::TerminatingFlow::FromPointer(this), "path", path.value());
+void AdBlockComponentFiltersProvider::OnGetNewPathFileInfo(
+    base::FilePath path,
+    base::File::Info info) {
   base::FilePath old_path = component_path_;
   component_path_ = path;
+  last_updated_ = info.last_modified;
```
Comment (atuchin-m) [inline components/brave_shields/core/browser/ad_block_component_filters_provider.cc]: I wonder can we use the component version instead of timestamp
* this allows to avoid an extra thread hope.
* `mtime` sounds less reliable than the version. And harder to debug

File: components/brave_shields/content/browser/ad_block_service.cc [hunk 10]
```diff
@@ -38,39 +48,69 @@
...
 }
 
 AdBlockService::SourceProviderObserver::~SourceProviderObserver() {
   filters_provider_manager_->RemoveObserver(this);
   resource_provider_->RemoveObserver(this);
 }
 
-void AdBlockService::SourceProviderObserver::OnChanged(bool is_default_engine) {
+void AdBlockService::SourceProviderObserver::OnChanged(bool is_default_engine,
+                                                       base::Time timestamp) {
```
Comment (atuchin-m) [inline components/brave_shields/content/browser/ad_block_service.cc]: is it the timestamp of the last loaded components or the most recent once (across the whole set)?

File: components/brave_shields/content/browser/ad_block_service.cc [hunk 11]
```diff
@@ -84,22 +124,35 @@ void AdBlockService::SourceProviderObserver::OnFilterSetCallbackLoaded(
...
+  TRACE_EVENT("brave.adblock", "OnFilterSetCreated");
+  filter_set_ = std::move(filter_set);
+  timestamp_ = std::move(timestamp);
+  LoadResources();
+}
+
 void AdBlockService::SourceProviderObserver::OnResourcesLoaded(
     AdblockResourceStorageBox storage) {
-  on_resources_loaded_.Run(engine_is_default_, std::move(filter_set_),
+  on_resources_loaded_.Run(engine_is_default_, std::move(dat_),
```
Comment (atuchin-m) [inline components/brave_shields/content/browser/ad_block_service.cc]: `std::move` leave `dat_` in an unspecified state.
If the method is called again without updating `dat_` we get a crash.

File: components/brave_shields/content/browser/ad_block_service.cc [hunk 12]
```diff
@@ -213,6 +282,122 @@ AdBlockService::~AdBlockService() {
...
+      local_state_->SetTime(cache_timestamp_pref_name(is_default_engine),
+                            timestamp);
+    }
+  }
+  for (auto& observer : observers_) {
+    observer.OnFilterListLoaded(is_default_engine, success);
+  }
+}
+
+void AdBlockService::OnReadCachedDATFiles(
```
Comment (atuchin-m) [inline components/brave_shields/content/browser/ad_block_service.cc:338]: I would say DAT reading should be implemented per-engine basis (not on the service level).
This also removes multiple calls like `NotifyOnDATLoaded(true, false);`

File: components/brave_shields/core/browser/ad_block_component_filters_provider.cc (hunk 9 above)
Comment (bridiver) [reply components/brave_shields/core/browser/ad_block_component_filters_provider.cc]: using something else adds substantial complexity, but the hop is not needed, we should cache the timestamp when the file is written to disk

File: components/brave_shields/content/browser/ad_block_service.cc (hunk 12 above)
Comment (bridiver) [reply components/brave_shields/content/browser/ad_block_service.cc:338]: It is per-engine. I am trying to avoid a lot of refactoring here so can you be more specific about the change you're suggesting?

File: components/brave_shields/content/browser/ad_block_service.cc (hunk 11 above)
Comment (bridiver) [reply components/brave_shields/content/browser/ad_block_service.cc]: it should be properly cleared, but it won't crash because std::move leaves it in a valid but unspecified state

File: components/brave_shields/core/browser/ad_block_component_filters_provider.cc [hunk 13]
```diff
@@ -120,10 +132,43 @@ void AdBlockComponentFiltersProvider::OnComponentReady(
   }
```
Comment (netzenbot) [inline components/brave_shields/core/browser/ad_block_component_filters_provider.cc:120]: `local_state_` can be null in unit tests (documented in the constructor comment), but `timestamp()` dereferences it unconditionally. The other providers added in this same PR (`AdBlockSubscriptionFiltersProvider`, `AdBlockCustomFiltersProvider`) both guard with `if (!local_state_) { CHECK_IS_TEST(); ... }` — this one is missing that guard.

File: components/brave_shields/content/browser/ad_block_service.h [hunk 14]
```diff
@@ -160,11 +193,28 @@ class AdBlockService {
...
+  bool ShouldLoadFilterState(bool is_default_engine, base::Time timestamp);
+
+  std::string_view cache_timestamp_pref_name(bool engine_is_default);
+
+  void OnResourcesLoaded(
+      bool is_default_engine,
+      DATFileDataBuffer dat,
+      std::unique_ptr<rust::Box<adblock::FilterSet>> filter_set,
+      base::Time timestamp,
+      AdblockResourceStorageBox storage);
```
Comment (netzenbot) [inline components/brave_shields/content/browser/ad_block_service.h:205]: The header declares `NotifyOnDATLoaded(bool success, bool is_default_engine)` but the implementation defines it as `NotifyOnDATLoaded(bool is_default_engine, bool success)` — the parameter order is swapped. Since both params are `bool`, this compiles silently but documents the wrong calling convention. The callers all use `(is_default_engine, success)` order (matching the implementation), so behavior is correct — but the declaration should match to avoid confusion.

File: components/brave_shields/content/browser/ad_block_service.h [hunk 15]
```diff
@@ -160,11 +193,28 @@ class AdBlockService {
...
+
+  void NotifyOnDATLoaded(bool success, bool is_default_engine);
+  void OnDatCached(bool is_default_engine, base::Time timestamp, bool success);
```
Comment (netzenbot) [inline components/brave_shields/content/browser/ad_block_service.h]: The declaration in the header has the parameter order swapped relative to the definition in `.cc`. Header says `(bool success, bool is_default_engine)` but the implementation has `(bool is_default_engine, bool success)`. Both params are `bool` so this compiles silently, but `success` and `is_default_engine` get swapped at every call site — all callers pass `is_default_engine` first, which matches the `.cc` but not the header. Fix the header declaration to match the implementation: `void NotifyOnDATLoaded(bool is_default_engine, bool success);` ([Naming Conventions](https://github.com/brave/brave-core/tree/master/docs/best-practices/coding-standards.md#CS-002))

File: components/brave_shields/content/test/ad_block_service_unittest.cc [hunk 16]
```diff
@@ -0,0 +1,698 @@
...
+      "||blocked-by-filter.com^");
+
+  base::RunLoop on_changed_run_loop;
+  service_task_runner->PostTask(FROM_HERE, on_changed_run_loop.QuitClosure());
+  while (!on_changed_run_loop.AnyQuitCalled()) {
+    if (service_task_runner->HasPendingTask()) {
+      service_task_runner->FastForwardBy(
+          service_task_runner->NextPendingTaskDelay());
+    } else {
+      base::RunLoop().RunUntilIdle();
```
Comment (netzenbot) [inline components/brave_shields/content/test/ad_block_service_unittest.cc]: `base::RunLoop().RunUntilIdle()` is banned — it's non-deterministic and flagged by both presubmit and [TA-005](https://github.com/brave/brave-core/tree/master/docs/best-practices/testing-async.md#TA-005). The `FilterSetLoadingBlocksDATLoading` and `ValidCacheTimestampSkipsFilterSetLoad` tests use it repeatedly. Replace with `base::test::RunUntil()` on a concrete condition, or `TestFuture` if an observable callback is available.

File: components/brave_shields/core/browser/ad_block_default_resource_provider.cc [hunk 17]
```diff
@@ -74,6 +76,11 @@ void AdBlockDefaultResourceProvider::OnComponentReady(
```
Comment (netzenbot) [inline components/brave_shields/core/browser/ad_block_default_resource_provider.cc:74]: The new `storage_testing_override_` optional and the `if (storage_testing_override_.has_value())` early-return inside `LoadResources` are production code paths that only exist to support tests — the presubmit also flagged `OverrideResourcesForTesting` for this. A cleaner approach is to subclass or inject a fake `AdBlockDefaultResourceProvider` in tests rather than polluting production `LoadResources` with a test hook. See [CSA-035](https://github.com/brave/brave-core/tree/master/docs/best-practices/coding-standards-apis.md#CSA-035).

File: components/brave_shields/content/browser/ad_block_service.cc (hunk 11 above)
Comment (atuchin-m) [reply components/brave_shields/content/browser/ad_block_service.cc]: my point is it could crash if the method is called **again** , not after the first `std::move()` of course

Comment (bridiver) [reply components/brave_shields/content/browser/ad_block_service.cc]: Of course we should change this, but it would not crash because move leaves it in a valid state, that state is just unspecified. Most likely it would be left empty, but we shouldn't rely on that

Comment (bridiver) [reply components/brave_shields/content/browser/ad_block_service.cc]: just for clarity I'm going to change them both to std::exchange even though the filter list move is fine as-is

File: components/brave_shields/content/test/ad_block_service_unittest.cc (hunk 16 above)
Comment (bridiver) [reply components/brave_shields/content/test/ad_block_service_unittest.cc]: Actually these take a race condition and make it deterministic for the test. I cannot find any other way to step through this in a way that causes the race condition every time. It is not strictly banned, but needs to be used very carefully (which I have done)

File: components/brave_shields/content/browser/ad_block_engine_wrapper.cc [hunk 18]
```diff
@@ -106,20 +106,42 @@ adblock::BlockerResult AdBlockEngineWrapper::ShouldStartRequest(
...
+DATFileDataBuffer AdBlockEngineWrapper::Serialize(bool is_default_engine) {
+  DCHECK_CALLED_ON_VALID_SEQUENCE(sequence_checker_);
+  auto* engine = is_default_engine ? default_engine_.get()
+                                   : additional_filters_engine_.get();
+  return engine->Serialize();
+}
+
 std::optional<std::string> AdBlockEngineWrapper::GetCspDirectives(
     const GURL& url,
     blink::mojom::ResourceType resource_type,
```
Comment (netzenbot) [inline components/brave_shields/content/browser/ad_block_engine_wrapper.cc:146]: nit: `Load()` and `LoadDAT()` return `bool` for success/failure, but [CS-028](https://github.com/brave/brave-core/tree/master/docs/best-practices/coding-standards.md#CS-028) recommends using result code enums instead of `bool` for operations that can fail. A small enum (e.g., `LoadResult::kSuccess`/`kDeserializeFailed`) would allow callers to distinguish failure reasons without ambiguity and is more future-proof.

File: components/brave_shields/content/test/ad_block_service_unittest.cc [hunk 19]
```diff
@@ -0,0 +1,726 @@
...
+  }
+
+  base::test::TaskEnvironment task_environment_;
+};
+
+class AdBlockServiceQueuedTest : public AdBlockServiceTestBase {
+ public:
+  AdBlockServiceQueuedTest() {
+    feature_list_.InitAndEnableFeature(features::kAdblockDATCache);
+  }
```
Comment (netzenbot) [inline components/brave_shields/content/test/ad_block_service_unittest.cc:175]: nit: `"adblock_cache"`, `"engine0.dat"`, and `"engine1.dat"` are re-hardcoded here but already defined as named constants (`kAdblockCacheDir`, `kAdBlockEngine0DATCache`, `kAdBlockEngine1DATCache`) in the production `.cc` file's anonymous namespace. Moving them to a shared internal header (or exposing them via a `*_constants.h`) would avoid the duplication and prevent silent drift if the paths change. ([BS-048](https://github.com/brave/brave-core/tree/master/docs/best-practices/build-system.md#BS-048))

File: components/brave_shields/core/browser/ad_block_filters_provider_manager.cc [hunk 20]
```diff
@@ -45,18 +48,55 @@ void AdBlockFiltersProviderManager::RemoveProvider(
...
+    bool is_for_default_engine) const {
   auto& filters_providers = is_for_default_engine
                                 ? default_engine_filters_providers_
                                 : additional_engine_filters_providers_;
-  for (auto*& provider : filters_providers) {
+  std::vector<std::string> hashes;
+  for (auto* const& provider : filters_providers) {
     if (!provider->IsInitialized()) {
-      return;
+      return std::string();
```
Comment (netzenbot) [inline components/brave_shields/core/browser/ad_block_filters_provider_manager.cc]: nit: The manual separator loop in `ComputeCombinedHash` can be replaced with `base::JoinString(hashes, "|")` from `base/strings/string_util.h`. ([CSA-001](https://github.com/brave/brave-core/tree/master/docs/best-practices/coding-standards-apis.md#CSA-001))

File: components/brave_shields/content/browser/ad_block_service.h [hunk 21]
```diff
@@ -57,46 +64,64 @@ class AdBlockSubscriptionServiceManager;
...
 
     OnResourcesLoadedCallback on_resources_loaded_;
-    std::unique_ptr<rust::Box<adblock::FilterSet>> filter_set_;
-    const bool engine_is_default_;
     raw_ptr<AdBlockResourceProvider> resource_provider_ = nullptr;  // not owned
     raw_ptr<AdBlockResourceProvider> custom_resource_provider_ =
         nullptr;  // not owned
     raw_ptr<AdBlockFiltersProviderManager> filters_provider_manager_ =
         nullptr;  // not owned
+    ShouldLoadFilterSetCallback should_load_filter_set_;
```
Comment (netzenbot) [inline components/brave_shields/content/browser/ad_block_service.h]: nit: The PR moves `filter_set_` (unique_ptr) and adds `dat_` after the `raw_ptr` members, reversing the pre-existing correct ordering. Per [CSM-013](https://github.com/brave/brave-core/tree/master/docs/best-practices/coding-standards-memory.md#CSM-013), unowned `raw_ptr<>` members should come after owning members (`unique_ptr`, etc.). Consider keeping `filter_set_` and `dat_` before `resource_provider_`, `custom_resource_provider_`, and `filters_provider_manager_`.

File: components/brave_shields/core/browser/ad_block_filters_provider_manager.h [hunk 22]
```diff
@@ -6,6 +6,7 @@
 #ifndef BRAVE_COMPONENTS_BRAVE_SHIELDS_CORE_BROWSER_AD_BLOCK_FILTERS_PROVIDER_MANAGER_H_
 #define BRAVE_COMPONENTS_BRAVE_SHIELDS_CORE_BROWSER_AD_BLOCK_FILTERS_PROVIDER_MANAGER_H_
 
+#include <algorithm>
```
Comment (netzenbot) [inline components/brave_shields/core/browser/ad_block_filters_provider_manager.h]: nit: `<algorithm>` is only used in the `.cc` implementation of `ComputeCombinedHash` (for `std::sort`), not in any header declaration. Move the `#include <algorithm>` to `ad_block_filters_provider_manager.cc` where it's actually needed. ([IWYU](https://github.com/brave/brave-core/tree/master/docs/best-practices/coding-standards.md#CS-001))

**Comment by bridiver** [comment]
> The deserialization is handled by the Rust library, which should be memory-safe, but the integrity of cached files is not verified (no signature or HMAC).

@brave/sec-team wdyt about this? If an attacker can alter the dat file they could presumably also alter any hmac we stored so not sure if this is a concern or not or any different from altering the filter list directly or inserting malicious filters into custom filters through prefs?

File: components/brave_shields/content/browser/ad_block_subscription_filters_provider.cc [hunk 23]
```diff
@@ -92,7 +128,21 @@ void AdBlockSubscriptionFiltersProvider::OnDATFileDataReady(
 }
 
 void AdBlockSubscriptionFiltersProvider::OnListAvailable() {
-  NotifyObservers(engine_is_default_);
+  base::ThreadPool::PostTaskAndReplyWithResult(
```
Comment (bridiver) [inline components/brave_shields/content/browser/ad_block_subscription_filters_provider.cc]: this is wrong, there shouldn't be an extra read here. Fixing

File: components/brave_shields/content/browser/ad_block_subscription_filters_provider.cc [hunk 24]
```diff
@@ -69,13 +75,41 @@ std::string AdBlockSubscriptionFiltersProvider::GetNameForDebugging() {
...
+  return list_file_.BaseName().RemoveExtension().MaybeAsASCII();
+}
+
+std::string AdBlockSubscriptionFiltersProvider::GetContentHash() const {
+  if (!content_hash_.empty()) {
+    return content_hash_;
+  }
+  if (local_state_) {
+    const auto& dict =
+        local_state_->GetDict(prefs::kAdBlockSubscriptionFiltersCacheTimestamp);
```
Comment (bridiver) [inline components/brave_shields/content/browser/ad_block_subscription_filters_provider.cc]: cache key names need to be updated

File: components/brave_shields/core/browser/ad_block_component_filters_provider.cc [hunk 25]
```diff
@@ -120,10 +135,54 @@ void AdBlockComponentFiltersProvider::OnComponentReady(
...
+  }
+  // On startup, before OnComponentReady fires, read persisted hash from prefs.
+  if (local_state_) {
+    const auto& dict =
+        local_state_->GetDict(prefs::kAdBlockComponentFiltersCacheTimestamp);
+    const std::string* stored = dict.FindString(GetCacheKey());
+    if (stored) {
+      return *stored;
+    }
+  }
```
Comment (bridiver) [inline components/brave_shields/core/browser/ad_block_component_filters_provider.cc]: check_is_test

File: components/brave_shields/core/browser/ad_block_component_filters_provider.cc [hunk 26]
```diff
@@ -120,10 +139,55 @@ void AdBlockComponentFiltersProvider::OnComponentReady(
...
+      FROM_HERE, {base::TaskPriority::USER_BLOCKING, base::MayBlock()},
+      base::BindOnce(
+          [](const base::FilePath& path) {
+            auto list_path = path.AppendASCII(kListFile);
+            std::optional<std::vector<uint8_t>> content =
+                base::ReadFileToBytes(list_path);
+            if (!content) {
+              return std::string();
+            }
+            return base::HexEncode(crypto::SHA256HashString(
```
Comment (atuchin-m) [inline components/brave_shields/core/browser/ad_block_component_filters_provider.cc]: the extra file reading + hash calculation for 5MB of filters (in total) definitely has some perf costs.
Why we can't just use SHA256(component-id + component-version) instead?
Also, this allows to avoid an extra thread hope.

File: components/brave_shields/content/browser/ad_block_custom_filters_provider.cc [hunk 27]
```diff
@@ -81,6 +84,16 @@ std::string AdBlockCustomFiltersProvider::GetNameForDebugging() {
   return "AdBlockCustomFiltersProvider";
 }
 
+std::optional<std::string> AdBlockCustomFiltersProvider::GetContentHash()
+    const {
+  if (!local_state_) {
+    CHECK_IS_TEST();
+    return base::HexEncode(crypto::SHA256HashString(std::string()));
+  }
+  return base::HexEncode(crypto::SHA256HashString(
```
Comment (atuchin-m) [inline components/brave_shields/content/browser/ad_block_custom_filters_provider.cc]: Should we memoize this?

File: components/brave_shields/content/browser/ad_block_subscription_filters_provider.cc [hunk 28]
```diff
@@ -69,13 +76,42 @@ std::string AdBlockSubscriptionFiltersProvider::GetNameForDebugging() {
...
 void AdBlockSubscriptionFiltersProvider::OnDATFileDataReady(
     base::OnceCallback<
         void(base::OnceCallback<void(rust::Box<adblock::FilterSet>*)>)> cb,
     const perfetto::Flow& flow,
     const DATFileDataBuffer& dat_buf) {
   TRACE_EVENT("brave.adblock",
               "AdBlockSubscriptionFiltersProvider::OnDATFileDataReady", flow);
+  // Compute the content hash while we have the data in hand.
+  content_hash_ = base::HexEncode(
+      crypto::SHA256HashString(std::string(dat_buf.begin(), dat_buf.end())));
```
Comment (atuchin-m) [inline components/brave_shields/content/browser/ad_block_subscription_filters_provider.cc]: Do we really need slow crypto-resistant SHA256?
WDYT about `base::PersistentHash` or `base::FastHash`? The last one can be updated from time to time, but it looks okay to use.

File: components/brave_shields/content/browser/ad_block_custom_filters_provider.cc (hunk 27 above)
Comment (atuchin-m) [reply components/brave_shields/content/browser/ad_block_custom_filters_provider.cc]: Also, do we have any limits for `kAdBlockCustomFilters` size? If it's huge, it could affect UI thread latency.

File: components/brave_shields/content/browser/ad_block_subscription_filters_provider.cc [hunk 29]
```diff
@@ -69,13 +76,42 @@ std::string AdBlockSubscriptionFiltersProvider::GetNameForDebugging() {
...
+}
+
 void AdBlockSubscriptionFiltersProvider::OnDATFileDataReady(
     base::OnceCallback<
         void(base::OnceCallback<void(rust::Box<adblock::FilterSet>*)>)> cb,
     const perfetto::Flow& flow,
     const DATFileDataBuffer& dat_buf) {
   TRACE_EVENT("brave.adblock",
               "AdBlockSubscriptionFiltersProvider::OnDATFileDataReady", flow);
+  // Compute the content hash while we have the data in hand.
```
Comment (atuchin-m) [inline components/brave_shields/content/browser/ad_block_subscription_filters_provider.cc]: We should move it out from UI thread.

File: components/brave_shields/content/browser/ad_block_subscription_filters_provider.cc [hunk 30]
```diff
@@ -69,13 +76,42 @@ std::string AdBlockSubscriptionFiltersProvider::GetNameForDebugging() {
...
+std::string AdBlockSubscriptionFiltersProvider::GetCacheKey() const {
+  return list_file_.BaseName().RemoveExtension().MaybeAsASCII();
+}
+
+std::optional<std::string> AdBlockSubscriptionFiltersProvider::GetContentHash()
+    const {
+  if (!content_hash_.empty()) {
+    return content_hash_;
+  }
+  if (local_state_) {
```
Comment (atuchin-m) [inline components/brave_shields/content/browser/ad_block_subscription_filters_provider.cc]: It's not clear what `GetContentHash()` returns in general. 
Is it the hash of the current content hash or the cached ones?

File: components/brave_shields/content/browser/ad_block_subscription_filters_provider.cc [hunk 31]
```diff
@@ -92,6 +128,11 @@ void AdBlockSubscriptionFiltersProvider::OnDATFileDataReady(
 }
 
 void AdBlockSubscriptionFiltersProvider::OnListAvailable() {
+  // Clear the in-memory hash so ComputeCombinedHash produces a different
```
Comment (atuchin-m) [inline components/brave_shields/content/browser/ad_block_subscription_filters_provider.cc]: I'm not following what happens here. We resets and immediately trigger OnChanged() that could result in making incorrect combined hash.

I also can't see `IsInitialized()` implemented for `AdBlockSubscriptionFiltersProvider`, maybe it's the root of these issues?

File: components/brave_shields/content/browser/ad_block_subscription_filters_provider.cc (hunk 28 above)
Comment (atuchin-m) [reply components/brave_shields/content/browser/ad_block_subscription_filters_provider.cc]: I got the idea: we're trying to save cycles by combining computing the cache with reading the file.

Unfortunately, this could result in using an incorrect old hash in the hash combination code and storing in. As the result the combined hash will not match to the actual content.

Comment (bridiver) [reply components/brave_shields/content/browser/ad_block_subscription_filters_provider.cc]: > Unfortunately, this could result in using an incorrect old hash in the hash combination code and storing in

There should be guards against this, but I'm double checking them

Comment (bridiver) [reply components/brave_shields/content/browser/ad_block_subscription_filters_provider.cc]: > May changed without warning, do not expect stability of outputs.

Not FastHash for sure, but PersistentHash seems fine

File: components/brave_shields/content/browser/ad_block_subscription_filters_provider.cc (hunk 31 above)
Comment (bridiver) [reply components/brave_shields/content/browser/ad_block_subscription_filters_provider.cc]: This is the problem you mentioned here: https://github.com/brave/brave-core/pull/35069/changes#r3057493516

If you wait until the file is read for the filter you have a chicken and egg issue with the hash. It intentionally gets cleared here to avoid this problem. It will not result in an incorrect hash because it won't build the hash if any of them are empty. I'll double check that there is a test covering this

File: components/brave_shields/content/browser/ad_block_subscription_filters_provider.cc (hunk 29 above)
Comment (bridiver) [reply components/brave_shields/content/browser/ad_block_subscription_filters_provider.cc]: need to think about potential race conditions here, do you still think it's an issue with PersistentHash?

File: components/brave_shields/content/browser/ad_block_subscription_filters_provider.cc (hunk 31 above)
Comment (bridiver) [reply components/brave_shields/content/browser/ad_block_subscription_filters_provider.cc]: oh wait, there is a problem here, I'm not sure why it has `content_hash_` in the first place instead of checking the pref directly, that does potentially cause the issue you described above.

File: components/brave_shields/core/browser/ad_block_default_resource_provider.cc (hunk 17 above)
Comment (bridiver) [reply components/brave_shields/core/browser/ad_block_default_resource_provider.cc:74]: yes, this is bad. Will update

File: components/brave_shields/content/browser/ad_block_subscription_filters_provider.cc (hunk 29 above)
Comment (bridiver) [reply components/brave_shields/content/browser/ad_block_subscription_filters_provider.cc]: related `OnDATFileDataReady` here is very confusing because this is the raw filter list. We should change this in a follow-up

File: components/brave_shields/content/browser/ad_block_subscription_filters_provider.cc (hunk 28 above)
Comment (atuchin-m) [reply components/brave_shields/content/browser/ad_block_subscription_filters_provider.cc]: > May changed without warning, do not expect stability of outputs.

I saw it, but I don't see it as a problem. If the change the hash function, we get extra ruleset rebuilding on time.
I believe it's fine.

File: components/brave_shields/content/browser/ad_block_subscription_filters_provider.cc (hunk 29 above)
Comment (atuchin-m) [reply components/brave_shields/content/browser/ad_block_subscription_filters_provider.cc]: >need to think about potential race conditions here, do you still think it's an issue with PersistentHash?

Not sure, but it's still dozen of megabytes in the worse case scenario. 

Can we just replace `brave_component_updater::ReadDATFileData` to `ReadDATFileDataAndCalcHash` and pass it back to UI thread in `OnDATFileDataReady()`?

File: components/brave_shields/content/browser/ad_block_service.cc (hunk 12 above)
Comment (bridiver) [reply components/brave_shields/content/browser/ad_block_service.cc:338]: I guess you're saying to split the reading into two separate tasks instead of one? That definitely makes sense, but I worry it might complicate the startup in terms of race conditions. I'll take a look

File: components/brave_shields/core/browser/ad_block_component_filters_provider.cc [hunk 32]
```diff
@@ -120,10 +137,53 @@ void AdBlockComponentFiltersProvider::OnComponentReady(
...
 
+void AdBlockComponentFiltersProvider::OnComponentReady(
+    const base::FilePath& path) {
+  TRACE_EVENT(
+      "brave.adblock", "AdBlockComponentFiltersProvider::OnComponentReady",
+      perfetto::TerminatingFlow::FromPointer(this), "path", path.value());
+
+  base::ThreadPool::PostTaskAndReplyWithResult(
+      FROM_HERE, {base::TaskPriority::USER_BLOCKING, base::MayBlock()},
+      base::BindOnce(
```
Comment (bridiver) [inline components/brave_shields/core/browser/ad_block_component_filters_provider.cc]: extra read isn't needed, removing

File: components/brave_shields/content/browser/ad_block_subscription_filters_provider.cc (hunk 29 above)
Comment (bridiver) [reply components/brave_shields/content/browser/ad_block_subscription_filters_provider.cc]: probably, I'll take a look

File: components/brave_shields/content/browser/ad_block_subscription_filters_provider.cc (hunk 30 above)
Comment (bridiver) [reply components/brave_shields/content/browser/ad_block_subscription_filters_provider.cc]: not sure what you mean, it's the hash for the current contents. Whether it's also the one that is cached is not relevant to this method

Comment (bridiver) [reply components/brave_shields/content/browser/ad_block_subscription_filters_provider.cc]: or are you asking because of content_hash_ vs the the pref? I removed content_hash_because it was unnecessary and could potentially get out of sync

File: components/brave_shields/core/browser/ad_block_component_filters_provider.cc [hunk 33]
```diff
@@ -151,9 +182,32 @@ void AdBlockComponentFiltersProvider::LoadFilterSet(
...
   base::ThreadPool::PostTaskAndReplyWithResult(
       FROM_HERE, {base::MayBlock()},
-      base::BindOnce(&brave_component_updater::ReadDATFileData, list_file_path),
-      base::BindOnce(&OnReadDATFileData, std::move(cb), permission_mask_,
-                     flow));
+      base::BindOnce(
+          [](const base::FilePath& path) {
+            auto buffer = brave_component_updater::ReadDATFileData(path);
+            std::string hash = base::NumberToString(
+                base::FastHash(std::string(buffer.begin(), buffer.end())));
```
Comment (atuchin-m) [inline components/brave_shields/core/browser/ad_block_component_filters_provider.cc]: let's avoid copying the data and use `base::span`

File: components/brave_shields/core/browser/ad_block_filters_provider_manager.cc [hunk 34]
```diff
@@ -45,18 +49,51 @@ void AdBlockFiltersProviderManager::RemoveProvider(
...
     }
+    hashes.push_back(std::move(*hash));
+  }
+  std::sort(hashes.begin(), hashes.end());
+  return base::JoinString(hashes, "|");
+}
+
+void AdBlockFiltersProviderManager::OnChanged(bool is_for_default_engine) {
+  if (!ComputeCombinedHash(is_for_default_engine).has_value()) {
+    // At least one provider is not initialized yet.
```
Comment (atuchin-m) [inline components/brave_shields/core/browser/ad_block_filters_provider_manager.cc]: >  At least one provider is not initialized yet.

+or hash isn't ready ?

For me the relationship between `IsInitialized` and `GetContentHash` isn't clear.
Should we rid off `IsInitialized` in favor of `GetContentHash`?

File: components/brave_shields/content/browser/ad_block_subscription_filters_provider.cc [hunk 35]
```diff
@@ -88,10 +130,19 @@ void AdBlockSubscriptionFiltersProvider::OnDATFileDataReady(
           },
           base::SingleThreadTaskRunner::GetCurrentDefault(),
           on_metadata_retrieved_),
-      dat_buf, flow));
+      result.first, flow));
 }
 
 void AdBlockSubscriptionFiltersProvider::OnListAvailable() {
+  // Clear the persisted hash so ComputeCombinedHash produces a different
```
Comment (atuchin-m) [inline components/brave_shields/content/browser/ad_block_subscription_filters_provider.cc]: I'm still not following what happens here.
We call `OnListAvailable` as a part of startup (not only when the list set is changed).
After `update->Remove(GetCacheKey());` we get `GetContentHash() == std::nullptr` and `NotifyObservers()` does nothing. 

What is suppose to trigger `GetFilterSetPath => .. => OnDATFileDataReady` chain?

Comment (bridiver) [reply components/brave_shields/content/browser/ad_block_subscription_filters_provider.cc]: should be fixed now and test added

File: components/brave_shields/core/test/ad_block_dat_cache_manager_unittest.cc [hunk 36]
```diff
@@ -0,0 +1,211 @@
...
+  AdBlockDATCacheManager cache(&prefs_, &manager_, profile_dir_.GetPath());
+
+  DATFileDataBuffer dat_data(100, 'x');
+  bool write_success = false;
+
+  cache.WriteDATFile(
+      true, std::move(dat_data),
+      base::BindOnce([](bool* out, bool success) { *out = success; },
+                     &write_success));
+  task_environment_.RunUntilIdle();
```
Comment (netzenbot) [inline components/brave_shields/core/test/ad_block_dat_cache_manager_unittest.cc]: `task_environment_.RunUntilIdle()` is banned per [TA-005](https://github.com/brave/brave-core/tree/master/docs/best-practices/testing-async.md#TA-005) and presubmit flagged this. Since `WriteDATFile` takes a `base::OnceCallback<void(bool)>`, use `base::test::TestFuture<bool>` instead and call `future.Get()` to block until the callback fires.

File: components/brave_shields/core/browser/ad_block_filters_provider.h [hunk 37]
```diff
@@ -55,6 +56,8 @@ class AdBlockFiltersProvider {
   // ready at creation time.
```
Comment (netzenbot) [inline components/brave_shields/core/browser/ad_block_filters_provider.h:55]: Adding `GetCacheKey() const = 0` as a pure virtual to `AdBlockFiltersProvider` leaks the internal DAT cache mechanism into every provider's public interface — all subclasses must now implement a caching concept they may not care about. Per [ARCH-045](https://github.com/brave/brave-core/tree/master/docs/best-practices/architecture.md#ARCH-045), internal cache keys should not appear in public API interfaces. Consider having `AdBlockDATCacheManager` maintain its own mapping of provider identity to cache key (e.g., keyed by `GetNameForDebugging()` or a separate identity interface), rather than putting `GetCacheKey()` on the provider base class.

File: components/brave_shields/content/test/BUILD.gn [hunk 38]
```diff
@@ -21,6 +21,7 @@ source_set("test_support") {
     "//brave/components/brave_shields/content/browser",
     "//brave/components/brave_shields/core/browser",
```
Comment (netzenbot) [inline components/brave_shields/content/test/BUILD.gn:24]: nit: `//crypto` is unused in the `test_support` target — none of `test_filters_provider.cc/h` or `engine_test_observer.cc` include any crypto header. The new hashing uses `base/hash/hash.h` which comes from `//base`. ([BS-012](https://github.com/brave/brave-core/tree/master/docs/best-practices/build-system.md#BS-012))

File: components/brave_shields/content/test/DEPS [hunk 39]
```diff
@@ -1,9 +1,12 @@
 include_rules = [
+  "+brave/components/brave_shields/content/test",
   "+components/content_settings",
   "+components/prefs",
   "+components/sync_preferences/testing_pref_service_syncable.h",
   "+content/public/test",
+  "+crypto/sha2.h",
   "+services/network/public",
+  "+third_party/blink/public/mojom/loader/resource_load_info.mojom-shared.h",
```
Comment (netzenbot) [inline components/brave_shields/content/test/DEPS:8]: nit: `+crypto/sha2.h` is added to the DEPS allowlist but no file in this directory includes it. Looks like a leftover from an earlier version that used SHA-256 before switching to `base::FastHash`. ([BS-012](https://github.com/brave/brave-core/tree/master/docs/best-practices/build-system.md#BS-012))

File: components/brave_shields/core/test/DEPS [hunk 40]
```diff
@@ -3,6 +3,7 @@ include_rules = [
   "+components/prefs",
   "+components/sync_preferences/testing_pref_service_syncable.h",
   "+content/public/test",
+  "+crypto/sha2.h",
 ]
```
Comment (netzenbot) [inline components/brave_shields/core/test/DEPS:6]: nit: `+crypto/sha2.h` is added to the DEPS allowlist but no test file in this directory includes it. Appears to be a leftover from before the switch to `base::FastHash`. ([BS-012](https://github.com/brave/brave-core/tree/master/docs/best-practices/build-system.md#BS-012))

File: components/brave_shields/content/browser/ad_block_service.cc (hunk 12 above)
Comment (bridiver) [reply components/brave_shields/content/browser/ad_block_service.cc:340]: I think maybe you're saying it should be implemented in AdBlockEngine? If so, I don't think that makes sense here, the AdBlockEngine is responsible for evaluating the adblock rules, the service is responsible for parsing and loading them.

File: components/brave_shields/core/browser/ad_block_filters_provider.h (hunk 37 above)
Comment (bridiver) [reply components/brave_shields/core/browser/ad_block_filters_provider.h:55]: This is not relevant here and the rule should probably be removed

File: components/brave_shields/content/browser/ad_block_service.cc (hunk 12 above)
Comment (atuchin-m) [reply components/brave_shields/content/browser/ad_block_service.cc:340]: My point is `AdBlockService` doesn't look the right place to implement caching: we have to process both files and duplicate some code to dispatch. Also it non scalable: if we add extra engine we have to add a lot of code.

> If so, I don't think that makes sense here, the AdBlockEngine is responsible for evaluating the adblock rules,

`AdBlockEngine` doesn't look like a good place to me. But we have `AdBlockService::SourceProviderObserver` that's exactly in between `AblockService` and `AdBlockEngine`

File: components/brave_shields/content/browser/ad_block_service.cc [hunk 41]
```diff
@@ -213,6 +252,124 @@ AdBlockService::~AdBlockService() {
...
+void AdBlockService::OnResourcesLoaded(
+    bool is_default_engine,
+    std::optional<DATFileDataBuffer> dat,
+    std::unique_ptr<rust::Box<adblock::FilterSet>> filter_set,
+    AdblockResourceStorageBox storage) {
+  DCHECK_CALLED_ON_VALID_SEQUENCE(sequence_checker_);
+
+  if (dat.has_value()) {
+    if (dat_cache_manager_->allow_dat_loading()) {
+      task_runner_->PostTaskAndReplyWithResult(
```
Comment (atuchin-m) [inline components/brave_shields/content/browser/ad_block_service.cc]: AsyncCallAndReplyWithResult?

File: components/brave_shields/content/browser/ad_block_service.cc [hunk 42]
```diff
@@ -213,6 +252,124 @@ AdBlockService::~AdBlockService() {
...
+                                        std::move(filter_set),
+                                        std::move(storage))) {
+                return {};
+              }
+              return engine_wrapper->Serialize(is_default_engine);
+            },
+            base::Unretained(engine_wrapper_.get()), is_default_engine,
+            std::move(filter_set), std::move(storage)),
+        base::BindOnce(
+            [](base::WeakPtr<AdBlockService> service,
```
Comment (atuchin-m) [inline components/brave_shields/content/browser/ad_block_service.cc]: Should me move out these lambas? The methods looks over-complicated and hard to read.

File: components/brave_shields/core/browser/ad_block_dat_cache_manager.cc [hunk 43]
```diff
@@ -0,0 +1,152 @@
...
+    CHECK_IS_TEST();
+    return true;
+  }
+  std::string combined_key = ComputeCombinedCacheKey(is_default_engine);
+  std::string cached_key =
+      local_state_->GetString(CacheHashPrefName(is_default_engine));
+  return cached_key.empty() || cached_key != combined_key;
+}
+
+void AdBlockDATCacheManager::StoreCacheKey(bool is_default_engine) {
```
Comment (atuchin-m) [inline components/brave_shields/core/browser/ad_block_dat_cache_manager.cc]: We have to use `is_default_engine` in every method. It's usually a good indicator that it `AdBlockDATCacheManager` should be created on per-engine basis and use const `is_default_engine_` passed to the ctor.

File: components/brave_shields/content/browser/ad_block_service.cc (hunk 12 above)
Comment (bridiver) [reply components/brave_shields/content/browser/ad_block_service.cc:340]: I specifically moved it out of the provider because that necessarily left it split between the service and the provider. This doesn't seem like an issue that should block this PR in any case

File: components/brave_shields/content/browser/ad_block_service.cc (hunk 41 above)
Comment (bridiver) [reply components/brave_shields/content/browser/ad_block_service.cc]: it should use `AsyncCallAndReplyWithResult`, but it seems to defeat the purpose of having `AsyncCallAndReplyWithResult` if it's still possible to just call PostTaskAndReplyWithResult directly? Seems like we should guard against this?

File: components/brave_shields/content/browser/ad_block_service.cc (hunk 42 above)
Comment (bridiver) [reply components/brave_shields/content/browser/ad_block_service.cc]: yeah this nesting is definitely hard to read

File: components/brave_shields/core/browser/ad_block_dat_cache_manager.cc (hunk 43 above)
Comment (bridiver) [reply components/brave_shields/core/browser/ad_block_dat_cache_manager.cc]: it's already spread all over the place. This sounds like a follow-up issue?

File: components/brave_shields/content/browser/ad_block_service.cc (hunk 41 above)
Comment (bridiver) [reply components/brave_shields/content/browser/ad_block_service.cc]: actually it's not using AsyncCallAndReplyWithResult because it has to do several things on the task runner (load and serialize).

File: components/brave_shields/core/browser/ad_block_dat_cache_manager.cc [hunk 44]
```diff
@@ -0,0 +1,152 @@
...
+      base::BindOnce(
+          [](base::OnceCallback<void(std::optional<DATFileDataBuffer>,
+                                     std::optional<DATFileDataBuffer>)>
+                 callback,
+             std::pair<std::optional<DATFileDataBuffer>,
+                       std::optional<DATFileDataBuffer>> result) {
+            std::move(callback).Run(std::move(result.first),
+                                    std::move(result.second));
+          },
+          std::move(on_complete)));
```
Comment (atuchin-m) [inline components/brave_shields/core/browser/ad_block_dat_cache_manager.cc:95]: Can we just use `on_complete` directly, without extra `base::BindOnce`?

File: components/brave_shields/content/browser/ad_block_service.cc [hunk 45]
```diff
@@ -164,11 +189,19 @@ AdBlockService::AdBlockService(
...
+
   filter_list_catalog_provider_ =
       std::make_unique<AdBlockFilterListCatalogProvider>(
           component_update_service_);
 
   filters_provider_manager_ = std::make_unique<AdBlockFiltersProviderManager>();
+  dat_cache_manager_ = std::make_unique<AdBlockDATCacheManager>(
+      local_state_, filters_provider_manager_.get(), profile_dir_);
+
+  if (base::FeatureList::IsEnabled(features::kAdblockDATCache)) {
```
Comment (atuchin-m) [inline components/brave_shields/content/browser/ad_block_service.cc:203]: Better to check the feature inside `ReadCachedDATFiles`.

File: components/brave_shields/content/browser/ad_block_service.cc (hunk 41 above)
Comment (bridiver) [reply components/brave_shields/content/browser/ad_block_service.cc]: or maybe you were only talking about this one and not the one below? Fixing this one now

Comment (atuchin-m) [reply components/brave_shields/content/browser/ad_block_service.cc]: ok, we will replace it with `base::SequenceBound` after

File: components/brave_shields/content/browser/ad_block_service.cc (hunk 12 above)
Comment (bridiver) [reply components/brave_shields/content/browser/ad_block_service.cc:340]: to be clear I'm not saying this is the ideal place (it may or may not be), but I think it's the best place right now to avoid splitting the logic. Other refactoring would be required to put it in a different place.

File: components/brave_shields/core/browser/ad_block_dat_cache_manager.cc (hunk 44 above)
Comment (bridiver) [reply components/brave_shields/core/browser/ad_block_dat_cache_manager.cc:95]: We could, but it would require changing the method signature. Follow-up?

File: components/brave_shields/content/browser/ad_block_engine_wrapper.cc (hunk 18 above)
Comment (bridiver) [reply components/brave_shields/content/browser/ad_block_engine_wrapper.cc:146]: We can flag this for follow-up

File: components/brave_shields/content/browser/ad_block_service.cc (hunk 45 above)
Comment (bridiver) [reply components/brave_shields/content/browser/ad_block_service.cc:203]: As discussed I changed them all to guard externally for clarity when looking at AdBlockService and CHECK internally to make sure guards are correct.

File: components/brave_shields/content/browser/ad_block_custom_filters_provider.cc [hunk 46]
```diff
@@ -43,6 +46,7 @@ AdBlockCustomFiltersProvider::AdBlockCustomFiltersProvider(
     PrefService* local_state,
     AdBlockFiltersProviderManager* manager)
     : AdBlockFiltersProvider(false, manager), local_state_(local_state) {
+  cached_hash_ = base::NumberToString(base::FastHash(GetCustomFilters()));
```
Comment (atuchin-m) [inline components/brave_shields/content/browser/ad_block_custom_filters_provider.cc]: let's make `UpdateCachesHash()` method to avoid code duplication.
Or even make `UpdateCachesHashAndNotifyObservers()` (because we usually call  both methods)

File: components/brave_shields/content/browser/ad_block_service.cc [hunk 47]
```diff
@@ -193,18 +226,29 @@ AdBlockService::AdBlockService(
...
+      &AdBlockService::OnResourcesLoaded, base::Unretained(this));
+
+  const auto should_load_filter_state_callback = base::BindRepeating(
+      [](AdBlockDATCacheManager* cache, bool is_default_engine) {
+        if (!base::FeatureList::IsEnabled(features::kAdblockDATCache)) {
+          return true;
+        }
+        return cache->ShouldLoadFilterSet(is_default_engine);
+      },
+      base::Unretained(dat_cache_manager_.get()));
```
Comment (atuchin-m) [inline components/brave_shields/content/browser/ad_block_service.cc]: it's safe only if 1)`dat_cache_manager_` is defined before `*_service_observer_` and 2) the callback isn't passed somewhere. Both points are true now, but they are easy to break.

File: components/brave_shields/content/browser/ad_block_service.cc [hunk 48]
```diff
@@ -213,6 +257,119 @@ AdBlockService::~AdBlockService() {
...
 }
 
+void AdBlockService::OnResourcesLoaded(
+    bool is_default_engine,
+    std::optional<DATFileDataBuffer> dat,
+    std::unique_ptr<rust::Box<adblock::FilterSet>> filter_set,
+    AdblockResourceStorageBox storage) {
+  DCHECK_CALLED_ON_VALID_SEQUENCE(sequence_checker_);
+
+  if (dat.has_value()) {
```
Comment (atuchin-m) [inline components/brave_shields/content/browser/ad_block_service.cc:258]: It's not clear why `dat.has_value()` has a priority. If DAT file exists and match the content it's faster to load it anyway.

Comment (atuchin-m) [reply components/brave_shields/content/browser/ad_block_service.cc:258]: ah, it's another (cached) DAT. So it's okay.

File: components/brave_shields/content/browser/ad_block_service.cc (hunk 47 above)
Comment (bridiver) [reply components/brave_shields/content/browser/ad_block_service.cc]: I guess there's no reason why this can't use WeakPtr, but that's also true of many other things here. Maybe we should follow-up for all of them?

File: components/brave_shields/content/browser/ad_block_service.cc (hunk 48 above)
Comment (bridiver) [reply components/brave_shields/content/browser/ad_block_service.cc:258]: there's also a condition/test now to not write an empty dat

File: components/brave_shields/core/browser/ad_block_custom_resource_provider.cc [hunk 49]
```diff
@@ -189,6 +191,11 @@ void AdBlockCustomResourceProvider::LoadResources(
                      weak_ptr_factory_.GetWeakPtr(), std::move(on_load)));
 }
 
+void AdBlockCustomResourceProvider::OverrideResourcesForTesting(
```
Comment (netzenbot) [inline components/brave_shields/core/browser/ad_block_custom_resource_provider.cc:193]: `OverrideResourcesForTesting` is a test-only hook added to a production class — the presubmit flagged this at this line. Per [CSA-035](https://github.com/brave/brave-core/tree/master/docs/best-practices/coding-standards-apis.md#CSA-035), production code should not be modified solely to accommodate tests. Consider injecting a fake/stub `AdBlockCustomResourceProvider` in tests rather than adding this hook to the production class.

File: components/brave_shields/content/test/DEPS [hunk 50]
```diff
@@ -1,9 +1,11 @@
 include_rules = [
+  "+brave/components/brave_shields/content/test",
   "+components/content_settings",
   "+components/prefs",
   "+components/sync_preferences/testing_pref_service_syncable.h",
   "+content/public/test",
   "+services/network/public",
```
Comment (netzenbot) [inline components/brave_shields/content/test/DEPS:7]: nit: `+third_party/blink/public/mojom/loader/resource_load_info.mojom-shared.h` is only needed by `ad_block_service_unittest.cc`, so it should be in `specific_include_rules` rather than `include_rules`. The existing DEPS file already shows this pattern with `test_filters_provider.h`. ([BS-030](https://github.com/brave/brave-core/tree/master/docs/best-practices/build-system.md#BS-030))

File: components/brave_shields/content/browser/ad_block_service.h [hunk 51]
```diff
@@ -11,18 +11,25 @@
...
 #include "base/sequence_checker.h"
 #include "base/task/sequenced_task_runner.h"
+#include "base/time/time.h"
 #include "base/values.h"
 #include "brave/components/brave_shields/content/browser/ad_block_engine_wrapper.h"
 #include "brave/components/brave_shields/content/browser/ad_block_subscription_download_manager.h"
+#include "brave/components/brave_shields/core/browser/ad_block_dat_cache_manager.h"
 #include "brave/components/brave_shields/core/browser/ad_block_filters_provider.h"
 #include "brave/components/brave_shields/core/browser/ad_block_filters_provider_manager.h"
 #include "brave/components/brave_shields/core/browser/ad_block_list_p3a.h"
```
Comment (netzenbot) [inline components/brave_shields/content/browser/ad_block_service.h:32]: nit: `#include "base/time/time.h"` appears unused — none of the new declarations in this header use `base::Time`, `base::TimeDelta`, or `base::TimeTicks`. Looks like a leftover from an earlier version of this PR. Remove it. ([CS-001](https://github.com/brave/brave-core/tree/master/docs/best-practices/coding-standards.md#CS-001))

File: components/brave_shields/content/browser/ad_block_service.cc [hunk 52]
```diff
@@ -213,6 +257,119 @@ AdBlockService::~AdBlockService() {
...
+              if (!wrapper->Load(is_default, std::move(fs), std::move(s))) {
+                return {false, std::nullopt};
+              }
+              if (!cache) {
+                return {true, std::nullopt};
+              }
+              return {true, wrapper->Serialize(is_default)};
+            },
+            base::Unretained(engine_wrapper_.get()), is_default_engine,
+            should_cache, std::move(filter_set), std::move(storage)),
```
Comment (netzenbot) [inline components/brave_shields/content/browser/ad_block_service.cc:292]: nit: `OnResourcesLoaded`, `NotifyOnDATLoaded`, `OnEngineLoaded`, and `OnDATFileWritten` all manually iterate `observers_` with a range-for loop. Replace with `observers_.Notify(&Observer::OnResourcesLoaded, is_default_engine)` (and equivalents) to use the standard Chromium pattern. ([CS-056](https://github.com/brave/brave-core/tree/master/docs/best-practices/coding-standards.md#CS-056))

File: components/brave_shields/content/browser/ad_block_service.cc (hunk 12 above)
Comment (antonok-edm) [reply components/brave_shields/content/browser/ad_block_service.cc:340]: > Also it non scalable: if we add extra engine we have to add a lot of code.

fwiw, I am planning to only further consolidate the number of engines down to 1, not to increase them any further

**Review by antonok-edm — APPROVED** [review]

File: components/brave_shields/core/test/ad_block_dat_cache_manager_unittest.cc [hunk 53]
```diff
@@ -0,0 +1,176 @@
...
+
+class AdBlockDATCacheManagerTest : public testing::Test {
+ public:
+  AdBlockDATCacheManagerTest() {
+    feature_list_.InitAndEnableFeature(features::kAdblockDATCache);
+  }
+
+  void SetUp() override {
+    ASSERT_TRUE(profile_dir_.CreateUniqueTempDir());
+    prefs_.registry()->RegisterStringPref(prefs::kAdBlockDefaultCacheHash, "");
```
Comment (atuchin-m) [inline components/brave_shields/core/test/ad_block_dat_cache_manager_unittest.cc]: nit: this should be done in a static methods like `AdBlockDATCacheManager::RegisterPrefs(registry)`

File: components/brave_shields/core/test/ad_block_dat_cache_manager_unittest.cc [hunk 54]
```diff
@@ -0,0 +1,176 @@
...
+  EXPECT_EQ(prefs_.GetString(prefs::kAdBlockDefaultCacheHash), "");
+
+  cache.StoreCacheKey(true);
+
+  EXPECT_NE(prefs_.GetString(prefs::kAdBlockDefaultCacheHash), "");
+  EXPECT_EQ(prefs_.GetString(prefs::kAdBlockDefaultCacheHash),
+            cache.ComputeCombinedCacheKey(true));
+}
+
+TEST_F(AdBlockDATCacheManagerTest, ComputeCombinedCacheKeyExcludesNullopt) {
```
Comment (atuchin-m) [inline components/brave_shields/core/test/ad_block_dat_cache_manager_unittest.cc]: we need more test cases to check:
1. ComputeCombinedCacheKey is stable between launches;
2. ComputeCombinedCacheKey doesn't depend on the order of the providers.
3. Registering an extra providers changes `ComputeCombinedCacheKey`

File: components/brave_shields/core/test/ad_block_filters_provider_manager_unittest.cc [hunk 55]
```diff
@@ -33,3 +34,73 @@ TEST(AdBlockFiltersProviderManagerTest, WaitUntilInitialized) {
...
+  m.ForceNotifyObserver(default_observer, true);
+  EXPECT_EQ(default_observer.changed_count, 1);
+
+  // Observer for additional engine only
+  FiltersProviderManagerTestObserver additional_observer;
+  m.ForceNotifyObserver(additional_observer, false);
+  EXPECT_EQ(additional_observer.changed_count, 1);
+}
+
+TEST(AdBlockFiltersProviderManagerTest, OnChangedCombinesProviderHashes) {
```
Comment (atuchin-m) [inline components/brave_shields/core/test/ad_block_filters_provider_manager_unittest.cc]: it's not clear how the name OnChanged**CombinesProviderHashes** related to test body. We don't check the combined hash.

File: components/brave_shields/content/test/ad_block_custom_filters_provider_unittest.cc [hunk 56]
```diff
@@ -0,0 +1,70 @@
...
+  }
+
+ protected:
+  TestingPrefServiceSimple prefs_;
+};
+
+TEST_F(AdBlockCustomFiltersProviderTest, HashUpdatedOnFilterChange) {
+  brave_shields::AdBlockCustomFiltersProvider provider(&prefs_, nullptr);
+
+  // Initially hash should be the hash of empty string (not empty itself).
```
Comment (atuchin-m) [inline components/brave_shields/content/test/ad_block_custom_filters_provider_unittest.cc]: We need to verify it calc the initial hash correctly (not just for empty rules case)

File: components/brave_shields/content/browser/ad_block_subscription_filters_provider.cc [hunk 57]
```diff
@@ -88,10 +130,18 @@ void AdBlockSubscriptionFiltersProvider::OnDATFileDataReady(
...
 
 void AdBlockSubscriptionFiltersProvider::OnListAvailable() {
+  // Clear the persisted hash so the combined cache key changes, forcing
+  // ShouldLoadFilterSet to return true and trigger a reload. The new hash
+  // will be computed in OnDATFileDataReady when the file content is read.
+  if (local_state_) {
+    ScopedDictPrefUpdate update(local_state_,
+                                prefs::kAdBlockSubscriptionFiltersCacheHash);
+    update->Remove(GetPrefKey());
+  }
```
Comment (atuchin-m) [inline components/brave_shields/content/browser/ad_block_subscription_filters_provider.cc]: else { CHECK_IS_TEST(); }

File: components/brave_shields/content/browser/ad_block_subscription_filters_provider.cc [hunk 58]
```diff
@@ -88,10 +130,18 @@ void AdBlockSubscriptionFiltersProvider::OnDATFileDataReady(
...
 }
 
 void AdBlockSubscriptionFiltersProvider::OnListAvailable() {
+  // Clear the persisted hash so the combined cache key changes, forcing
+  // ShouldLoadFilterSet to return true and trigger a reload. The new hash
+  // will be computed in OnDATFileDataReady when the file content is read.
+  if (local_state_) {
+    ScopedDictPrefUpdate update(local_state_,
+                                prefs::kAdBlockSubscriptionFiltersCacheHash);
+    update->Remove(GetPrefKey());
```
Comment (atuchin-m) [inline components/brave_shields/content/browser/ad_block_subscription_filters_provider.cc]: Let's me ask it one more time:
here we drops the store prefs and call `NotifyObservers`. Why we do this if 
GetCacheKey() will return `std::nullopt`? 
It looks like we move the provided to a non-initialized state until we re-evaluate the hash.

Comment (atuchin-m) [reply components/brave_shields/content/browser/ad_block_subscription_filters_provider.cc]: Also, we always call `OnListAvailable` after ctor. So in fact it always throws away the cached value. How does it work?

File: components/brave_shields/content/browser/ad_block_subscription_filters_provider.cc [hunk 59]
```diff
@@ -69,13 +83,41 @@ std::string AdBlockSubscriptionFiltersProvider::GetNameForDebugging() {
   return "AdBlockSubscriptionFiltersProvider";
 }
 
+std::string AdBlockSubscriptionFiltersProvider::GetPrefKey() const {
+  return list_file_.BaseName().RemoveExtension().MaybeAsASCII();
```
Comment (atuchin-m) [inline components/brave_shields/content/browser/ad_block_subscription_filters_provider.cc]: It doesn't looks like a unique id.
AFAIK it converts `/home/user/path/list.txt` to just `list`.

File: components/brave_shields/content/browser/ad_block_service.cc [hunk 60]
```diff
@@ -213,6 +257,119 @@ AdBlockService::~AdBlockService() {
   ANNOTATE_LEAKING_OBJECT_PTR(engine_wrapper_.get());
 }
 
+void AdBlockService::OnResourcesLoaded(
```
Comment (atuchin-m) [inline components/brave_shields/content/browser/ad_block_service.cc:251]: What if OnResourcesLoaded is called again before we load the cached dat file? Do we skip it?

File: components/brave_shields/content/browser/ad_block_service.cc (hunk 47 above)
Comment (atuchin-m) [reply components/brave_shields/content/browser/ad_block_service.cc]: ok, let's believe such kinds of issues are easy to catch by ASAN (because there is always the same destruction order)

File: components/brave_shields/content/browser/ad_block_service.cc [hunk 61]
```diff
@@ -213,6 +257,119 @@ AdBlockService::~AdBlockService() {
...
+    for (auto& observer : observers_) {
+      observer.OnFilterListLoaded(is_default_engine, load_success);
+    }
+  }
+}
+
+void AdBlockService::OnDATFileWritten(bool is_default_engine, bool success) {
+  DCHECK_CALLED_ON_VALID_SEQUENCE(sequence_checker_);
+  if (success) {
+    dat_cache_manager_->StoreCacheKey(is_default_engine);
```
Comment (atuchin-m) [inline components/brave_shields/content/browser/ad_block_service.cc]: the current combined hash can be different (some components are updated).
We need write the hash matched to the DAT file we've just written or skip writing in that case.

File: components/brave_shields/content/browser/ad_block_engine_wrapper.cc [hunk 62]
```diff
@@ -106,20 +106,42 @@ adblock::BlockerResult AdBlockEngineWrapper::ShouldStartRequest(
...
+bool AdBlockEngineWrapper::Load(
     bool is_default_engine,
     std::unique_ptr<rust::Box<adblock::FilterSet>> filter_set,
     AdblockResourceStorageBox storage) {
   DCHECK_CALLED_ON_VALID_SEQUENCE(sequence_checker_);
   auto* engine = is_default_engine ? default_engine_.get()
                                    : additional_filters_engine_.get();
   if (filter_set) {
-    engine->Load(std::move(*filter_set), *storage);
+    return engine->Load(std::move(*filter_set), *storage);
```
Comment (atuchin-m) [inline components/brave_shields/content/browser/ad_block_engine_wrapper.cc:114]: In fact I see multiple `Load` calls even for the disabled feature that creates a significant CPU regression.
Image

Comment (atuchin-m) [reply components/brave_shields/content/browser/ad_block_engine_wrapper.cc:114]: I also don't see the calls eliminated after I enable the feature. We need to add a test for that case.

File: components/brave_shields/content/browser/ad_block_subscription_filters_provider.cc (hunk 59 above)
Comment (bridiver) [reply components/brave_shields/content/browser/ad_block_subscription_filters_provider.cc]: yeah that's definitely not right

File: components/brave_shields/content/browser/ad_block_engine_wrapper.cc (hunk 62 above)
Comment (bridiver) [reply components/brave_shields/content/browser/ad_block_engine_wrapper.cc:114]: Aren't there multiple load calls now? What does it look like without this change?

File: components/brave_shields/content/browser/ad_block_service.cc (hunk 61 above)
Comment (bridiver) [reply components/brave_shields/content/browser/ad_block_service.cc]: I think I might revert the DATCacheManager change and put it back in AdBlockService. It seems to have caused a bunch of regressions and assumes that only one load is happening at a time

File: components/brave_shields/content/browser/ad_block_engine_wrapper.cc (hunk 62 above)
Comment (atuchin-m) [reply components/brave_shields/content/browser/ad_block_engine_wrapper.cc:114]: I've shared the details in DM

File: components/brave_shields/content/browser/ad_block_service.cc (hunk 12 above)
Comment (atuchin-m) [reply components/brave_shields/content/browser/ad_block_service.cc:340]: ok, that thing isn't a dealbreaker. Let's leave it as is for now.

File: components/brave_shields/content/browser/ad_block_service.cc (hunk 61 above)
Comment (atuchin-m) [reply components/brave_shields/content/browser/ad_block_service.cc]: that's make sense, but I'm not following how it surely avoid such race conditions.
I also suppose we could have some similar issues with the current code, but at least it's stable.
The cached adds another layer of instability, so we need to be more carefull.

File: components/brave_shields/content/browser/ad_block_engine_wrapper.cc (hunk 62 above)
Comment (bridiver) [reply components/brave_shields/content/browser/ad_block_engine_wrapper.cc:114]: OnChanged wasn't waiting for all providers to be initialized. This should be fixed now

File: components/brave_shields/content/browser/ad_block_service.cc (hunk 60 above)
Comment (bridiver) [reply components/brave_shields/content/browser/ad_block_service.cc:251]: `dat_cache_manager_->allow_dat_loading()` will return false if the filter list loads before the cached dat so yes, it's skipped

File: components/brave_shields/content/browser/ad_block_service.cc [hunk 63]
```diff
@@ -87,20 +107,32 @@ void AdBlockService::SourceProviderObserver::OnFilterSetCallbackLoaded(
...
+  filter_set_ = std::move(filter_set);
+  LoadResources();
+}
+
 void AdBlockService::SourceProviderObserver::OnResourcesLoaded(
     AdblockResourceStorageBox storage) {
-  on_resources_loaded_.Run(engine_is_default_, std::move(filter_set_),
-                           std::move(storage));
+  on_resources_loaded_.Run(
+      engine_is_default_, std::exchange(cache_key_, std::string()),
```
Comment (atuchin-m) [inline components/brave_shields/content/browser/ad_block_service.cc]: `cache_key_` can be updated one more time after the first `OnChanged` call.
So we pass will the next key, not the right one. And for the second `OnResourcesLoaded` call we pass the empty key.

File: components/brave_shields/content/browser/ad_block_service.cc (hunk 60 above)
Comment (atuchin-m) [reply components/brave_shields/content/browser/ad_block_service.cc:251]: we call `set_allow_dat_loading(false)` only if the hash doesn't match.
I'm asking about the case when the resources (a dedicated component) is updated.
The hash isn't changed.

File: components/brave_shields/content/browser/ad_block_service.cc (hunk 63 above)
Comment (bridiver) [reply components/brave_shields/content/browser/ad_block_service.cc]: if these overlap then this entire thing is broken because that also affects filter_set_ and dat_

Comment (bridiver) [reply components/brave_shields/content/browser/ad_block_service.cc]: I'm not saying this isn't a problem, but it's a pre-existing problem with much larger issues than just cache_key_

File: components/brave_shields/content/test/DEPS (hunk 50 above)
Comment (bridiver) [reply components/brave_shields/content/test/DEPS:7]: You are misunderstanding the rule. Things that are fine to include for all classes in the directory should not be in specific_include_rules

File: components/brave_shields/content/browser/ad_block_service.cc (hunk 61 above)
Comment (bridiver) [reply components/brave_shields/content/browser/ad_block_service.cc]: I believe this should be fixed now by passing through the hash created when the files were updated, but let me know if I'm missing something here

File: components/brave_shields/content/browser/ad_block_service.cc (hunk 60 above)
Comment (bridiver) [reply components/brave_shields/content/browser/ad_block_service.cc:251]: I haven't verified this myself yet so I don't know if it's accurate, but "The race atuchin-m described is benign. The resource-only path
  (dat=nullopt) never enters the dat.has_value() branch, so
  allow_dat_loading is irrelevant for it. And the resource observer
   can't fire before the first load path starts, because it isn't
  registered yet."
Not sure if this is the same issue we discussed in DM and (I think) decided is not a concern?

File: components/brave_shields/core/browser/ad_block_dat_cache_manager.h [hunk 64]
```diff
@@ -0,0 +1,68 @@
...
+ public:
+  static void RegisterPrefs(PrefRegistrySimple* registry);
+
+  AdBlockDATCacheManager(PrefService* local_state,
+                         const base::FilePath& profile_dir);
+  ~AdBlockDATCacheManager();
+  AdBlockDATCacheManager(const AdBlockDATCacheManager&) = delete;
+  AdBlockDATCacheManager& operator=(const AdBlockDATCacheManager&) = delete;
+
+  // Returns true if a cached DAT was written in a previous session.
```
Comment (atuchin-m) [inline components/brave_shields/core/browser/ad_block_dat_cache_manager.h]: > if a cached DAT was written

If it's for a single file, we need to take into account `is_default_engine`.
if it's for the both, let's update the comment and name to clarify that.

File: components/brave_shields/content/browser/ad_block_subscription_filters_provider.h [hunk 65]
```diff
@@ -56,7 +53,6 @@ class AdBlockSubscriptionFiltersProvider : public AdBlockFiltersProvider {
 
   std::string GetNameForDebugging() override;
 
- private:
```
Comment (atuchin-m) [inline components/brave_shields/content/browser/ad_block_subscription_filters_provider.h:59]: is it intentional change? Making the fields public doesn't look right.

File: components/brave_shields/core/test/ad_block_component_filters_provider_unittest.cc [hunk 66]
```diff
@@ -0,0 +1,45 @@
...
+#include "brave/components/brave_shields/core/browser/ad_block_component_filters_provider.h"
+
+#include "base/files/scoped_temp_dir.h"
+#include "base/test/task_environment.h"
+#include "brave/components/brave_shields/core/browser/ad_block_filters_provider.h"
+#include "testing/gtest/include/gtest/gtest.h"
+
+namespace {
+
+class HashObserver : public brave_shields::AdBlockFiltersProvider::Observer {
```
Comment (atuchin-m) [inline components/brave_shields/core/test/ad_block_component_filters_provider_unittest.cc]: Unused?

File: components/brave_shields/core/test/ad_block_dat_cache_manager_unittest.cc
Comment (atuchin-m) [inline components/brave_shields/core/test/ad_block_dat_cache_manager_unittest.cc:1]: is it a stale file?

File: components/brave_shields/content/browser/ad_block_service.cc [hunk 67]
```diff
@@ -213,6 +251,132 @@ AdBlockService::~AdBlockService() {
...
+    bool is_default_engine,
+    std::pair<FilterListLoadResult, std::optional<DATFileDataBuffer>> result) {
+  DCHECK_CALLED_ON_VALID_SEQUENCE(sequence_checker_);
+  auto [load_result, serialized_dat] = std::move(result);
+
+  if (load_result != FilterListLoadResult::kResourcesOnly) {
+    if (is_default_engine) {
+      default_filter_list_loaded_ = true;
+    } else {
+      additional_filter_list_loaded_ = true;
```
Comment (atuchin-m) [inline components/brave_shields/content/browser/ad_block_service.cc]: do we use it only for testing? If so, can we just use `Observer::OnFilterListLoaded` ?
Or at least rename it to `additional_filter_list_loaded_for_testing_`

File: components/brave_shields/content/browser/ad_block_service.cc [hunk 68]
```diff
@@ -213,6 +251,132 @@ AdBlockService::~AdBlockService() {
...
+            should_cache, std::move(filter_set), std::move(storage)),
+        base::BindOnce(&AdBlockService::OnEngineLoaded,
+                       weak_factory_.GetWeakPtr(), is_default_engine));
+  }
+}
+
+void AdBlockService::NotifyOnDATLoaded(bool is_default_engine, bool success) {
+  DCHECK_CALLED_ON_VALID_SEQUENCE(sequence_checker_);
+  if (is_default_engine) {
+    default_dat_loaded_ = true;
```
Comment (atuchin-m) [inline components/brave_shields/content/browser/ad_block_service.cc]: the same question about replacing `default_dat_loaded_` to using `Observer::OnDATLoaded`

File: components/brave_shields/core/test/ad_block_filters_provider_manager_unittest.cc [hunk 69]
```diff
@@ -33,3 +34,88 @@ TEST(AdBlockFiltersProviderManagerTest, WaitUntilInitialized) {
   provider2.RegisterAsSourceProvider(&m);
   EXPECT_EQ(test_observer.changed_count, 2);
 }
+
+TEST(AdBlockFiltersProviderManagerTest, ForceNotifyObserverCombinesHashes) {
```
Comment (atuchin-m) [inline components/brave_shields/core/test/ad_block_filters_provider_manager_unittest.cc]: we don't have hashes anymore.

File: components/brave_shields/content/browser/ad_block_service.cc [hunk 70]
```diff
@@ -213,6 +251,132 @@ AdBlockService::~AdBlockService() {
...
+    dat_cache_manager_->WriteDATFile(
+        is_default_engine, std::move(*serialized_dat),
+        base::BindOnce(&AdBlockService::OnDATFileWritten,
+                       weak_factory_.GetWeakPtr(), is_default_engine));
+  }
+}
+
+void AdBlockService::OnDATFileWritten(bool is_default_engine, bool success) {
+  DCHECK_CALLED_ON_VALID_SEQUENCE(sequence_checker_);
+  observers_.Notify(&Observer::OnDATWritten, is_default_engine);
```
Comment (atuchin-m) [inline components/brave_shields/content/browser/ad_block_service.cc]: Do we use it somewhere?

File: components/brave_shields/content/browser/ad_block_service.h [hunk 71]
```diff
@@ -57,49 +61,77 @@ class AdBlockSubscriptionServiceManager;
...
+    kResourcesOnly,
+  };
+
+  class Observer : public base::CheckedObserver {
+   public:
+    Observer() = default;
+    ~Observer() override = default;
+    virtual void OnFilterListLoaded(bool is_default_engine,
+                                    FilterListLoadResult result) {}
+    virtual void OnDATLoaded(bool is_default_engine, bool success) {}
```
Comment (atuchin-m) [inline components/brave_shields/content/browser/ad_block_service.h:76]: Some of the methods here look unused.

File: components/brave_shields/core/browser/ad_block_dat_cache_manager.cc [hunk 72]
```diff
@@ -0,0 +1,155 @@
...
+
+bool AdBlockDATCacheManager::HasCachedDAT(bool is_default_engine) const {
+  if (!base::FeatureList::IsEnabled(features::kAdblockDATCache)) {
+    return false;
+  }
+  if (!local_state_) {
+    CHECK_IS_TEST();
+    return false;
+  }
+  return !local_state_->GetString(TimestampPrefName(is_default_engine)).empty();
```
Comment (atuchin-m) [inline components/brave_shields/core/browser/ad_block_dat_cache_manager.cc]: It's not clear why we use timestamps if they act like bool..

File: components/brave_shields/content/browser/ad_block_service.cc [hunk 73]
```diff
@@ -213,6 +251,132 @@ AdBlockService::~AdBlockService() {
...
+  if (load_result != FilterListLoadResult::kResourcesOnly) {
+    if (is_default_engine) {
+      default_filter_list_loaded_ = true;
+    } else {
+      additional_filter_list_loaded_ = true;
+    }
+    observers_.Notify(&Observer::OnFilterListLoaded, is_default_engine,
+                      load_result);
+  }
+  observers_.Notify(&Observer::OnResourcesLoaded, is_default_engine);
```
Comment (atuchin-m) [inline components/brave_shields/content/browser/ad_block_service.cc]: What if it's `kFailed`? When we're going to build a ruleset in that case?

File: components/brave_shields/content/browser/ad_block_service.h [hunk 74]
```diff
@@ -57,49 +61,77 @@ class AdBlockSubscriptionServiceManager;
 // The brave shields service in charge of ad-block checking and init.
 class AdBlockService {
  public:
+  enum class FilterListLoadResult {
+    kLoaded,
+    kFailed,
+    kResourcesOnly,
```
Comment (atuchin-m) [inline components/brave_shields/content/browser/ad_block_service.h:67]: if it's possible to split the methods to build/load ruleset from loading the resources (instead of making a combined `FilterListLoadResult`), it would be nice.

File: components/brave_shields/content/browser/ad_block_service.h [hunk 75]
```diff
@@ -225,6 +278,11 @@ class AdBlockService {
   std::unique_ptr<SourceProviderObserver> additional_filters_service_observer_
       GUARDED_BY_CONTEXT(sequence_checker_);
 
+  base::ObserverList<Observer> observers_;
```
Comment (atuchin-m) [inline components/brave_shields/content/browser/ad_block_service.h:278]: `GUARDED_BY_CONTEXT(sequence_checker_)`?

File: components/brave_shields/content/browser/ad_block_service.h [hunk 76]
```diff
@@ -225,6 +278,11 @@ class AdBlockService {
...
+
+  bool default_dat_loaded_ = false;
```
Comment (atuchin-m) [inline components/brave_shields/content/browser/ad_block_service.h]: better to remove this in favor of Observer. If we can't, let's add `GUARDED_BY_CONTEXT(sequence_checker_) `.

File: components/brave_shields/core/browser/ad_block_component_service_manager.cc [hunk 77]
```diff
@@ -187,6 +255,11 @@ void AdBlockComponentServiceManager::StartRegionalServices() {
       }
     }
   }
+
+  // Mark the gate providers as initialized now that all component providers
+  // have been registered. This unblocks filter set loading.
+  default_gate_->SetInitialized();
```
Comment (atuchin-m) [inline components/brave_shields/core/browser/ad_block_component_service_manager.cc]: Can we skip this because of the `return` operator above (`filter_list_catalog_.size() == 0`)?

File: components/brave_shields/core/browser/ad_block_component_service_manager.cc [hunk 78]
```diff
@@ -187,6 +255,11 @@ void AdBlockComponentServiceManager::StartRegionalServices() {
...
+  additional_gate_->SetInitialized();
```
Comment (atuchin-m) [inline components/brave_shields/core/browser/ad_block_component_service_manager.cc]: Do we sure that the rest providers are registered here?
At least `AdBlockSubscriptionFiltersProvider` is registered in async manner via `LoadSubscriptionServices`.

File: components/brave_shields/content/browser/ad_block_subscription_filters_provider.h (hunk 65 above)
Comment (bridiver) [reply components/brave_shields/content/browser/ad_block_subscription_filters_provider.h:59]: There were two private declarations. These are already in private

File: components/brave_shields/core/browser/ad_block_component_service_manager.cc (hunk 77 above)
Comment (bridiver) [reply components/brave_shields/core/browser/ad_block_component_service_manager.cc]: yes, and there should be a test for that

Comment (bridiver) [reply components/brave_shields/core/browser/ad_block_component_service_manager.cc]: I think just putting it at the beginning should work fine since nothing else can happen between initializing these and adding the providers

File: components/brave_shields/core/browser/ad_block_component_service_manager.cc (hunk 78 above)
Comment (bridiver) [reply components/brave_shields/core/browser/ad_block_component_service_manager.cc]: as discussed in DM I don't see that there are any other providers that are registered async. The callbacks all appear to be sync (no PostTask)

File: components/brave_shields/content/browser/ad_block_service.cc (hunk 60 above)
Comment (bridiver) [reply components/brave_shields/content/browser/ad_block_service.cc:251]: Can this be resolved?

File: components/brave_shields/content/browser/ad_block_service.cc (hunk 68 above)
Comment (bridiver) [reply components/brave_shields/content/browser/ad_block_service.cc]: there is no way to register the observer early enough in browser tests to guarantee that you receive the event. This is a hacky workaround for sure and I'm open to suggestions.

File: components/brave_shields/content/browser/ad_block_service.cc (hunk 67 above)
Comment (bridiver) [reply components/brave_shields/content/browser/ad_block_service.cc]: > additional_filter_list_loaded_for_testing_

yes, I was already thinking about making that change

File: components/brave_shields/content/browser/ad_block_service.h (hunk 74 above)
Comment (bridiver) [reply components/brave_shields/content/browser/ad_block_service.h:67]: that sounds like a refactor outside of the scope of this PR?

File: components/brave_shields/content/browser/ad_block_service.h (hunk 75 above)
Comment (bridiver) [reply components/brave_shields/content/browser/ad_block_service.h:278]: I don't know if this stuff is needed anymore since AdBlockService is no longer called on more than one thread?

File: components/brave_shields/content/browser/ad_block_service.h (hunk 76 above)
Comment (bridiver) [reply components/brave_shields/content/browser/ad_block_service.h]: per above response it's not possible to use the observer in browser tests due to a race between the dat loading and registering the observer

**Comment by bridiver** [comment]
> 1. **Stale cache problem**: No cache invalidation mechanism exists. If filter lists are updated between runs, the cached DAT files will contain outdated rules until a provider change triggers a rebuild. There's no version/hash check comparing cached DATs against current filter list versions.

This is intentional. This is a best effort process and in edge cases we just wait for the next component update to clear it

**Comment by bridiver** [comment]
> ### Possible Issues
> 1. **Stale cache problem**: No cache invalidation mechanism exists. If filter lists are updated between runs, the cached DAT files will contain outdated rules until a provider change triggers a rebuild. There's no version/hash check comparing cached DATs against current filter list versions.

This is intentional. This is a best effort process and in edge cases we just wait for the next component update to clear it

> 2. **`suppress_*_startup_change_notification_` consumed prematurely in `ForceNotifyObserver`**: When DAT load fails and `ForceNotifyObserver` is called, the suppression flag is consumed (set to false) and the method returns early _without_ actually notifying. If providers aren't initialized yet at that point, the notification is silently dropped. The subsequent `OnChanged` from provider initialization will work, but the suppression flag consumption in `ForceNotifyObserver` when `!AreAllProvidersInitialized` means the real `OnChanged` won't be suppressed—which is correct for the fallback case but makes the control flow fragile and hard to reason about.

This is also intentional, if we didn't do this the filter list would never load when the dat load fails

> 3. **`base::Unretained(engine_wrapper_.get())` in `OnResourcesLoaded`**: `engine_wrapper_` is moved to task runner but destroyed in `AdBlockService` destructor with `ANNOTATE_LEAKING_OBJECT_PTR`. If `AdBlockService` is destroyed while tasks are in flight, the `Unretained` pointer could dangle. The existing code had the same pattern, but adding more posted tasks increases the risk window.

This is wrong. No tasks can be posted to the wrapper after the destruction of the AdBlockService on the task runner

> 4. **`AdBlockSubscriptionFiltersProvider::list_file_` moved from private to public** — breaks encapsulation without clear justification in this diff.

This is wrong, there were two private declarations

> 6. **Race between `MaybeReadCachedDATFiles` and `SourceProviderObserver` construction**: Both are initiated in the constructor. If the read completes before observers are wired, `OnReadCachedDATFiles` could call methods on observers that haven't finished setup. In practice, the thread pool hop likely prevents this, but it's not guaranteed.

This is wrong, MaybeReadCachedDATFiles and SourceProviderObserver construction both happen in the same method, there is no way for the response to MaybeReadCachedDATFiles happen before the observers are created

File: components/brave_shields/core/browser/ad_block_component_service_manager.cc [hunk 79]
```diff
@@ -141,6 +197,20 @@ void AdBlockComponentServiceManager::OnAdBlockOnlyModePrefChanged() {
...
   DCHECK_CALLED_ON_VALID_SEQUENCE(sequence_checker_);
+
+  // Mark the gate providers as initialized now that all component providers
+  // have been registered. This unblocks filter set loading.
+  // This happens first so it applies even for early returns below and it's
+  // ok because nothing else can check the intialized state until after this
+  // method completes. The gates are only created when the DAT cache feature
+  // is enabled, so they may be null here.
+  if (default_gate_) {
+    default_gate_->SetInitialized();
```
Comment (atuchin-m) [inline components/brave_shields/core/browser/ad_block_component_service_manager.cc]: I'm not following why we set this before adding the rest providers.
What if all of the current providers are ready?

File: components/brave_shields/core/browser/ad_block_custom_resource_provider.cc [hunk 80]
```diff
@@ -189,6 +190,11 @@ void AdBlockCustomResourceProvider::LoadResources(
...
+    AdblockResourceStorageBox storage) {
+  cached_storage_ = adblock::new_empty_resource_storage();
```
Comment (atuchin-m) [inline components/brave_shields/core/browser/ad_block_custom_resource_provider.cc:195]: we should use `storage` here or rename method to `SetEmptyResourcesForTesting()`

File: components/brave_shields/content/browser/ad_block_service.cc [hunk 81]
```diff
@@ -213,6 +248,130 @@ AdBlockService::~AdBlockService() {
...
+      default_filter_list_loaded_for_testing_ = true;
+    } else {
+      additional_filter_list_loaded_for_testing_ = true;
+    }
+    observers_.Notify(&Observer::OnFilterListLoaded, is_default_engine,
+                      load_result);
+  }
+
+  if (serialized_dat.has_value() && !serialized_dat->empty()) {
+    dat_cache_manager_->WriteDATFile(is_default_engine,
```
Comment (atuchin-m) [inline components/brave_shields/content/browser/ad_block_service.cc:335]: Does it make sense to write the dat file in-place when we call `wrapper->Serialize()` instead of doing extra thread hopes?
Or vice-versa: call serialize here to get `DATFileDataBuffer`.

File: components/brave_shields/content/browser/ad_block_service.cc [hunk 82]
```diff
@@ -213,6 +248,130 @@ AdBlockService::~AdBlockService() {
...
+  DCHECK_CALLED_ON_VALID_SEQUENCE(sequence_checker_);
+  // Load cached DATs unconditionally for immediate ad-blocking protection.
+  // If a DAT file is missing or fails to load, NotifyOnDATLoaded will
+  // fall back to loading from filter lists via ForceNotifyObserver.
+  if (default_dat) {
+    default_service_observer_->OnDATFileRead(std::move(*default_dat));
+  } else {
+    NotifyOnDATLoaded(true, false);
+    // Trigger filter list loading
+    filters_provider_manager_->ForceNotifyObserver(*default_service_observer_,
```
Comment (atuchin-m) [inline components/brave_shields/content/browser/ad_block_service.cc]: in `NotifyOnDATLoaded` with `success = false` we also call ForceNotifyObserver. Is it intentional?

File: components/brave_shields/core/browser/ad_block_filters_provider_manager.cc [hunk 83]
```diff
@@ -42,23 +52,86 @@ void AdBlockFiltersProviderManager::RemoveProvider(
...
 
+void AdBlockFiltersProviderManager::MaybeNotifyObserver(
+    AdBlockFiltersProvider::Observer& observer,
+    bool is_for_default_engine) {
+  if (AreAllProvidersInitialized(is_for_default_engine)) {
+    observer.OnChanged(is_for_default_engine);
+  }
+}
+
+void AdBlockFiltersProviderManager::ForceNotifyObserver(
```
Comment (atuchin-m) [inline components/brave_shields/core/browser/ad_block_filters_provider_manager.cc:67]: What exactly `Force` means here?
Comparing the implementations `ForceNotifyObserver` uses less force then `MaybeNotifyObserver` 😄

File: components/brave_shields/content/browser/ad_block_service.cc (hunk 68 above)
Comment (bridiver) [reply components/brave_shields/content/browser/ad_block_service.cc]: so actually it may now be possible to load the observers early enough since I added AdBlockBrowserTestHelper to ensure that we control creation of the adblock service. Going to take a look

File: components/brave_shields/content/browser/ad_block_service.h (hunk 75 above)
Comment (atuchin-m) [reply components/brave_shields/content/browser/ad_block_service.h:278]: it's up to you.

File: browser/brave_browser_process_impl.cc [hunk 84]
```diff
@@ -316,6 +316,7 @@ void BraveBrowserProcessImpl::StartBraveServices() {
 
 brave_shields::AdBlockService* BraveBrowserProcessImpl::ad_block_service() {
   if (!ad_block_service_) {
+    LOG(ERROR) << base::debug::StackTrace().ToString();
```
Comment (netzenbot) [inline browser/brave_browser_process_impl.cc]: `LOG(ERROR) << base::debug::StackTrace().ToString();` is debug code that was not removed before submission. It fires every time `ad_block_service()` is called, which will spam ERROR logs in production builds and incur the cost of capturing a stack trace on each call. This should be removed.

File: browser/brave_browser_process_impl.cc [hunk 85]
```diff
@@ -316,6 +316,7 @@ void BraveBrowserProcessImpl::StartBraveServices() {
 
 brave_shields::AdBlockService* BraveBrowserProcessImpl::ad_block_service() {
```
Comment (netzenbot) [inline browser/brave_browser_process_impl.cc:317]: `LOG(ERROR) << base::debug::StackTrace().ToString()` looks like debug instrumentation that was accidentally left in. This will fire every time `ad_block_service()` is called for the first time, polluting error logs in production builds.

File: browser/brave_browser_process_impl.cc [hunk 86]
```diff
@@ -316,6 +316,7 @@ void BraveBrowserProcessImpl::StartBraveServices() {
...
   if (!ad_block_service_) {
+    LOG(ERROR) << base::debug::StackTrace().ToString();
     scoped_refptr<base::SequencedTaskRunner> task_runner(
```
Comment (netzenbot) [inline browser/brave_browser_process_impl.cc:319]: `LOG(ERROR) << base::debug::StackTrace().ToString()` looks like leftover debug instrumentation — a stack trace dump on every ad_block_service accessor call is not appropriate for production. Remove this line entirely, or if it needs to be kept temporarily, use `VLOG(1)` scoped to debug builds only. ([CS-044](https://github.com/brave/brave-core/tree/master/docs/best-practices/coding-standards.md#CS-044))

File: browser/brave_browser_process_impl.cc (hunk 84 above)
Comment (bridiver) [reply browser/brave_browser_process_impl.cc]: Oops, accidentally left this in

File: components/brave_shields/core/browser/ad_block_filters_provider_manager.cc (hunk 83 above)
Comment (bridiver) [reply components/brave_shields/core/browser/ad_block_filters_provider_manager.cc:67]: `MaybeConsumeEngineStartupChangeNotification` is the critical difference. Without that the startup notification will be suppressed when it is called here https://github.com/brave/brave-core/pull/35069/changes#diff-2042ea0a21200f1079c1086ecec47b067752a835bb96878b7cb13b98c76041c6R98
but something doesn't seem right about this because it shouldn't consume the notification and then return, it should consume it and then call AreAllProvidersInitialized/OnChanged
I need to check on tests because I thought there was a test for this, but all tests are green and this doesn't seem right

File: components/brave_shields/content/browser/ad_block_service.cc (hunk 82 above)
Comment (bridiver) [reply components/brave_shields/content/browser/ad_block_service.cc]: I think that was an AI change I missed.

File: components/brave_shields/content/browser/ad_block_service.cc (hunk 81 above)
Comment (bridiver) [reply components/brave_shields/content/browser/ad_block_service.cc:335]: it writes on a thread pool anyway so I don't think it matters. This keeps the dat_cache_manager on UI thread only

File: components/brave_shields/core/browser/ad_block_component_service_manager.cc (hunk 79 above)
Comment (bridiver) [reply components/brave_shields/core/browser/ad_block_component_service_manager.cc]: All the current providers are always ready because the default implementation is to return true. The purpose of this is to ensure that AreAllProvidersInitialized doesn't return true until the component providers are added

Comment (bridiver) [reply components/brave_shields/core/browser/ad_block_component_service_manager.cc]: Oh wait, the ordering? It is explained in the comment above. We do this first because otherwise it would get missed when `filter_list_catalog_.size() == 0` and block forever. The ordering inside the method makes no difference because nothing can happen until the method returns.

File: components/brave_shields/core/browser/ad_block_filters_provider_manager.cc (hunk 83 above)
Comment (bridiver) [reply components/brave_shields/core/browser/ad_block_filters_provider_manager.cc:67]: actually I added some tests and was confused at first, but it doesn't make any difference whether you return or not because it only matters when the startup notification has not already been consumed and therefore we're still waiting for one of the startup providers to complete

Comment (atuchin-m) [reply components/brave_shields/core/browser/ad_block_filters_provider_manager.cc:67]: At least naming is confusing. In fact the internals here is the same as for MaybeNotifyObserver plus extra `MaybeConsumeEngineStartupChangeNotification` checking.

File: components/brave_shields/core/browser/ad_block_filters_provider_manager.cc [hunk 87]
```diff
@@ -11,15 +11,25 @@
...
 #include "base/task/sequenced_task_runner.h"
 #include "base/trace_event/trace_event.h"
+#include "brave/components/brave_shields/core/browser/ad_block_filters_provider.h"
+#include "brave/components/brave_shields/core/common/features.h"
 
 namespace brave_shields {
 
-AdBlockFiltersProviderManager::AdBlockFiltersProviderManager() = default;
+AdBlockFiltersProviderManager::AdBlockFiltersProviderManager() {
+  suppress_default_engine_startup_change_notification_ =
```
Comment (atuchin-m) [inline components/brave_shields/core/browser/ad_block_filters_provider_manager.cc:28]: do we change `suppress_default_engine_startup_change_notification_` somewhere?
if not, let's just use `base::FeatureList::IsEnabled(features::kAdblockDATCache)` directly.

File: components/brave_shields/core/browser/ad_block_component_service_manager.cc (hunk 79 above)
Comment (atuchin-m) [reply components/brave_shields/core/browser/ad_block_component_service_manager.cc]: >  because nothing can happen until the method returns.

If it's true, then it's okay.
But `SetInitialized` calls `NotifyObservers` internally. I suppose it can trigger the ruleset building if all the current  providers are ready.

Comment (bridiver) [reply components/brave_shields/core/browser/ad_block_component_service_manager.cc]: oic, the gate providers call NotifyObservers, but then I wonder why tests aren't failing. Need to look into this

Comment (bridiver) [reply components/brave_shields/core/browser/ad_block_component_service_manager.cc]: https://github.com/brave/brave-core/pull/35069/changes/afd0210023c69f251981ee39ed9e6e3c931a7237

File: components/brave_shields/core/browser/ad_block_filters_provider_manager.cc (hunk 83 above)
Comment (bridiver) [reply components/brave_shields/core/browser/ad_block_filters_provider_manager.cc:67]: Right, but the `MaybeConsumeEngineStartupChangeNotification` is what makes it `Force` because that notification might not happen in `MaybeNotifyObserver` if it's startup. I could make it `ForceStartupNotifyObserver` but not sure if that's better or even more confusing

File: components/brave_shields/core/browser/ad_block_filters_provider_manager.cc (hunk 87 above)
Comment (bridiver) [reply components/brave_shields/core/browser/ad_block_filters_provider_manager.cc:28]: we have to handle default and additional engine separately

File: components/brave_shields/core/browser/ad_block_component_service_manager.cc (hunk 79 above)
Comment (bridiver) [reply components/brave_shields/core/browser/ad_block_component_service_manager.cc]: changed to absl::Cleanup

**Review by cdesouza-chromium — APPROVED** [review]
LGTM

File: components/brave_shields/core/browser/ad_block_custom_resource_provider.cc (hunk 80 above)
Comment (bridiver) [reply components/brave_shields/core/browser/ad_block_custom_resource_provider.cc]: oops, I'll fix

File: components/brave_shields/core/browser/ad_block_dat_cache_manager.h [hunk 88]
```diff
@@ -0,0 +1,52 @@
...
+  // Reads cached DAT files from disk. Calls |on_complete| with the results.
+  void MaybeReadCachedDATFiles(
+      base::OnceCallback<void(std::optional<DATFileDataBuffer>,
+                              std::optional<DATFileDataBuffer>)> on_complete);
+
+ private:
+  base::FilePath cache_dir_;
+  scoped_refptr<base::SequencedTaskRunner> task_runner_;
+
+  base::WeakPtrFactory<AdBlockDATCacheManager> weak_factory_{this};
```
Comment (atuchin-m) [inline components/brave_shields/core/browser/ad_block_dat_cache_manager.h]: nit: unused?

File: components/brave_shields/content/browser/ad_block_service.cc [hunk 89]
```diff
@@ -87,22 +91,47 @@ void AdBlockService::SourceProviderObserver::OnFilterSetCallbackLoaded(
           weak_factory_.GetWeakPtr()));
 }
 
-void AdBlockService::SourceProviderObserver::OnFilterSetCreated(
+void AdBlockService::SourceProviderObserver::LoadResources(
+    std::optional<DATFileDataBuffer> dat,
```
Comment (atuchin-m) [inline components/brave_shields/content/browser/ad_block_service.cc]: Looks like `dat` is always `std::nullopt` for both `LoadResources()` calls here.
Should we eliminate it? The same for `OnAllLoaded`

File: components/brave_shields/content/test/DEPS [hunk 90]
```diff
@@ -1,9 +1,11 @@
 include_rules = [
+  "+brave/components/brave_shields/content/test",
```
Comment (atuchin-m) [inline components/brave_shields/content/test/DEPS]: Is it necessary?
It points to the current location.

File: components/brave_shields/core/browser/ad_block_dat_cache_manager.h [hunk 91]
```diff
@@ -0,0 +1,52 @@
...
+  // Calls |on_complete| with success/failure.
+  void WriteDATFile(bool is_default_engine, DATFileDataBuffer dat);
+
+  // Reads cached DAT files from disk. Calls |on_complete| with the results.
+  void MaybeReadCachedDATFiles(
+      base::OnceCallback<void(std::optional<DATFileDataBuffer>,
+                              std::optional<DATFileDataBuffer>)> on_complete);
+
+ private:
+  base::FilePath cache_dir_;
```
Comment (atuchin-m) [inline components/brave_shields/core/browser/ad_block_dat_cache_manager.h:40]: nit: add `const` for cache_dir_ and task_runner_

File: components/brave_shields/core/browser/ad_block_dat_cache_manager.cc [hunk 92]
```diff
@@ -0,0 +1,98 @@
...
+
+namespace {
+
+constexpr char kAdblockCacheDir[] = "adblock_cache";
+constexpr char kAdBlockEngine0DATCache[] = "engine0.dat";
+constexpr char kAdBlockEngine1DATCache[] = "engine1.dat";
+
+std::pair<std::optional<DATFileDataBuffer>, std::optional<DATFileDataBuffer>>
+ReadCachedDATFilesFromDisk(base::FilePath cache_dir) {
+  if (!base::CreateDirectory(cache_dir)) {
```
Comment (atuchin-m) [inline components/brave_shields/core/browser/ad_block_dat_cache_manager.cc]: nit: do we need this?

File: components/brave_shields/core/browser/ad_block_filters_provider_manager.cc [hunk 93]
```diff
@@ -42,23 +52,88 @@ void AdBlockFiltersProviderManager::RemoveProvider(
...
+}
+
 void AdBlockFiltersProviderManager::OnChanged(bool is_for_default_engine) {
+  if (!AreAllProvidersInitialized(is_for_default_engine)) {
+    return;
+  }
+
+  // All startup providers are initialized so we can safely consume the startup
+  // notification. The next call to OnChanged will trigger NotifyObservers
+  if (MaybeConsumeEngineStartupChangeNotification(is_for_default_engine)) {
```
Comment (atuchin-m) [inline components/brave_shields/core/browser/ad_block_filters_provider_manager.cc:100]: What if one provider A is updated (the second OnChangeda) before another provider B is ready?
We don't count OnChanged(), so looks like we just consume OnChanged from B and continue to use a cached DAT.

File: components/brave_shields/content/browser/ad_block_service.cc [hunk 94]
```diff
@@ -213,6 +248,124 @@ AdBlockService::~AdBlockService() {
...
+  DCHECK_CALLED_ON_VALID_SEQUENCE(sequence_checker_);
+  if (is_default_engine) {
+    default_dat_loaded_for_testing_ = true;
+  } else {
+    additional_dat_loaded_for_testing_ = true;
+  }
+  // If the cached DAT failed to load, fall back to loading from filter lists.
+  if (!success) {
+    if (is_default_engine) {
+      filters_provider_manager_->ForceNotifyObserver(*default_service_observer_,
```
Comment (atuchin-m) [inline components/brave_shields/content/browser/ad_block_service.cc:306]: Could we do something less tricky instead? I.e.
```
filters_provider_manager_->OnDatLoadFailed(false /* is_default_engine */);
default_service_observer_->OnDatLoadFailed()
```

This could be done in a follow-up.

File: components/brave_shields/core/browser/ad_block_filters_provider_manager.cc (hunk 93 above)
Comment (bridiver) [reply components/brave_shields/core/browser/ad_block_filters_provider_manager.cc:100]: We specifically don't care, we discussed this approach and decided to ignore the race conditions because it's too complex and they will get updated the next time there is a crx update which is many times a day

**Review by atuchin-m — APPROVED** [review]
