### PR TITLE
[plaster] Migration and fixes for request type customisations

### LINKED ISSUE #33203: [CR118] Refactor permission_request_data.h chromium_src override to use patch
This was mentioned in our cr118 review here https://github.com/brave/brave-core/pull/19765/commits/826f75c2cda8067122f8f68cbe9b78876ee8e2b4#r1334215951. We've had to add some overly complex handling to the chromium_src override for `permission_request_data.h` in order to get the correct definition for `PermissionContextBase`. Instead of juggling around these definitions, we should investigate adding a simple patch to do this in a cleaner way.

 cc: @goodov

### LINKED ISSUE #54949: Provide plaster for `components/permissions/request_type.cc`
This source is a bit of a mess, and the implementation at the moment is wrong, as `ContentSettingsTypeToRequestTypeIfExists`, rather than its callers, to provide our results consistently.

### PR DESCRIPTION
**Pull request by cdesouza-chromium**
This PR migrates all macros in `components/permissions/request_type.cc`
to plaster. The use of macros here particularly hid the fact that we
failed to override the correct functions, in particular the way we were
treating brave keys for `RequestTypeToContentSettingsType` and
`IsRequestablePermissionType` was incorrect as both these functions are
callers of `ContentSettingsTypeToRequestTypeIfExists`, and this fucntion
has been slipping through all this time.

Resolves https://github.com/brave/brave-browser/issues/54949
Resolves https://github.com/brave/brave-browser/issues/33203

### CODE REVIEW

File: rewrite/components/permissions/request_type.cc.toml [hunk 1]
```diff
@@ -0,0 +1,95 @@
+# Copyright (c) 2024 The Brave Authors. All rights reserved.
```
Comment (netzenbot) [inline rewrite/components/permissions/request_type.cc.toml]: nit: New files must use the current year in the copyright header. This file was created in 2026 but uses `Copyright (c) 2024`. Please update to 2026. ([✅ Copyright Year in New Files Must Be Current Year](https://github.com/brave/brave-core/tree/master/docs/best-practices/coding-standards.md#CS-012))

File: rewrite/components/permissions/request_type.h.toml [hunk 2]
```diff
@@ -0,0 +1,17 @@
+# Copyright (c) 2024 The Brave Authors. All rights reserved.
```
Comment (netzenbot) [inline rewrite/components/permissions/request_type.h.toml]: nit: New files must use the current year in the copyright header. This file was created in 2026 but uses `Copyright (c) 2024`. Please update to 2026. ([✅ Copyright Year in New Files Must Be Current Year](https://github.com/brave/brave-core/tree/master/docs/best-practices/coding-standards.md#CS-012))

File: rewrite/components/permissions/request_type.h.toml [hunk 3]
```diff
@@ -0,0 +1,17 @@
...
+# This Source Code Form is subject to the terms of the Mozilla Public
+# License, v. 2.0. If a copy of the MPL was not distributed with this file,
+# You can obtain one at https://mozilla.org/MPL/2.0/.
+
+[[substitution]]
+description = 'Add Brave-specific entries to `RequestType`'
+re_pattern = '(\bkStorageAccess\b,)'
```
Comment (netzenbot) [inline rewrite/components/permissions/request_type.h.toml]: nit: `kStorageAccess` is a unique enum value, so a plain `pattern: 'kStorageAccess,'` with `replace: 'kStorageAccess,\n  kWidevine,...'` would be simpler and more readable here. Per [PLSTR-002](https://github.com/brave/brave-core/tree/master/docs/best-practices/plaster.md#PLSTR-002), `re_pattern` is for when you need regex features like whitespace matching — the word boundaries and capture group here are unnecessary for a unique symbol.

File: rewrite/components/permissions/request_type.cc.toml (hunk 1 above)
Comment (cdesouza-chromium) [reply rewrite/components/permissions/request_type.cc.toml]: Fixed.

File: rewrite/components/permissions/request_type.h.toml (hunk 2 above)
Comment (cdesouza-chromium) [reply rewrite/components/permissions/request_type.h.toml]: Fixed.

File: rewrite/components/permissions/request_type.h.toml (hunk 3 above)
Comment (cdesouza-chromium) [reply rewrite/components/permissions/request_type.h.toml]: Fixed.

File: rewrite/components/permissions/request_type.cc.toml [hunk 4]
```diff
@@ -0,0 +1,95 @@
...
+    case ContentSettingsType::BRAVE_GOOGLE_SIGN_IN:
+      return RequestType::kBraveGoogleSignInPermission;
+    case ContentSettingsType::BRAVE_OPEN_AI_CHAT:
+      return RequestType::kBraveOpenAIChat;
+    case ContentSettingsType::DEFAULT:
+      return RequestType::kWidevine;\2'''
+
+[[substitution]]
+description = 'Add Brave permission types to `GetIconIdAndroid`'
+re_pattern = '(GetIconIdAndroid\([^)]*\) \{[\s\S]*?\n  switch[^{]*\{[\s\S]*?)(\n  \})'
```
Comment (bridiver) [inline rewrite/components/permissions/request_type.cc.toml]: fix whitespace like `\n  ` is fragile, I think you want multiline enabled here to simplify this? Same with `/n  ` at the end

**Review by netzenbot — APPROVED** [review]

File: rewrite/components/permissions/request_type.cc.toml (hunk 4 above)
Comment (cdesouza-chromium) [reply rewrite/components/permissions/request_type.cc.toml]: Fixed.

**Review by bridiver — APPROVED** [review]
