### PR TITLE
Web extension content setting changes affecting Shields (Block scripts) 

### LINKED ISSUE #45019: Web extension content setting changes affecting Shields (`Block scripts`)
### Description

https://community.brave.com/t/chrome-extensions-js/605808

A developer tested script blocking by extensions. But it affects Shields setting and there's no way to block scripts by extensions if Shields are disabled.

### Steps to reproduce

1. Access `brave.com`
2. Open Shields setting, the script blocking is disabled by default

Image

3.  Create a browser extension as below
```
chrome.contentSettings.javascript.set({
  primaryPattern: "https://brave.com/*",
  setting: "block"
});
```
4. Enable that extension on `brave://extensions/`

Image

5. Reload `brave.com`
6. Open Shields setting

### Actual result

The extension changes Shields setting, the script blocking is now enabled (by the extension)

Image

### Expected result

* Extensions shouldn't affect/change Shields setting
* The browser should block all scripts on `brave.com` by the extension even if Brave Shields are disabled

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

1.76.82

### Channel information

- [x] release (stable)
- [x] beta
- [x] nightly

### Reproducibility

- [x] with Brave Shields disabled
- [x] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

_No response_

### PR DESCRIPTION
**Pull request by vadimstruts**
Resolves https://github.com/brave/brave-browser/issues/45019

- Added the ability to check for the existence of extension-created rules (to block or allow scripts). Rules created by the extension take priority over those created by the user.
- Changed the `Block scripts` toggle on the Shields panel to be disabled when an extension-created rule exists, and added subtext explaining this behavior.

# Test plan

1. Access `brave.com`
2. Open `Shields setting`, the script blocking is disabled by default
3. Create a browser extension as below
```
chrome.contentSettings.javascript.set({
  primaryPattern: "https://brave.com/*",
  setting: "block"
});
```
4. Enable that extension on `brave://extensions/`
5. JS scripts must be blocked, on the Shields panel the `Block script` toggle should be ON and `(enforced by extension)` subtext added.
6. Remove the extension
7. Make sure that on the Shields panel the `Block script` toggle works in normal way

Video:

https://github.com/user-attachments/assets/8e7e6634-6ed4-4963-9af3-ef8c316e9d09

image

### CODE REVIEW

File: components/brave_shields/core/browser/brave_shields_utils.cc [hunk 1]
```diff
@@ -879,4 +882,21 @@ bool IsDeveloperModeEnabled(PrefService* profile_state) {
...
 
+mojom::ScriptBlockedByExtensionStatus GetScriptBlockedByExtensionStatus(
+    HostContentSettingsMap* map,
+    const GURL& primary_url) {
+  const auto rules =
+      map->GetSettingsForOneType(ContentSettingsType::JAVASCRIPT);
+  for (const auto& rule : rules) {
+    if (rule.primary_pattern.Matches(primary_url) &&
+        rule.source ==
+            content_settings::mojom::ProviderType::kCustomExtensionProvider) {
```
Comment (goodov) [inline components/brave_shields/core/browser/brave_shields_utils.cc]: what if JS is blocked by a policy. Will disabled shields re-enable JS in this case? Shouldn't we fix all these cases?

Comment (vadimstruts) [reply components/brave_shields/core/browser/brave_shields_utils.cc]: Policy has higher priority, then simple `ProviderType::kDefaultProvider`, so if we have rule from PolicyProvider type it doesn't depend from shields and JS will be blocked

**Review by StephenHeaps — APPROVED** [review]
Unblocking for minor iOS change. iOS++

**Review by mkarolin — APPROVED** [review]
`strings`++

File: components/brave_shields/core/browser/brave_shields_utils.cc [hunk 2]
```diff
@@ -879,4 +911,26 @@ bool IsDeveloperModeEnabled(PrefService* profile_state) {
   return profile_state->GetBoolean(prefs::kAdBlockDeveloperMode);
 }
 
+mojom::ContentSettingsOverriddenDataPtr GetContentSettingsOverriddenData(
```
Comment (goodov) [inline components/brave_shields/core/browser/brave_shields_utils.cc]: this should be implemented in `brave/components/brave_shields/core/browser/brave_shields_settings_service.h` from now on (make sure to rebase to latest master).

File: components/content_settings/renderer/brave_content_settings_agent_impl.h [hunk 3]
```diff
@@ -83,6 +83,9 @@ class BraveContentSettingsAgentImpl
 
   bool IsScriptTemporarilyAllowed(const GURL& script_url);
 
+  brave_shields::mojom::ContentSettingsOverriddenStatus
+  GetScriptBlockedByExtensionStatus() const;
```
Comment (goodov) [inline components/content_settings/renderer/brave_content_settings_agent_impl.h]: "extensions" should be not mentioned here.

File: components/brave_shields/core/browser/brave_shields_utils.cc [hunk 4]
```diff
@@ -150,6 +153,35 @@ base::Token CreateStableFarblingToken(const GURL& url) {
   return base::Token(high, low);
 }
 
+mojom::ContentSettingsOverrideSource ConvertSettingsSource(
+    const content_settings::SettingSource source) {
+  switch (source) {
+    case content_settings::SettingSource::kUser:
+      return mojom::ContentSettingsOverrideSource::kUser;
```
Comment (goodov) [inline components/brave_shields/core/browser/brave_shields_utils.cc]: do we need to have this mapping? can't we just use `content_settings::SettingSource` from mojo?

File: components/brave_shields/core/browser/brave_shields_settings_service.cc [hunk 5]
```diff
@@ -168,4 +168,12 @@ bool BraveShieldsSettingsService::IsNoScriptEnabled(const GURL& url) {
   return control_type != ControlType::ALLOW;
 }
 
+mojom::ContentSettingsOverriddenDataPtr
+BraveShieldsSettingsService::GetJsContentSettingsOverriddenData(
+    const GURL& url) {
+  return brave_shields::GetContentSettingsOverriddenData(
```
Comment (goodov) [inline components/brave_shields/core/browser/brave_shields_settings_service.cc]: please do not add `brave_shields::GetContentSettingsOverriddenData`, instead implement it right here. We are currently migrating those global functions into this service.

File: components/brave_shields/core/common/shields_settings.mojom [hunk 6]
```diff
@@ -13,11 +13,37 @@ enum FarblingLevel {
   MAXIMUM,
 };
 
+enum ContentSettingsOverriddenStatus {
+  kNotSet = 0,
+  kBlocked,
+  kAllowed
+};
+
+enum ContentSettingsOverrideSource {
```
Comment (goodov) [inline components/brave_shields/core/common/shields_settings.mojom]:
```
// Maps to content_settings::SettingSource
enum ContentSettingSource {
```

File: components/brave_shields/core/common/shields_settings.mojom [hunk 7]
```diff
@@ -13,11 +13,37 @@ enum FarblingLevel {
...
+  ContentSettingsOverriddenStatus status = kNotSet;
+  ContentSettingsOverrideSource override_source = kNone;
+};
+
 struct ShieldsSettings {
   FarblingLevel farbling_level;
   mojo_base.mojom.Token farbling_token;
   array<string> origins_to_allow_scripts;
   bool reduce_language;
+  ContentSettingsOverriddenData scripts_blocked_override_status;
```
Comment (goodov) [inline components/brave_shields/core/common/shields_settings.mojom]: do we really need to pass the override status *with the source* to renderer?

File: components/brave_shields/core/browser/brave_shields_settings_service.cc [hunk 8]
```diff
@@ -15,6 +15,39 @@
 
 namespace brave_shields {
 
+namespace {
+
+mojom::ContentSettingsOverrideSource ConvertSettingsSource(
```
Comment (goodov) [inline components/brave_shields/core/browser/brave_shields_settings_service.cc]: a place for this function is `core/common`.

File: components/brave_shields/core/common/shields_settings.mojom [hunk 9]
```diff
@@ -13,11 +13,37 @@ enum FarblingLevel {
   MAXIMUM,
 };
 
+enum ContentSettingsOverriddenStatus {
```
Comment (goodov) [inline components/brave_shields/core/common/shields_settings.mojom]: can't we use `ContentSetting` from `components/content_settings/core/common/content_settings.mojom`
and pass it as `ContentSetting? scripts_enforced_setting;` in `ShieldsSettings`?

File: components/brave_shields/core/common/shields_settings.mojom [hunk 10]
```diff
@@ -13,11 +13,27 @@ enum FarblingLevel {
...
+  kOsJavascriptOptimizer,
+  kTest,
+};
+
 struct ShieldsSettings {
   FarblingLevel farbling_level;
   mojo_base.mojom.Token farbling_token;
   array<string> origins_to_allow_scripts;
   bool reduce_language;
+  bool enforced_script_blocking = false;
```
Comment (goodov) [inline components/brave_shields/core/common/shields_settings.mojom]: do not default values here please.

File: browser/brave_shields/brave_shields_web_contents_observer_browsertest.cc [hunk 11]
```diff
@@ -118,6 +123,60 @@ class BraveShieldsWebContentsObserverBrowserTest : public InProcessBrowserTest {
...
+ public:
+  BraveShieldsWebContentsObserverManagedPolicyBrowserTest() = default;
+
+  void SetUpOnMainThread() override {
+    BraveShieldsWebContentsObserverBrowserTest::SetUpOnMainThread();
+
+    // Enable JavaScript blocking globally.
+    content_settings()->SetContentSettingCustomScope(
+        ContentSettingsPattern::Wildcard(), ContentSettingsPattern::Wildcard(),
+        ContentSettingsType::JAVASCRIPT, CONTENT_SETTING_ALLOW);
```
Comment (goodov) [inline browser/brave_shields/brave_shields_web_contents_observer_browsertest.cc]: how `CONTENT_SETTING_ALLOW` is "Enable JavaScript blocking globally"?

File: browser/brave_shields/brave_shields_web_contents_observer_browsertest.cc [hunk 12]
```diff
@@ -118,6 +123,60 @@ class BraveShieldsWebContentsObserverBrowserTest : public InProcessBrowserTest {
...
+  policy::MockConfigurationPolicyProvider provider_;
+};
+
+IN_PROC_BROWSER_TEST_F(BraveShieldsWebContentsObserverManagedPolicyBrowserTest,
+                       JavaScriptBlockedEvents) {
+  const GURL& url = GURL("a.com");
+
+  // try to enable JavaScript for user provider
+  ContentSetting block_javascript_setting =
+      content_settings()->GetContentSetting(url, url,
```
Comment (goodov) [inline browser/brave_shields/brave_shields_web_contents_observer_browsertest.cc]: > try to enable JavaScript for user provider

> `GetContentSetting`

how `Get*` can enable it?

File: browser/brave_shields/brave_shields_web_contents_observer_browsertest.cc (hunk 11 above)
Comment (vadimstruts) [reply browser/brave_shields/brave_shields_web_contents_observer_browsertest.cc]: removed it

File: browser/brave_shields/brave_shields_web_contents_observer_browsertest.cc [hunk 13]
```diff
@@ -118,6 +123,60 @@ class BraveShieldsWebContentsObserverBrowserTest : public InProcessBrowserTest {
...
+    provider_.UpdateChromePolicy(policies);
+  }
+
+ private:
+  policy::MockConfigurationPolicyProvider provider_;
+};
+
+IN_PROC_BROWSER_TEST_F(BraveShieldsWebContentsObserverManagedPolicyBrowserTest,
+                       JavaScriptBlockedEvents) {
+  auto first_url = GURL("http://a.com");
```
Comment (goodov) [inline browser/brave_shields/brave_shields_web_contents_observer_browsertest.cc]:
```
a_com_url
b_com_url
```

File: browser/brave_shields/brave_shields_web_contents_observer_browsertest.cc [hunk 14]
```diff
@@ -118,6 +123,60 @@ class BraveShieldsWebContentsObserverBrowserTest : public InProcessBrowserTest {
...
+  auto second_url = GURL("http://b.com");
+
+  // Verify that the policy is applied correctly
+  ContentSetting first_block_javascript_setting =
```
Comment (goodov) [inline browser/brave_shields/brave_shields_web_contents_observer_browsertest.cc]:
```
a_com_javascript_setting
b_com_javascript_setting
```

File: browser/brave_shields/brave_shields_web_contents_observer_browsertest.cc [hunk 15]
```diff
@@ -118,6 +123,60 @@ class BraveShieldsWebContentsObserverBrowserTest : public InProcessBrowserTest {
...
+      content_settings()->GetContentSetting(first_url, first_url,
+                                            ContentSettingsType::JAVASCRIPT);
+  EXPECT_EQ(CONTENT_SETTING_BLOCK, first_block_javascript_setting);
+  ContentSetting second_block_javascript_setting =
+      content_settings()->GetContentSetting(second_url, second_url,
+                                            ContentSettingsType::JAVASCRIPT);
+  EXPECT_EQ(CONTENT_SETTING_ALLOW, second_block_javascript_setting);
+
+  // Navigate to the first URL which has JavaScript blocked by policy
```
Comment (goodov) [inline browser/brave_shields/brave_shields_web_contents_observer_browsertest.cc]: to the a.com URL

File: browser/brave_shields/brave_shields_web_contents_observer_browsertest.cc [hunk 16]
```diff
@@ -118,6 +123,60 @@ class BraveShieldsWebContentsObserverBrowserTest : public InProcessBrowserTest {
...
+  EXPECT_TRUE(ui_test_utils::NavigateToURL(
+      browser(), embedded_test_server()->GetURL("a.com", "/load_js.html")));
+  EXPECT_TRUE(WaitForLoadStop(GetWebContents()));
+  EXPECT_EQ(brave_shields_web_contents_observer()->block_javascript_count(), 5);
+  EXPECT_EQ(GetBlockedJsList().size(), 3u);
+}
```
Comment (goodov) [inline browser/brave_shields/brave_shields_web_contents_observer_browsertest.cc:178]: please follow this PR with another one where this case is fixed: 
1. blocks JS globally via Setting page.
2. disable shields on a specific website.
3. load said website.
4. expect JS is blocked on the website.

File: components/brave_shields/core/browser/brave_shields_settings_service.cc [hunk 17]
```diff
@@ -168,4 +167,31 @@ bool BraveShieldsSettingsService::IsNoScriptEnabled(const GURL& url) {
...
+      url, GURL(), content_settings::mojom::ContentSettingsType::JAVASCRIPT,
+      &info);
+
+  // No override
+  if (info.source == content_settings::SettingSource::kUser) {
+    return nullptr;
+  }
+
+  return mojom::ContentSettingsOverriddenData::New(
+      rule == CONTENT_SETTING_BLOCK ? ::ContentSetting::CONTENT_SETTING_BLOCK
```
Comment (goodov) [inline components/brave_shields/core/browser/brave_shields_settings_service.cc]: why this condition? just pass `rule`.

File: components/brave_shields/core/browser/brave_shields_settings_service.h [hunk 18]
```diff
@@ -47,6 +48,10 @@ class BraveShieldsSettingsService : public KeyedService {
   void SetNoScriptEnabled(bool is_enabled, const GURL& url);
   bool IsNoScriptEnabled(const GURL& url);
 
+  bool IsJsBlockingEnforced(const GURL& url);
+  mojom::ContentSettingsOverriddenDataPtr GetJsContentSettingsOverriddenData(
```
Comment (goodov) [inline components/brave_shields/core/browser/brave_shields_settings_service.h]: `ContentSettings` -> `ContentSetting`

File: components/brave_shields/core/common/brave_shield_utils.h [hunk 19]
```diff
@@ -36,6 +37,8 @@ ShieldsSettingCounts GetSettingCountFromRules(
 ShieldsSettingCounts GetSettingCountFromCosmeticFilteringRules(
     const ContentSettingsForOneType& fp_rules);
 
+mojom::ContentSettingSource ConvertSettingsSource(
+    const content_settings::SettingSource source);
 }  // namespace brave_shields
```
Comment (goodov) [inline components/brave_shields/core/common/brave_shield_utils.h:43]: pls keep a new line

File: components/content_settings/renderer/brave_content_settings_agent_impl.cc [hunk 20]
```diff
@@ -183,7 +190,8 @@ bool BraveContentSettingsAgentImpl::AllowScript(bool enabled_per_settings) {
       BraveSpecificDidAllowJavaScriptOnce(secondary_url);
     }
   }
-  return allow;
+
+  return IsJsBlockingEnforced() ? false : allow;
```
Comment (goodov) [inline components/content_settings/renderer/brave_content_settings_agent_impl.cc]: shouldn't this become part of `allow = ` above? otherwise this will be executed incorrectly:
```
  if (!allow) {
    blocked_script_url_ = secondary_url;
  } else if (!is_shields_down) {
    if (is_script_temporarily_allowed) {
      BraveSpecificDidAllowJavaScriptOnce(secondary_url);
    }
  }
```

**Review by goodov — APPROVED** [review]
While this PR fixes a concrete issue where JS is not blocked by a policy or extension in some scenarios, we should follow this up with a full fix that will prevent Shields in a disabled state to re-enable JS if user disable it globally via Settings.

See https://github.com/brave/brave-core/pull/31484/files#r2470409670

File: components/brave_shields/core/browser/brave_shields_settings_service.cc [hunk 21]
```diff
@@ -200,4 +200,29 @@ mojom::AutoShredMode BraveShieldsSettingsService::GetAutoShredMode(
...
+bool BraveShieldsSettingsService::IsJsBlockingEnforced(const GURL& url) {
+  const auto js_content_settings_overridden_data =
+      GetJsContentSettingOverriddenData(url);
+  return js_content_settings_overridden_data &&
+         js_content_settings_overridden_data->status ==
+             ::ContentSetting::CONTENT_SETTING_BLOCK;
+}
+
+mojom::ContentSettingsOverriddenDataPtr
+BraveShieldsSettingsService::GetJsContentSettingOverriddenData(
```
Comment (bridiver) [inline components/brave_shields/core/browser/brave_shields_settings_service.cc:212]: I don't understand the point of this, all content settings are already available in the renderer process so why do we need to jump through hoops to pass this in?

**Comment by bridiver** [comment]
As a general concern special casing JS content settings here is a problematic approach imo. The fundamental problem is that we make brave shields disabled check separately from the content settings and what we need is an "effective content setting" that already includes shields. Then all checks are just simple content setting checks and all provider priorities work as expected.
