### PR TITLE
[iOS] Increase sync device limit to 50 to match backend

### LINKED ISSUE #54452: Sync chain device limit is incorrect on iOS
iOS currently limits the number of devices that can be added to the sync chain to 10 which is not up to date with backend (50)

Community post: https://community.brave.app/t/brave-sync-limit-10-devices-not-updating-after-removing-devices/570318/

### PR DESCRIPTION
**Pull request by kylehickinson**
The current client-side limit of 10 was out of date

Resolves https://github.com/brave/brave-browser/issues/54452

### CODE REVIEW

File: ios/brave-ios/Sources/Brave/Frontend/Sync/SyncWelcomeViewController.swift [hunk 1]
```diff
@@ -510,9 +510,9 @@ extension SyncWelcomeViewController: SyncPairControllerDelegate {
     switch devices.count {
     case 1...4:
       deviceLimitLevel = .safe
-    case 5...9:
+    case 5..<50:
       deviceLimitLevel = .approvalNeeded
-    case 10...:
+    case 50...:
```
Comment (StephenHeaps) [inline ios/brave-ios/Sources/Brave/Frontend/Sync/SyncWelcomeViewController.swift:515]: Is there a constant in core that could be used so this only needs to be updated once for all platforms?

Comment (kylehickinson) [reply ios/brave-ios/Sources/Brave/Frontend/Sync/SyncWelcomeViewController.swift:515]: AFAIK iOS was the only one to implement this client side check, so nothing shared to use from desktop/android. The limit is here: https://github.com/brave/go-sync/blob/master/command/device_limit.go#L9

Perhaps we just remove it entirely but I'll let @fmarier weigh in on that

Comment (fmarier) [reply ios/brave-ios/Sources/Brave/Frontend/Sync/SyncWelcomeViewController.swift:515]: Yes, we may as well rely on the server-enforced limit without enforcing an additional client-side limit.

Comment (kylehickinson) [reply ios/brave-ios/Sources/Brave/Frontend/Sync/SyncWelcomeViewController.swift:515]: @fmarier Lets open a follow-up issue for removing it in that case, as it has some other product related changes that probably will want more focus

**Review by fmarier — APPROVED** [review]

**Review by StephenHeaps — APPROVED** [review]

File: ios/brave-ios/Sources/Brave/Frontend/Sync/SyncWelcomeViewController.swift (hunk 1 above)
Comment (StephenHeaps) [reply ios/brave-ios/Sources/Brave/Frontend/Sync/SyncWelcomeViewController.swift:515]: Sounds good, feel free to resolve comment to merge 🙂

Comment (kylehickinson) [reply ios/brave-ios/Sources/Brave/Frontend/Sync/SyncWelcomeViewController.swift:515]: Opened https://github.com/brave/brave-browser/issues/54453
