### PR TITLE
Fixes min width for scrollable horizontal tab strip.

### LINKED ISSUE #55045: Minimum tab width no longer correct when using scrollable tab strip
### Description

In Release (1.89.143) and Beta (1.90.116), if `brave://flags/#brave-scrollable-tab-strip` is enabled, then the minimum tab width is the same as a pinned tab. Note, the minimum tab width is smaller if this flag is not enabled.

In Nightly, both 1.91.118 with C147 and 1.91.119 with C149, the minimum tab width is no longer correct when scrollable tab strip is enabled. Note, this must be done via settings now, as this was changed with https://github.com/brave/brave-browser/issues/54438) and the flag is enabled by default in 1.91.x.

### Steps to reproduce

1. On 1.91.x either with or without C148, go to brave://settings/appearance
2. Enable "Use scrollable tab strip"
3. See that "Minimum tab width" setting is displayed with a default value of "Minimum (Default)"
4. Create a bunch of tabs so that the horizontal tab strip will scroll
5. See that the minimum tab width is much narrower than in Release and Beta

### Actual result

1.91.118 with Chromium 147:

Image

1.91.119 with Chromium 148:

Image

### Expected result

Minimum tab width should be the same as a pinned tab as it is in 1.89.x and 1.90.x:

Image

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

```
Brave | 1.91.118 Chromium: 147.0.7727.117 (Official Build) nightly (arm64)
-- | --
Revision | b6e937c7792c018ac51c669aa40769aff09264ad
OS | macOS Version 26.3 (Build 25D125)
```

```
Brave | 1.91.119 Chromium: 148.0.7778.60 (Official Build) nightly (arm64)
-- | --
Revision | d72d27ea10e0c034443e7252c1eba80359c029d1
OS | macOS Version 26.3 (Build 25D125)
```

### Channel information

- [ ] release (stable)
- [ ] beta
- [x] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

cc @rebron @sangwoo108 @brave/qa-team

### PR DESCRIPTION
**Pull request by sangwoo108**
When horizontal scrollable tab strip is active (feature + pref), we can have wider inactive tabs. If not scrolling feature is not that helpful.

Resolves https://github.com/brave/brave-browser/issues/55045

### CODE REVIEW

**Review by netzenbot — APPROVED** [review]

**Comment by diracdeltas** [comment]
why was package-lock.json changed?

**Review by emerick — APPROVED** [review]

**Comment by sangwoo108** [comment]
> why was package-lock.json changed?

oops, it was accidentally added. thanks

File: browser/ui/views/tabs/brave_tab.cc [hunk 1]
```diff
@@ -556,6 +556,14 @@ TabSizeInfo BraveTab::GetTabSizeInfo() const {
   size_info.min_inactive_width = GetTabMinWidthForMode(
       mode, size_info.min_inactive_width, size_info.standard_width);
 
+  if (controller()->IsHorizontalScrollingEnabled()) {
+    // When horizontal scrollable tab strip is active (feature + pref), we
+    // can have wider inactive tabs.
+    const int min_active_width = tab_style()->GetMinimumActiveWidth(false);
+    size_info.min_inactive_width =
```
Comment (simonhong) [inline browser/ui/views/tabs/brave_tab.cc:563]: q) don't need to handle min_active_width?

**Review by simonhong — APPROVED** [review]
++

File: browser/ui/views/tabs/brave_tab.cc (hunk 1 above)
Comment (sangwoo108) [reply browser/ui/views/tabs/brave_tab.cc:563]: Yes, they are already in good width.

**Comment by LaurenWags** [comment]
Verified with

```
Brave | 1.92.4 Chromium: 148.0.7778.96 (Official Build) nightly (arm64)
-- | --
Revision | 0be82570025e1611baf072294f99a69a95d73616
OS | macOS Version 26.3 (Build 25D125)
```

Using `1.92.2 Chromium: 148.0.7778.60` and STR from https://github.com/brave/brave-browser/issues/55045#issue-4345870421, reproduced the issue:

https://github.com/user-attachments/assets/878db94d-a612-4e67-a84a-1534364eb56e

Using `1.92.4 Chromium: 148.0.7778.96` and same STR, confirmed expected minimum tab width for horizontal scrolling. It is about the same width as a pinned tab - which is included in the below video for reference.

https://github.com/user-attachments/assets/c441b1fc-7395-4cfb-b7aa-d9c589861327
