### PR TITLE
[iOS] [AI Chat] Replace Skia with UIKit for image decoding & scaling

### LINKED ISSUE #54936: App crashes when pasting images that require scaling to Leo as attachments
### Description

Thread: https://bravesoftware.slack.com/archives/CHGKGMHDJ/p1776979154455619

Seems like the issue specifically is any photo added that is bigger than 1024x768 will result in the crash.

Related to #54899

### Steps to reproduce

Image

1. Have an image in your clipboard thats width & height exceed 1024 x 768
2. Load Leo WebUI and paste directly into input field.

### Actual result

Crash

### Expected result

Attachments should work

### Reproduces how often

Easily reproduced

### Brave version

1.91 (108)

### Device/iOS version

iPhone, iOS 26, iOS 18

### Affected browser versions

- [ ] latest AppStore
- [x] latest TestFlight
- [x] previous TestFlight

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] in the latest version of mobile Safari

### Miscellaneous information

_No response_

### PR DESCRIPTION
**Pull request by kylehickinson**
Skia's `SkCanvas` requires the usage of a `DiscardableMemoryAllocator` which is not set in Chromium iOS so the shared scale logic fails a CHECK and crashes at runtime.

Resolves https://github.com/brave/brave-browser/issues/54936

### CODE REVIEW

File: ios/browser/ui/webui/ai_chat/ai_chat_ui_page_handler.mm [hunk 1]
```diff
@@ -60,19 +61,31 @@
...
+                                   length:file_data.size()];
   auto encode_image = base::BindOnce(
-      [](const SkBitmap& decoded_bitmap) {
-        return gfx::PNGCodec::EncodeBGRASkBitmap(
-            ScaleDownBitmap(decoded_bitmap), false);
+      [](NSData* data) -> std::optional<std::vector<uint8_t>> {
+        CGSize target_size = CGSizeMake(1024, 768);
+        UIImage* image = [[UIImage alloc] initWithData:data];
+        if (image.size.width >= target_size.width &&
+            image.size.height >= target_size.height) {
```
Comment (nuo-xu) [inline ios/browser/ui/webui/ai_chat/ai_chat_ui_page_handler.mm]: we used `>` in the other PR.

Comment (kylehickinson) [reply ios/browser/ui/webui/ai_chat/ai_chat_ui_page_handler.mm]: good catch, fixed

**Review by nuo-xu — APPROVED** [review]

**Review by netzenbot — APPROVED** [review]

**Comment by Uni-verse** [comment]
Verified on `iPhone 12` running `iOS 26.3.1` using version `1.91 (116)`

- Ensured that images larger than 1024 x 768 as mentioned in https://github.com/brave/brave-browser/issues/54936#issue-4323921779 are being scaled down and successfully added as an attachment.
- Ensured that adding multiple images is successful.
- Ensured images can be removed and then re-added again using the methods available.

Note: encountered intermittent crash: https://github.com/brave/brave-browser/issues/55032 when testing adding multiple images

example | example | example
--|--|--
IMG_0268 | IMG_0269 | IMG_0270
