### PR TITLE
[Containers] Show containers menu on new tab button

### LINKED ISSUE #54484: [Containers] Add right click menu for new tab button
### Description

When users right click on the new tab button, give them the option to open the new tab in a container

See Figma link: https://www.figma.com/design/qOIex7poMN1YbnepQJEvIo/%F0%9F%93%A6-Containers?node-id=3570-11083&t=PRAHBq2haSwl2ZvD-1

### Steps to reproduce

1. Right click on the new tab button from either horizontal or vertical tabs
2. Containers menu should appear.

### Actual result

Currently, no right click menu.

### Expected result

Image

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

1.91.43 and higher

### Channel information

- [ ] release (stable)
- [ ] beta
- [x] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

Related to: https://github.com/brave/brave-browser/issues/53350

### PR DESCRIPTION
**Pull request by sangwoo108**
When right clicking on new tab button, shows containers menu. Users can pick a container to open new tab in.

Resolves https://github.com/brave/brave-browser/issues/54484

### CODE REVIEW

File: browser/ui/views/tabs/brave_new_tab_button.h [hunk 1]
```diff
@@ -36,10 +47,35 @@ class BraveNewTabButton : public NewTabButton {
...
+  raw_ptr<BrowserWindowInterface> browser_window_interface_ = nullptr;
+
+#if BUILDFLAG(ENABLE_CONTAINERS)
+  std::unique_ptr<NewTabButtonContainersMenuDelegate> containers_menu_delegate_;
+  std::unique_ptr<containers::ContainersMenuModel> containers_menu_model_;
+  std::unique_ptr<views::MenuRunner> containers_context_menu_runner_;
+#endif
 };
 
 #endif  // BRAVE_BROWSER_UI_VIEWS_TABS_BRAVE_NEW_TAB_BUTTON_H_
```
Comment (netzenbot) [inline browser/ui/views/tabs/brave_new_tab_button.h:77]: nit: `containers_context_menu_runner_for_testing()` is a public method added only for test access to a private member. Per [ARCH-020](https://github.com/brave/brave-core/tree/master/docs/best-practices/architecture.md#ARCH-020), use a `friend class` declaration in the private section instead of exposing a public getter. Since `BraveNewTabButton` is our own class, no `#define` trick is needed — just add `friend class ContainersBrowserTest;` (or the specific test fixture name) inside `private:`.

File: browser/ui/views/tabs/brave_new_tab_button.cc [hunk 2]
```diff
@@ -7,13 +7,78 @@
...
+        BrowserView::GetBrowserViewForBrowser(browser_window_interface_.get());
+    CHECK(browser_view);
+    auto* widget = browser_view->GetWidget();
+    CHECK(widget);
+    auto* compositor = widget->GetCompositor();
+    CHECK(compositor);
+    return compositor->device_scale_factor();
+  }
+
+ private:
```
Comment (netzenbot) [inline browser/ui/views/tabs/brave_new_tab_button.cc:78]: nit: `#include "base/feature_list.h"` and `#include "brave/browser/ui/browser_commands.h"` at lines 77-78 are only used inside the `#if BUILDFLAG(ENABLE_CONTAINERS)` block. Per [BS-034](https://github.com/brave/brave-core/tree/master/docs/best-practices/build-system.md#BS-034), these includes should be moved inside the guard.

File: browser/ui/views/tabs/brave_new_tab_button.h (hunk 1 above)
Comment (netzenbot) [inline browser/ui/views/tabs/brave_new_tab_button.h:77]: nit: Per [CSM-013](https://github.com/brave/brave-core/tree/master/docs/best-practices/coding-standards-memory.md#CSM-013), `raw_ptr<>` members should come after owning members (`std::unique_ptr<>`). Move `browser_window_interface_` after the `#if BUILDFLAG(ENABLE_CONTAINERS)` block with the `unique_ptr` members.

File: browser/ui/views/tabs/brave_new_tab_button.cc [hunk 3]
```diff
@@ -12,8 +12,73 @@
...
+  raw_ptr<BrowserWindowInterface> browser_window_interface_ = nullptr;
+};
+#endif
+
 // static
 gfx::Size BraveNewTabButton::GetButtonSize() {
   if (!HorizontalTabsUpdateEnabled()) {
```
Comment (netzenbot) [inline browser/ui/views/tabs/brave_new_tab_button.cc:85]: nit: This `#endif` closes a 13-line `#if BUILDFLAG(ENABLE_CONTAINERS)` block but has no trailing comment. Per [BS-045](https://github.com/brave/brave-core/tree/master/docs/best-practices/build-system.md#BS-045), blocks > 3 lines should always have a comment, and the later `#endif` in this file already uses `#endif  // BUILDFLAG(ENABLE_CONTAINERS)`. Please add the comment here for consistency.

File: browser/ui/views/tabs/brave_new_tab_button.cc [hunk 4]
```diff
@@ -12,8 +12,73 @@
...
 #include "ui/gfx/paint_vector_icon.h"
 
+#if BUILDFLAG(ENABLE_CONTAINERS)
+#include "base/containers/flat_set.h"
+#include "base/feature_list.h"
+#include "brave/browser/containers/containers_service_factory.h"
+#include "brave/browser/ui/browser_commands.h"
+#include "brave/browser/ui/containers/containers_menu_model.h"
+#include "brave/components/containers/core/common/features.h"
+#include "chrome/browser/profiles/profile.h"
```
Comment (netzenbot) [inline browser/ui/views/tabs/brave_new_tab_button.cc:23]: nit: The constructor `CHECK(browser_window_interface_)` signals this parameter can never be null, so prefer a reference parameter (`BrowserWindowInterface&`) and store it as `raw_ref<BrowserWindowInterface>` instead of `raw_ptr`. Per [CSA-030](https://github.com/brave/brave-core/tree/master/docs/best-practices/coding-standards-apis.md#CSA-030), use references for non-nullable parameters and `raw_ref` for stored non-null members.

File: browser/ui/views/tabs/brave_new_tab_button.cc [hunk 5]
```diff
@@ -12,8 +12,73 @@
...
+    CHECK(browser);
+    brave::OpenUrlInContainer(browser_window_interface_.get(),
+                              browser->GetNewTabURL(), container);
+  }
+
+  void OnNoContainerSelected() override {
+    auto* browser = GetBrowserToOpenSettings();
+    CHECK(browser);
+    brave::OpenUrlWithoutContainer(browser_window_interface_.get(),
+                                   browser->GetNewTabURL());
```
Comment (netzenbot) [inline browser/ui/views/tabs/brave_new_tab_button.cc:56]: nit: `GetCurrentContainerIds()` silently returns `{}` — a brief comment explaining that the new tab button has no "current" container (unlike tab or link context menus) would clarify this intentional choice for future maintainers. Per [DOC-004](https://github.com/brave/brave-core/tree/master/docs/best-practices/documentation.md#DOC-004), the contract of non-obvious return values should be documented.

File: browser/containers/containers_browsertest.cc [hunk 6]
```diff
@@ -1818,4 +1825,27 @@ IN_PROC_BROWSER_TEST_F(ContainersBrowserTest,
...
+  BrowserView* const browser_view =
+      BrowserView::GetBrowserViewForBrowser(browser());
+  ASSERT_TRUE(browser_view);
+  auto* horizontal_tab_strip_region =
+      views::AsViewClass<HorizontalTabStripRegionView>(
+          browser_view->tab_strip_view());
+  ASSERT_TRUE(horizontal_tab_strip_region);
+  auto* new_tab = views::AsViewClass<BraveNewTabButton>(
+      horizontal_tab_strip_region->new_tab_button_for_testing());
+  ASSERT_TRUE(new_tab);
```
Comment (netzenbot) [inline browser/containers/containers_browsertest.cc:1874]: nit: `ShowContextMenuForViewImpl` has a guard on `features::kContainers` that falls through to `NewTabButton::ShowContextMenuForViewImpl` when disabled. Per [TI-026](https://github.com/brave/brave-core/tree/master/docs/best-practices/testing-isolation.md#TI-026), consider adding a second test that verifies the fallback behavior when the feature is off (e.g., the containers menu runner is NOT started).

File: browser/ui/views/tabs/brave_new_tab_button.h [hunk 7]
```diff
@@ -6,14 +6,26 @@
...
 #include "ui/gfx/geometry/size.h"
 
 class TabStrip;
 namespace views {
 class ButtonListener;
-}
+class MenuRunner;
+}  // namespace views
+
+#if BUILDFLAG(ENABLE_CONTAINERS)
```
Comment (netzenbot) [inline browser/ui/views/tabs/brave_new_tab_button.h:23]: nit: Per [BS-051](https://github.com/brave/brave-core/tree/master/docs/best-practices/build-system.md#BS-051), forward declarations don't need `#if BUILDFLAG(...)` guards — they're harmless and don't pull in dependencies. The `#if BUILDFLAG(ENABLE_CONTAINERS)` block here can be removed; just leave the bare `namespace containers { class ContainersBrowserTest; class ContainersMenuModel; }` forward declarations.

File: browser/ui/views/tabs/brave_new_tab_button.h [hunk 8]
```diff
@@ -36,10 +48,30 @@ class BraveNewTabButton : public NewTabButton {
...
+
  protected:
   // NewTabButton:
   gfx::Size CalculatePreferredSize(
       const views::SizeBounds& available_size) const override;
+
+ private:
+#if BUILDFLAG(ENABLE_CONTAINERS)
+  class NewTabButtonContainersMenuDelegate;
+  friend class containers::ContainersBrowserTest;
```
Comment (netzenbot) [inline browser/ui/views/tabs/brave_new_tab_button.h:67]: nit: Per [CS-015](https://github.com/brave/brave-core/tree/master/docs/best-practices/coding-standards.md#CS-015), `friend` declarations should come immediately after `private:`, before any other members. Move `friend class containers::ContainersBrowserTest;` to be the first item inside `#if BUILDFLAG(ENABLE_CONTAINERS)`, before `class NewTabButtonContainersMenuDelegate;`.

File: browser/ui/views/tabs/brave_new_tab_button.cc [hunk 9]
```diff
@@ -55,5 +122,37 @@ BraveNewTabButton::BraveNewTabButton(
 
 BraveNewTabButton::~BraveNewTabButton() = default;
 
+#if BUILDFLAG(ENABLE_CONTAINERS)
+void BraveNewTabButton::ShowContextMenuForViewImpl(
```
Comment (netzenbot) [inline browser/ui/views/tabs/brave_new_tab_button.cc:126]: nit: Per [CS-017](https://github.com/brave/brave-core/tree/master/docs/best-practices/coding-standards.md#CS-017), function definitions in `.cc` should follow the same order as their declarations in `.h`. `ShowContextMenuForViewImpl` is declared in the public section before `CalculatePreferredSize` in the protected section of the header, but it is defined after `CalculatePreferredSize` in the `.cc`. Consider moving `ShowContextMenuForViewImpl` before `CalculatePreferredSize` in the `.cc`.

File: browser/ui/views/tabs/brave_new_tab_button.h [hunk 10]
```diff
@@ -36,10 +48,30 @@ class BraveNewTabButton : public NewTabButton {
...
+
+  std::unique_ptr<NewTabButtonContainersMenuDelegate> containers_menu_delegate_;
+  std::unique_ptr<containers::ContainersMenuModel> containers_menu_model_;
+  std::unique_ptr<views::MenuRunner> containers_context_menu_runner_;
+#endif
+
+  raw_ptr<BrowserWindowInterface> browser_window_interface_ = nullptr;
 };
```
Comment (netzenbot) [inline browser/ui/views/tabs/brave_new_tab_button.h:76]: nit: `browser_window_interface_` is always set by every constructor (both the full and delegating one), so the `= nullptr` default is misleading per [CS-054](https://github.com/brave/brave-core/tree/master/docs/best-practices/coding-standards.md#CS-054). Remove the in-class initializer and rely on the constructor.

**Review by netzenbot — APPROVED** [review]

File: browser/ui/views/tabs/brave_new_tab_button.h [hunk 11]
```diff
@@ -36,10 +46,31 @@ class BraveNewTabButton : public NewTabButton {
...
+  friend class containers::ContainersBrowserTest;
+
+  class NewTabButtonContainersMenuDelegate;
+
+  std::unique_ptr<NewTabButtonContainersMenuDelegate> containers_menu_delegate_;
+  std::unique_ptr<containers::ContainersMenuModel> containers_menu_model_;
+  std::unique_ptr<views::MenuRunner> containers_context_menu_runner_;
+#endif
+
+  raw_ptr<BrowserWindowInterface> browser_window_interface_;
```
Comment (goodov) [inline browser/ui/views/tabs/brave_new_tab_button.h]: `const` or `const raw_ref`?

**Review by goodov — APPROVED** [review]
lgtm!

File: browser/ui/views/tabs/brave_new_tab_button.h (hunk 11 above)
Comment (sangwoo108) [reply browser/ui/views/tabs/brave_new_tab_button.h]: Good call!

File: browser/ui/views/tabs/brave_new_tab_button.cc [hunk 12]
```diff
@@ -108,7 +108,7 @@ BraveNewTabButton::BraveNewTabButton(
                    fixed_flat_edge,
                    animated_flat_edge,
                    browser_window_interface),
-      browser_window_interface_(browser_window_interface) {}
+      browser_window_interface_(*browser_window_interface) {}
```
Comment (goodov) [inline browser/ui/views/tabs/brave_new_tab_button.cc]: `CHECK_DEREF`

Comment (sangwoo108) [reply browser/ui/views/tabs/brave_new_tab_button.cc]: Nice.

**Comment by goodov** [comment]
@sangwoo108 just rebased to try this and saw this on linux (happens on second menu show attempt).

```
[DanglingSignature]     base::debug::CollectStackTrace()        No active task containers::ContainersMenuModel::~ContainersMenuModel()  No active task

[DanglingPtr](1/3) A raw_ptr/raw_ref is dangling.

[DanglingPtr](2/3) First, the memory was freed at:

Stack trace:
#0 0x73dcb0567cf2 base::debug::CollectStackTrace()
#1 0x73dcb05435a1 base::debug::StackTrace::StackTrace()
#2 0x73dcb0570ca6 base::allocator::(anonymous namespace)::DanglingRawPtrDetected()
#3 0x73dcb013a915 allocator_shim::internal::PartitionAllocFunctionsInternal<>::FreeWithSize()
#4 0x65042325121c BraveNewTabButton::NewTabButtonContainersMenuDelegate::~NewTabButtonContainersMenuDelegate()
#5 0x650423250e82 BraveNewTabButton::ShowContextMenuForViewImpl()
#6 0x73dca4ec8478 views::ContextMenuController::ShowContextMenuForView()
#7 0x73dca4fe6505 views::View::ShowContextMenu()
#8 0x73dca4fe3ebb views::View::ProcessMousePressed()
#9 0x73dca4fe3bd2 views::View::OnMouseEvent()
#10 0x73dcae3778ae ui::ScopedTargetHandler::OnEvent()
#11 0x73dcae36d16a ui::EventDispatcher::DispatchEvent()
#12 0x73dcae36c6b0 ui::EventDispatcher::ProcessEvent()
#13 0x73dcae36c2c7 ui::EventDispatcherDelegate::DispatchEventToTarget()
#14 0x73dcae36bf72 ui::EventDispatcherDelegate::DispatchEvent()
#15 0x73dca4ff8fad views::internal::RootView::OnMousePressed()
#16 0x73dca500b0af views::Widget::OnMouseEvent()
#17 0x73dca5064f74 views::DesktopNativeWidgetAura::OnMouseEvent()
#18 0x73dcae36d16a ui::EventDispatcher::DispatchEvent()
#19 0x73dcae36c6b0 ui::EventDispatcher::ProcessEvent()
#20 0x73dcae36c2c7 ui::EventDispatcherDelegate::DispatchEventToTarget()
#21 0x73dcae36bf72 ui::EventDispatcherDelegate::DispatchEvent()
#22 0x73dcae36f8d0 ui::EventProcessor::OnEventFromSource()
#23 0x73dca67f1cad aura::WindowTreeHostPlatform::DispatchEvent()
#24 0x73dca5068612 views::DesktopWindowTreeHostLinux::DispatchEvent()
#25 0x73dcae37a169 base::OnceCallback<>::Run()
#26 0x73dcae379f3f ui::DispatchEventFromNativeUiEvent()
#27 0x73dcb0abf55a ui::X11Window::DispatchUiEvent()
#28 0x73dcb0abf149 ui::X11Window::DispatchEvent()
#29 0x73dcb0abf65d ui::X11Window::DispatchEvent()
#30 0x73dca22eaec2 ui::PlatformEventSource::DispatchEvent()
#31 0x73dc9606b03d ui::X11EventSource::OnEvent()
#32 0x73dc988eecb0 _ZN4base12ObserverListIN3x1113EventObserverELb0ELNS_28ObserverListReentrancyPolicyE1ENS_8internal24UncheckedObserverAdapterILN15partition_alloc8internal12RawPtrTraitsE1ELb0EEEE6NotifyIMS2_FvRKNS1_5EventEEJSC_EQsr3stdE9invocableITL0__PT_DpRKTL0_0_EEEvSI_DpRKT0_
#33 0x73dc988ee5ee x11::Connection::DispatchEvent()
#34 0x73dc988ee3f4 x11::Connection::ProcessNextEvent()
#35 0x73dc988ee185 x11::Connection::Dispatch()
#36 0x73dc96070b02 ui::(anonymous namespace)::XSourceDispatch()
#37 0x73dc9571ac44 g_main_context_dispatch
#38 0x73dc95770488 (/usr/lib/x86_64-linux-gnu/libglib-2.0.so.0.7200.4+0xab487)
#39 0x73dc957183e3 g_main_context_iteration
#40 0x73dcb058ec2d base::MessagePumpGlib::Run()
#41 0x73dcb04cf7fa base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::Run()
#42 0x73dcb045c1a6 base::RunLoop::Run()
#43 0x73dca7aa6c21 content::BrowserMainLoop::RunMainMessageLoop()
#44 0x73dca7aa9311 content::BrowserMainRunnerImpl::Run()
#45 0x73dca7aa2b60 content::BrowserMain()
#46 0x73dca8cc2cb0 content::RunBrowserProcessMain()
#47 0x73dca8cc5e03 content::ContentMainRunnerImpl::RunBrowser()
#48 0x73dca8cc51e9 content::ContentMainRunnerImpl::Run()
#49 0x73dca8cc14d4 content::RunContentProcess()
#50 0x73dca8cc16b2 content::ContentMain()
#51 0x650421aee07e ChromeMain
#52 0x73dc95029d90 (/usr/lib/x86_64-linux-gnu/libc.so.6+0x29d8f)
#53 0x73dc95029e40 __libc_start_main
#54 0x650421aedbca _start

[DanglingPtr](3/3) Later, the dangling raw_ptr was released at:

Stack trace:
#0 0x73dcb0567cf2 base::debug::CollectStackTrace()
#1 0x73dcb05435a1 base::debug::StackTrace::StackTrace()
#2 0x73dcb0570d8d base::allocator::(anonymous namespace)::DanglingRawPtrReleased<>()
#3 0x73dcb0707469 base::internal::RawPtrBackupRefImpl<>::ReleaseInternal()
#4 0x65042335eff0 containers::ContainersMenuModel::~ContainersMenuModel()
#5 0x65042335f05e containers::ContainersMenuModel::~ContainersMenuModel()
#6 0x650423250ec0 BraveNewTabButton::ShowContextMenuForViewImpl()
#7 0x73dca4ec8478 views::ContextMenuController::ShowContextMenuForView()
#8 0x73dca4fe6505 views::View::ShowContextMenu()
#9 0x73dca4fe3ebb views::View::ProcessMousePressed()
#10 0x73dca4fe3bd2 views::View::OnMouseEvent()
#11 0x73dcae3778ae ui::ScopedTargetHandler::OnEvent()
#12 0x73dcae36d16a ui::EventDispatcher::DispatchEvent()
#13 0x73dcae36c6b0 ui::EventDispatcher::ProcessEvent()
#14 0x73dcae36c2c7 ui::EventDispatcherDelegate::DispatchEventToTarget()
#15 0x73dcae36bf72 ui::EventDispatcherDelegate::DispatchEvent()
#16 0x73dca4ff8fad views::internal::RootView::OnMousePressed()
#17 0x73dca500b0af views::Widget::OnMouseEvent()
#18 0x73dca5064f74 views::DesktopNativeWidgetAura::OnMouseEvent()
#19 0x73dcae36d16a ui::EventDispatcher::DispatchEvent()
#20 0x73dcae36c6b0 ui::EventDispatcher::ProcessEvent()
#21 0x73dcae36c2c7 ui::EventDispatcherDelegate::DispatchEventToTarget()
#22 0x73dcae36bf72 ui::EventDispatcherDelegate::DispatchEvent()
#23 0x73dcae36f8d0 ui::EventProcessor::OnEventFromSource()
#24 0x73dca67f1cad aura::WindowTreeHostPlatform::DispatchEvent()
#25 0x73dca5068612 views::DesktopWindowTreeHostLinux::DispatchEvent()
#26 0x73dcae37a169 base::OnceCallback<>::Run()
#27 0x73dcae379f3f ui::DispatchEventFromNativeUiEvent()
#28 0x73dcb0abf55a ui::X11Window::DispatchUiEvent()
#29 0x73dcb0abf149 ui::X11Window::DispatchEvent()
#30 0x73dcb0abf65d ui::X11Window::DispatchEvent()
#31 0x73dca22eaec2 ui::PlatformEventSource::DispatchEvent()
#32 0x73dc9606b03d ui::X11EventSource::OnEvent()
#33 0x73dc988eecb0 _ZN4base12ObserverListIN3x1113EventObserverELb0ELNS_28ObserverListReentrancyPolicyE1ENS_8internal24UncheckedObserverAdapterILN15partition_alloc8internal12RawPtrTraitsE1ELb0EEEE6NotifyIMS2_FvRKNS1_5EventEEJSC_EQsr3stdE9invocableITL0__PT_DpRKTL0_0_EEEvSI_DpRKT0_
#34 0x73dc988ee5ee x11::Connection::DispatchEvent()
#35 0x73dc988ee3f4 x11::Connection::ProcessNextEvent()
#36 0x73dc988ee185 x11::Connection::Dispatch()
#37 0x73dc96070b02 ui::(anonymous namespace)::XSourceDispatch()
#38 0x73dc9571ac44 g_main_context_dispatch
#39 0x73dc95770488 (/usr/lib/x86_64-linux-gnu/libglib-2.0.so.0.7200.4+0xab487)
#40 0x73dc957183e3 g_main_context_iteration
#41 0x73dcb058ec2d base::MessagePumpGlib::Run()
#42 0x73dcb04cf7fa base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::Run()
#43 0x73dcb045c1a6 base::RunLoop::Run()
#44 0x73dca7aa6c21 content::BrowserMainLoop::RunMainMessageLoop()
#45 0x73dca7aa9311 content::BrowserMainRunnerImpl::Run()
#46 0x73dca7aa2b60 content::BrowserMain()
#47 0x73dca8cc2cb0 content::RunBrowserProcessMain()
#48 0x73dca8cc5e03 content::ContentMainRunnerImpl::RunBrowser()
#49 0x73dca8cc51e9 content::ContentMainRunnerImpl::Run()
#50 0x73dca8cc14d4 content::RunContentProcess()
#51 0x73dca8cc16b2 content::ContentMain()
#52 0x650421aee07e ChromeMain
#53 0x73dc95029d90 (/usr/lib/x86_64-linux-gnu/libc.so.6+0x29d8f)
#54 0x73dc95029e40 __libc_start_main
#55 0x650421aedbca _start
```

**Comment by sangwoo108** [comment]
thanks, will right on it
