### PR TITLE
[Android] Migrate private NTP to Leo tokens and fix VPN icon visibility

### LINKED ISSUE #53958: Fix `Brave VPN` icon color for both `Light` and `Dark` themes
### Description

Fix the `Brave VPN` icon color for both the `Light` and `Dark` themes.

### Steps to reproduce

1. Install and launch Brave `Beta` or `Nightly` build
2. Open new `Private` tab > *Observe*
3. Switch device to `Light` or `Dark` theme
4. Open new `Private` tab again > *Observe*

### Actual result

Fix the `Brave VPN` icon color for both the `Light` and `Dark` themes.

-------------------

| Dark theme | Light theme |
|:-:|:-:|
| Image | Image |

### Expected result

The `Brave VPN` icon must have the correct color in both `Light` and `Dark` themes.

----------------

### RC build:

| Dark theme | Light theme |
|:-:|:-:|
| Image | Image |

### Reproduces how often

Easily reproduced

### Brave version

Brave build: 1.89.118
Chromium: 146.0.7680.80 (Official Build) beta (64-bit)

### Device

- Galaxy Tab S8 / gts8wifixx-user 15 AP3A.240905.015.A2 release-keys
- Pixel 7 / panther_beta-user 17 CP21.260206.011.A1 release-keys

### Channel information

- [ ] release (stable)
- [x] beta
- [x] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

_No response_

### PR DESCRIPTION
**Pull request by SergeyZhukovsky**
I had to redo the NTP page as the nala icon for VPN was a very low contrast and the NTP page changed a lot, here is the figma link https://www.figma.com/design/jt7tV0UsU7XhJXR2B8807E/Private-and-Tor-Windows---Nala?node-id=257-14294&t=ls8AkDDge1FGGQRh-0
Changes:
- Drop Brave-local duplicates of ic_product_vpn / ic_antenna / ic_product_private_window so the private NTP renders the Leo (Nala) icons via resource_overlay; tint the inner icon layer to primitive_private_window_60 in IncognitoNewTabPageView so the designed purple still wins on the fixed-dark surface.
- Remove Brave-local primitive_private_window_5/10/20/60/80/90 from brave_colors.xml; references now resolve through Leo's primitive scale (same hex for _60/80/90; slight neutral shift for _5/10/20).
- Remove the runtime setBackgroundColor on the scroll view that was masking the gradient drawable defined in the layout XML.
- Switch the private-tab logo to ic_social_brave_release_favicon_- fullheight_color (Leo) and size in dp (42 phone, 56 tablet) to match Figma and to stop scaling with accessibility font size.
- Resize circle drawable to 32x32 (was 32x33), constrain inner icon via new_tab_page_incognito_icon_inner_size (20dp / 24dp tablet), and grow circle to 48dp on tablets.
- Introduce per-form-factor style aliases (IncognitoNtpTitle / SectionTitle / SectionDescription / Cta) under values/ + values-sw600dp/ so phones and tablets land on the right Leo typography ramp without per-TextView attributes.
- Delete the now-dead ntp_bg_incognito and incognito_modern_- primary_color color entries.

Resolves: https://github.com/brave/brave-browser/issues/53958

Screenshot_20260426_125141
Screenshot_20260426_125029

### CODE REVIEW

File: android/java/org/chromium/chrome/browser/ntp/IncognitoNewTabPageView.java [hunk 1]
```diff
@@ -89,6 +91,23 @@ protected void onFinishInflate() {
...
+        tintLayerListIcon(R.id.iv_first_icon, iconTint);
+        tintLayerListIcon(R.id.iv_second_icon, iconTint);
+        tintLayerListIcon(R.id.iv_third_icon, iconTint);
+    }
+
+    private void tintLayerListIcon(int imageViewId, int tint) {
+        ImageView imageView = findViewById(imageViewId);
+        if (imageView == null) return;
+        Drawable drawable = imageView.getDrawable();
+        if (!(drawable instanceof LayerDrawable)) return;
```
Comment (netzenbot) [inline android/java/org/chromium/chrome/browser/ntp/IncognitoNewTabPageView.java:107]: nit: The icon tint could be set directly in the layer-list XMLs (`android:tint="@color/primitive_private_window_60"` on each inner `<item>`) rather than programmatically. Per [AND-034](https://github.com/brave/brave-core/tree/master/docs/best-practices/android.md#AND-034), prefer XML color resources over patching Java code for theming. The `drawable.mutate()` usage is correct, but an XML-only approach avoids the runtime overhead and keeps all styling declarative.

**Review by AlexeyBarabash — APPROVED** [review]
LGTM

File: android/java/org/chromium/chrome/browser/ntp/IncognitoNewTabPageView.java (hunk 1 above)
Comment (SergeyZhukovsky) [reply android/java/org/chromium/chrome/browser/ntp/IncognitoNewTabPageView.java:107]: Tried this — `android:tint` on `<item>` in a `layer-list` isn't part of the `LayerDrawableItem` styleable

**Review by mkarolin — APPROVED** [review]
`strings`++
