### PR TITLE
Don't use virtual url for brave/chrome

### LINKED ISSUE #22872: brave://wallet redirects to chrome://wallet
## Description 
`brave://wallet` redirects to `chrome://wallet` 

## Steps to reproduce 

   1. Go to `brave://wallet`
  
## Actual result 
Redirected to `chrome://wallet`

## Expected result
Opening `brave://wallet`

## Issue reproduces how often 
Easily reproduced

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? yes
- Can you reproduce this issue with the current Play Store Beta version? yes
- Can you reproduce this issue with the current Play Store Nightly version? yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone, OnePlus 7 Pro
   - Android version: 11
   
## Brave version
Brave 1.38.113, Chromium 101.0.4951.61

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

### LINKED ISSUE #34983: Internal pages showing `chrome://`. They should always show `brave://`
## Description

Example screenshot below. Note how it says `chrome://`. It should say `brave://`. 

IMG_0082

### LINKED ISSUE #53508: chrome vs brave scheme should be display only
We have had an endless stream of issues related to brave vs chrome scheme checks and just recently ran into what looks like a lot more of them on android. The only way to safely resolve this is to make `brave` scheme display only and never part of the actual url. This would also be similar to `about://flags` where `about` gets rewritten to `chrome` without becoming the virtual url. Using `brave` as the virtual url is just too risky in terms of security and I think we need to accept that we may have some display regressions to fix this problem.

### LINKED ISSUE #53549: brave:// -> chrome:// rewrite causes many upstream checks to fail to properly recognize the pages as chrome://
We currently change brave -> chrome scheme in a way that results in the real and virtual url being different. Because some checks use the virtual url and some use the real url, this results in some of them failing to correctly identify the pages as `chrome://`. `brave://`

### PR DESCRIPTION
**Pull request by bridiver**
Use `brave://` for display purposes only. Internally the scheme should always be `chrome://`

Resolves https://github.com/brave/brave-browser/issues/53549
Resolves https://github.com/brave/brave-browser/issues/34983
Resolves https://github.com/brave/brave-browser/issues/22872
Resolves https://github.com/brave/brave-browser/issues/53508

QA:
Verify chrome urls direct to brave
Verify brave urls are not added to history
Test plan from https://github.com/brave/brave-core/pull/1196 partially works, but use brave://about/ to check navigating from one brave "host" to another
check that session restore with brave:// pages works correctly.

### CODE REVIEW

File: android/java/org/chromium/chrome/browser/BraveRewardsNativeWorker.java [hunk 1]
```diff
@@ -121,12 +121,8 @@ public void removePublisherObserver(PublisherObserver observer) {
     }
 
     public void onNotifyFrontTabUrlChanged(int tabId, String url) {
-        // Check both chrome:// and brave:// schemes. brave:// URLs (e.g.
-        // brave://version) are not recognized by the publisher lookup and
-        // would leave a stale verified-publisher checkmark from a previous tab.
         boolean internalUrl =
-                url.startsWith(UrlConstants.CHROME_SCHEME)
-                        || url.startsWith(BraveUrlConstants.BRAVE_SCHEME);
+                url.startsWith(UrlConstants.CHROME_SCHEME);
```
Comment (bridiver) [inline android/java/org/chromium/chrome/browser/BraveRewardsNativeWorker.java]: cc @yrliou

**Comment by fallaciousreasoning** [comment]
This looks great

File: android/java/org/chromium/chrome/browser/BraveRewardsNativeWorker.java (hunk 1 above)
Comment (bridiver) [reply android/java/org/chromium/chrome/browser/BraveRewardsNativeWorker.java]: this is fixed now in terms of display, but no idea if that addresses the issue here. We definitely can't use brave as the real or virtual url because that messes up important checks in android

**Review by fallaciousreasoning — APPROVED** [review]

File: browser/ui/toolbar/brave_location_bar_model_delegate.cc [hunk 2]
```diff
@@ -100,7 +97,7 @@ const gfx::VectorIcon* BraveLocationBarModelDelegate::GetVectorIconOverride()
 
   // Defer to the Chromium implementation first.
   const gfx::VectorIcon* parent_icon =
-      BrowserLocationBarModelDelegate::GetVectorIconOverride();
+      ChromeLocationBarModelDelegate::GetVectorIconOverride();
```
Comment (fallaciousreasoning) [inline browser/ui/toolbar/brave_location_bar_model_delegate.cc:100]: haven't checked the code but could this return icons in more cases than the base class?

Comment (bridiver) [reply browser/ui/toolbar/brave_location_bar_model_delegate.cc:100]: It's not the base class, Browser subclasses Chrome

Comment (bridiver) [reply browser/ui/toolbar/brave_location_bar_model_delegate.cc:100]: The only thing different about Browser is that it adds a dependency on tab strip that isn't allowed on android which is why I inverted this relationship

File: chromium_src/chrome/browser/ui/android/toolbar/location_bar_model_android.h [hunk 3]
```diff
@@ -0,0 +1,17 @@
...
+ * You can obtain one at https://mozilla.org/MPL/2.0/. */
+
+#ifndef BRAVE_CHROMIUM_SRC_CHROME_BROWSER_UI_ANDROID_TOOLBAR_LOCATION_BAR_MODEL_ANDROID_H_
+#define BRAVE_CHROMIUM_SRC_CHROME_BROWSER_UI_ANDROID_TOOLBAR_LOCATION_BAR_MODEL_ANDROID_H_
+
+#include "brave/browser/ui/toolbar/brave_location_bar_model_delegate.h"
+
+#define ChromeLocationBarModelDelegate BraveLocationBarModelDelegate
+
+#include "src/chrome/browser/ui/android/toolbar/location_bar_model_android.h"  // IWYU pragma: export
```
Comment (goodov) [inline chromium_src/chrome/browser/ui/android/toolbar/location_bar_model_android.h]: is this based on an old branch? we don't use `src/` anymore.

File: patches/components-url_formatter-url_fixer.cc.patch [hunk 4]
```diff
@@ -0,0 +1,53 @@
+diff --git a/components/url_formatter/url_fixer.cc b/components/url_formatter/url_fixer.cc
+index 553623e61699757d520699eeeb9405b756872d8f..c4bbd6327970c642532eb02797581babf12839f5 100644
+--- a/components/url_formatter/url_fixer.cc
++++ b/components/url_formatter/url_fixer.cc
+@@ -38,6 +38,7 @@ namespace {
+ 
+ // Hardcode these constants to avoid dependences on //chrome and //content.
+ const char kChromeUIScheme[] = "chrome";
++const char kBraveUIScheme[] = "brave";
```
Comment (goodov) [inline patches/components-url_formatter-url_fixer.cc.patch]: I see it's added here, but I don't see it's removed from `content::`. should it be removed?

File: browser/ui/toolbar/brave_location_bar_model_delegate.cc [hunk 5]
```diff
@@ -59,8 +55,9 @@ BraveLocationBarModelDelegate::FormattedStringWithEquivalentMeaning(
 bool BraveLocationBarModelDelegate::GetURL(GURL* url) const {
 #if !BUILDFLAG(IS_ANDROID)
   if (base::FeatureList::IsEnabled(tabs::kBraveSharedPinnedTabs) &&
-      tab_strip_model_->profile()->GetPrefs()->GetBoolean(
-          brave_tabs::kSharedPinnedTab)) {
+      Profile::FromBrowserContext(GetActiveWebContents()->GetBrowserContext())
+          ->GetPrefs()
+          ->GetBoolean(brave_tabs::kSharedPinnedTab)) {
     content::NavigationEntry* entry = GetNavigationEntry();
     if (entry && entry->IsInitialEntry()) {
```
Comment (netzenbot) [inline browser/ui/toolbar/brave_location_bar_model_delegate.cc:63]: The new code `Profile::FromBrowserContext(GetActiveWebContents()->GetBrowserContext())` will crash if `GetActiveWebContents()` returns nullptr (e.g., no active tab). The original code used `tab_strip_model_->profile()` which didn't have this issue. Consider null-checking first, similar to line 122 which already does `if (!web_contents)`. [best practice](https://github.com/brave/brave-core/tree/master/docs/best-practices/coding-standards-memory.md#CSM-029)

File: chromium_src/chrome/browser/ui/android/toolbar/location_bar_model_android.h (hunk 3 above)
Comment (bridiver) [reply chromium_src/chrome/browser/ui/android/toolbar/location_bar_model_android.h]: Oops, will fix

File: patches/components-url_formatter-url_fixer.cc.patch (hunk 4 above)
Comment (bridiver) [reply patches/components-url_formatter-url_fixer.cc.patch]: It's in a lot of places just like chrome. I didn't want to add a content dependency here so just hard coded to match chrome

Comment (bridiver) [reply patches/components-url_formatter-url_fixer.cc.patch]: oh, you're asking generally, not because of this specific change? I think it's still needed for some cases like converting back to brave for the UI, but I'll double check

Comment (bridiver) [reply patches/components-url_formatter-url_fixer.cc.patch]: still used in autocomplete classifier (which may or may not still be needed) and also in `BraveBrowser::UpdateTargetURL` which also may or may not be needed. I'll check those

File: build.log
Comment (simoarpe) [inline build.log:1]: You probably don't want to include the `build.log` here.

File: rewrite/components/url_formatter/url_fixer.cc.toml [hunk 6]
```diff
@@ -0,0 +1,44 @@
+# Copyright (c) 2025 The Brave Authors. All rights reserved.
```
Comment (simoarpe) [inline rewrite/components/url_formatter/url_fixer.cc.toml]:
```suggestion
# Copyright (c) 2026 The Brave Authors. All rights reserved.
```

File: browser/ui/toolbar/brave_location_bar_model_delegate.cc [hunk 7]
```diff
@@ -58,16 +53,19 @@ BraveLocationBarModelDelegate::FormattedStringWithEquivalentMeaning(
 
 bool BraveLocationBarModelDelegate::GetURL(GURL* url) const {
 #if !BUILDFLAG(IS_ANDROID)
+  auto* active_web_contents = GetActiveWebContents();
   if (base::FeatureList::IsEnabled(tabs::kBraveSharedPinnedTabs) &&
-      tab_strip_model_->profile()->GetPrefs()->GetBoolean(
-          brave_tabs::kSharedPinnedTab)) {
+      active_web_contents &&
```
Comment (netzenbot) [inline browser/ui/toolbar/brave_location_bar_model_delegate.cc:58]: `Profile::FromBrowserContext(active_web_contents->GetBrowserContext())` can return nullptr, and dereferencing it directly with `->GetPrefs()` will crash if the browser context isn't a Profile. Null-check the result before use, e.g. `if (auto* profile = Profile::FromBrowserContext(...)) { ... }`. [best practice](https://github.com/brave/brave-core/tree/master/docs/best-practices/coding-standards-memory.md#CSM-029)

File: chromium_src/chrome/browser/ui/android/toolbar/location_bar_model_android.h [hunk 8]
```diff
@@ -0,0 +1,17 @@
+/* Copyright (c) 2025 The Brave Authors. All rights reserved.
```
Comment (netzenbot) [inline chromium_src/chrome/browser/ui/android/toolbar/location_bar_model_android.h]: nit: Copyright year should be 2026 for new files (currently shows 2025). [best practice](https://github.com/brave/brave-core/tree/master/docs/best-practices/coding-standards.md#CS-012)

File: patches/components-url_formatter-url_fixer.cc.patch [hunk 9]
```diff
@@ -0,0 +1,53 @@
+diff --git a/components/url_formatter/url_fixer.cc b/components/url_formatter/url_fixer.cc
```
Comment (netzenbot) [inline patches/components-url_formatter-url_fixer.cc.patch]: This PR adds both `patches/components-url_formatter-url_fixer.cc.patch` (6 hunks) and `rewrite/components/url_formatter/url_fixer.cc.toml` (3 substitutions) for the same file. Is the patch intended to be kept alongside the toml, or is it a leftover? If the toml approach can cover all the changes, consider migrating the remaining patch hunks to additional toml substitutions and removing the patch file entirely. [best practice](https://github.com/brave/brave-core/tree/master/docs/best-practices/chromium-src-overrides.md#CSRC-004)

File: browser/ui/toolbar/brave_location_bar_model_delegate.cc (hunk 7 above)
Comment (bridiver) [reply browser/ui/toolbar/brave_location_bar_model_delegate.cc:58]: It only return nullptr if BrowserContext is nullptr, but the BrowserContext for WebContents can never be nullptr  so this is not problem here.

File: patches/components-url_formatter-url_fixer.cc.patch (hunk 9 above)
Comment (fallaciousreasoning) [reply patches/components-url_formatter-url_fixer.cc.patch]: This is incorrect - the patch file is generated from the toml. cc @bbondy

File: patches/components-url_formatter-url_fixer.cc.patch (hunk 4 above)
Comment (bridiver) [reply patches/components-url_formatter-url_fixer.cc.patch]: `UpdateTargetURL` should stay as is since it's about correct display when hovering. Autocomplete classifier should also continue to use `content::kBraveUIScheme`

File: patches/components-url_formatter-url_fixer.cc.patch (hunk 9 above)
Comment (bridiver) [reply patches/components-url_formatter-url_fixer.cc.patch]: Yeah it seems to be confused here, there is always a patch associated with plaster files

File: patches/components-url_formatter-url_fixer.cc.patch (hunk 4 above)
Comment (goodov) [reply patches/components-url_formatter-url_fixer.cc.patch]: should we rename `kBraveUIScheme` to highlight that it shouldn't be used for navigations? The way this var exists is still very tempting to use it instead of the chrome scheme.

`kBraveUISchemeNotForNavigation`

**Review by goodov — COMMENTED** [review]
please check that session restore with `brave://` pages works correctly.

**Comment by bridiver** [comment]
> please check that session restore with `brave://` pages works correctly.

verified, but I'll add to the QA list anyway

**Review by netzenbot — APPROVED** [review]

File: chromium_src/chrome/browser/ui/android/toolbar/DEPS [hunk 10]
```diff
@@ -0,0 +1,3 @@
+include_rules = [
+ "+src/chrome/browser/ui/android/toolbar/location_bar_model_android.h",
```
Comment (goodov) [inline chromium_src/chrome/browser/ui/android/toolbar/DEPS]: `src/` again

**Review by goodov — APPROVED** [review]
lgtm overall

File: patches/content-browser-renderer_host-navigation_controller_impl.cc.patch [hunk 11]
```diff
@@ -1,25 +1,12 @@
...
-index ed4e4fe82902a072e99071c918f34b29ab407635..00a7f135a38097b755f1a7e64bbf8cbe1c861bb5 100644
+index ed4e4fe82902a072e99071c918f34b29ab407635..712458113109f3e9e4a3e25939fd07420294d5d0 100644
 --- a/content/browser/renderer_host/navigation_controller_impl.cc
 +++ b/content/browser/renderer_host/navigation_controller_impl.cc
-@@ -4029,16 +4029,17 @@ base::WeakPtr<NavigationHandle> NavigationControllerImpl::NavigateWithoutEntry(
-   // Note: we intentionally leave the pending entry in place for renderer debug
-   // URLs, unlike the cases below where we clear it if the navigation doesn't
-   // proceed.
--  if (blink::IsRendererDebugURL(params.url)) {
-+  const GURL url = params.url.SchemeIs(url::kJavaScriptScheme) ? params.url : pending_entry_->GetURL();
```
Comment (bridiver) [inline patches/content-browser-renderer_host-navigation_controller_impl.cc.patch:10]: I should probably remove this in a separate PR, I'll split it out

File: patches/content-browser-renderer_host-navigation_controller_impl.cc.patch [hunk 12]
```diff
@@ -1,25 +1,12 @@
...
- 
--    HandleRendererDebugURL(node, params.url);
-+    HandleRendererDebugURL(node, url);
-     return nullptr;
-   }
+@@ -452,6 +452,7 @@ void RewriteUrlForNavigation(const GURL& original_url,
+   *url_to_load = *virtual_url = original_url;
+   BrowserURLHandlerImpl::GetInstance()->RewriteURLIfNecessary(
+       url_to_load, browser_context, reverse_on_redirect);
++  MaybeRewriteVirtualURL(url_to_load, virtual_url);
```
Comment (bridiver) [inline patches/content-browser-renderer_host-navigation_controller_impl.cc.patch]: need to convert this to plaster

File: chromium_src/chrome/browser/ui/android/toolbar/DEPS (hunk 10 above)
Comment (bridiver) [reply chromium_src/chrome/browser/ui/android/toolbar/DEPS]: this is actually not needed, I think it was only triggering because I had src in the override

**Review by yrliou — APPROVED** [review]
wallet-core++

**Comment by bridiver** [comment]
> ### Possible Issues
> 1. **`MaybeRewriteVirtualURL` is overly broad**: In `chromium_src/content/browser/renderer_host/navigation_controller_impl.cc`, the function sets `virtual_url = url_to_load` for _all_ `chrome://` URLs, not just those that were rewritten from `brave://`. This could interfere with Chromium's own virtual URL handling for chrome:// pages that intentionally have different virtual URLs.

Looking into this

> 2. **Test observer rewriting is fragile**: The `test_navigation_observer.cc` override rewrites _any_ `brave://` URL passed as an expected URL to `chrome://`, which modifies the state of the `GURL*` pointer passed in. This could cause unexpected side effects in tests that reuse the URL object after the observer check.

Agreed, but I don't see a good way around this right now other than changing every single test. Maybe in a follow-up

> 3. **`HandleChromeAboutAndChromeSyncRewrite` now returns `true` after rewriting brave→chrome**: The added `return true;` on the brave→chrome rewrite path means it skips the subsequent Chromium `HandleChromeAboutAndChromeSyncRewrite` call. This could skip important logic that Chromium's handler performs for certain URLs.

Not sure this is actually the case after spending time looking at how the return value is used, but I'll double check

> 4. **Browser test `TestWalletPageRoute` was deleted entirely** rather than being updated to test the new behavior. This reduces test coverage for wallet page URL routing on Android.

This test was for a wallet specific workaround and now all android urls work correctly so it's no longer needed

> 5. **Missing `BraveLocationBarModelDelegate` constructor forwarding**: The `BraveLocationBarModelDelegate` now has a default constructor, but `ChromeLocationBarModelDelegate` may require initialization parameters on certain platforms. The Android override in `location_bar_model_android.h` substitutes `ChromeLocationBarModelDelegate` with `BraveLocationBarModelDelegate`, but the construction site may pass arguments that the default constructor doesn't accept.

Not relevant
 
> ### Security Hotspots
> 1. **Extension kill URL check removed** (`chrome-browser-extensions-extension_tab_util.cc.patch` deleted): The patch that added `brave://` scheme checking to `ExtensionTabUtil::IsKillURL` is removed. If `brave://` URLs can still reach this code path before being rewritten, potentially dangerous URLs might not be caught by the kill URL check.
> 2. **WebUI factory no longer checks `kBraveUIScheme`** (`brave_web_ui_controller_factory.cc`): If any code path can reach the factory with an unrewritten `brave://` URL, it would return `nullptr` instead of creating the appropriate WebUI controller, potentially causing navigation failures or unexpected behavior.

These changes are intentional, if anything there should be a CHECK here if the url is ever brave and I might add that instead of outright removing some of these

File: patches/content-browser-renderer_host-navigation_controller_impl.cc.patch (hunk 11 above)
Comment (bridiver) [reply patches/content-browser-renderer_host-navigation_controller_impl.cc.patch:10]: actually this is related to brave://crash so it makes sense to remove it here

File: patches/third_party-blink-renderer-core-dom-document.cc.patch [hunk 13]
```diff
@@ -0,0 +1,28 @@
+diff --git a/third_party/blink/renderer/core/dom/document.cc b/third_party/blink/renderer/core/dom/document.cc
+index dde7e8993cb8e59d0cbc1a15fffaedb8b0a26688..874c34ae74db95ed367524d76bb7ff352e136d81 100644
+--- a/third_party/blink/renderer/core/dom/document.cc
++++ b/third_party/blink/renderer/core/dom/document.cc
+@@ -7561,6 +7561,15 @@ KURL Document::CompleteURL(
+   return CompleteURLWithOverride(url.ToString(), base_url_, preload_status);
+ }
+ 
++KURL MakeChromeURL(const KURL& brave_url) {
```
Comment (bridiver) [inline patches/third_party-blink-renderer-core-dom-document.cc.patch]: temporary patch for testing

File: chromium_src/content/public/test/test_navigation_observer.cc [hunk 14]
```diff
@@ -0,0 +1,33 @@
...
+ * License, v. 2.0. If a copy of the MPL was not distributed with this file,
+ * You can obtain one at https://mozilla.org/MPL/2.0/. */
+
+#include "content/public/browser/browser_url_handler.h"
+#include "content/public/common/url_constants.h"
+#include "url/gurl.h"
+
+namespace {
+
+GURL* RewriteExpectedURLBraveToChrome(GURL* url) {
```
Comment (bridiver) [inline chromium_src/content/public/test/test_navigation_observer.cc:12]: I'm going to add a warning to this because it was only added for backwards compat

Comment (bridiver) [reply chromium_src/content/public/test/test_navigation_observer.cc:12]: nvm, this is unavoidable when we want to navigate to `brave://` for testing

**Comment by brave-browser-releases** [comment]
Released in [v1.90.51](https://github.com/brave/brave-browser/releases/tag/v1.90.51)
