### PR TITLE
[Shields UI] Fix blocked scripts details button not visible

### LINKED ISSUE #54693: [Shields UI] "carat-right" button for `Block scripts` setting is not shown when enabled immediately
### Description

Found while testing https://github.com/brave/brave-browser/issues/53111.  If `Block scripts` toggle enabled, the "carat-right" button is not shown which prevents user to view  blocked scripts.  Was able to view the scripts when advanced options panel was collapsed and expanded

### Steps to reproduce

1. Install 1.90.x
2. launch Brave
3. open a website
4. open Shields panel -->Advanced options
5. enable `Block scripts` toggle

### Actual result

` "carat-right" button` is not loaded immediately (eg. similar to Block trackers & ads)

https://github.com/user-attachments/assets/c214d388-8195-4292-866e-36a7c9639faa

### Expected result

 "carat-right" button should be visible immediately

Image

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

Brave | 1.90.106 Chromium: 147.0.7727.102 (Official Build) beta (64-bit)
-- | --
Revision | c6d6a9660a9c6017b69985b737f2dd56e7b49b2f
OS | Windows 11 Version 25H2 (Build 26200.8037)

### Channel information

- [ ] release (stable)
- [x] beta
- [ ] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

@rebron @zenparsing 
cc: @brave/qa-team

### PR DESCRIPTION
**Pull request by zenparsing**
Resolves https://github.com/brave/brave-browser/issues/54693

### CODE REVIEW

File: components/brave_shields/resources/panel_new/components/advanced_settings.tsx [hunk 1]
```diff
@@ -216,9 +219,7 @@ function BlockScriptsControls(props: { showDetails: () => void }) {
       </div>
       <Button
         onClick={props.showDetails}
-        isDisabled={
-          !isNoscriptEnabled || !hasBlockedOrAllowed || scriptsBlockedEnforced
-        }
+        isDisabled={!detailsEnabled}
```
Comment (zenparsing) [inline components/brave_shields/resources/panel_new/components/advanced_settings.tsx:222]: Previously we were supplying a `null` value (instead of `false`) to this prop, which was not triggering a reset of the element's "disabled" property.

**Review by petemill — APPROVED** [review]

**Review by fallaciousreasoning — APPROVED** [review]

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.91.100 Chromium: 147.0.7727.117 (Official Build) nightly (64-bit)
-- | --
Revision | 7dad4225d72ee79aa5a708b82b145d969a80fbba
OS | Windows 11 Version 25H2 (Build 26200.8037)
```

Verified the PR using STR from issue description https://github.com/brave/brave-browser/issues/54693#issue-4284655630

- Confirmed when `Block scripts` toggle enabled, carat-right button to show details button enabled. 
- Confirmed when clicked the button, blocked scripts details page shown as expected



https://github.com/user-attachments/assets/3c5c0f43-d0c0-4e86-b627-46da6d42041d
