### PR TITLE
Scroll to new tab when adding tabs

### LINKED ISSUE #53312: Vertical tabs - When opening a new tab from link via right click and it's the last tab in a scrollable list, there's no indication the tab opened
### Description

Reported here
https://bravesoftware.slack.com/archives/CKNHM4RTK/p1772544284117229

https://github.com/user-attachments/assets/5c4b65ea-d9a9-4566-8b76-c0ccd849e523

### Steps to reproduce

1. Have vertical tabs enabled
2. Open many tabs
3. From the last tab in the list, navigate to a website like the verge
4. There, open a link in a new tab via right click or middle click
5. You'll see that there's no indication that there's now a new tab underneath the one you had

### Actual result

See video attached

### Expected result

Ideally, the list of tabs would auto scroll to show the new tabs created below that previously last tab

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

1.89.78 Chromium: 145.0.7632.120 (Official Build) nightly (arm64) 

### Channel information

- [ ] release (stable)
- [ ] beta
- [x] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

_No response_

### PR DESCRIPTION
**Pull request by sangwoo108**
When adding background tabs, scroll to the new tab to be visible in the viewport. Otherwise, users will not notice the tab was created or not.

Resolves https://github.com/brave/brave-browser/issues/53312

### CODE REVIEW

File: browser/ui/views/tabs/brave_tab_container.cc [hunk 1]
```diff
@@ -304,6 +304,18 @@ bool BraveTabContainer::ShouldTabBeVisible(const Tab* tab) const {
   return TabContainerImpl::ShouldTabBeVisible(tab);
 }
 
+std::vector<Tab*> BraveTabContainer::AddTabs(
+    std::vector<TabInsertionParams> tabs_params) {
+  std::vector<Tab*> added_tabs =
+      TabContainerImpl::AddTabs(std::move(tabs_params));
+  if (GetScrollDirection()) {
```
Comment (simonhong) [inline browser/ui/views/tabs/brave_tab_container.cc:311]: don't need to filter with vertical tab? linked issue title for vertical tab.

Comment (simonhong) [reply browser/ui/views/tabs/brave_tab_container.cc:311]: also let's have a test that covers this change.

Comment (sangwoo108) [reply browser/ui/views/tabs/brave_tab_container.cc:311]: > don't need to filter with vertical tab? linked issue title for vertical tab.

We don't need to. we have horizontal scrollable tab strip too.

Comment (sangwoo108) [reply browser/ui/views/tabs/brave_tab_container.cc:311]: Thanks, added a test

**Review by simonhong — APPROVED** [review]
++
