### PR TITLE
Fix trezor bridge tests intermittent failures

### LINKED ISSUE #54561: Test failure:  Device is busy. Device is busy
Greetings human!

Bad news. ` Device is busy. Device is busy` [failed on browser macos arm64 beta v1.90.106](https://ci.brave.com/job/brave-browser-build-macos-arm64/6252/testReport/junit/(root)/%20Device%20is%20busy/test_javascript____Device_is_busy).
<details>
<summary>Stack trace</summary>

```
Error: expect(received).resolves.toStrictEqual(expected) // deep equality
Expected: 1
Received: 0
    at Object.toStrictEqual (/Users/jenkins/jenkins/workspace/brave-browser-build-macos-arm64-beta/src/brave/node_modules/expect/build/index.js:194:22)
    at Object.<anonymous> (/Users/jenkins/jenkins/workspace/brave-browser-build-macos-arm64-beta/src/brave/components/brave_wallet_ui/common/hardware/trezor/trezor_bridge_keyring.test.ts:312:34)
    at Promise.then.completed (/Users/jenkins/jenkins/workspace/brave-browser-build-macos-arm64-beta/src/brave/node_modules/jest-circus/build/utils.js:333:28)
    at new Promise (<anonymous>)
    at callAsyncCircusFn (/Users/jenkins/jenkins/workspace/brave-browser-build-macos-arm64-beta/src/brave/node_modules/jest-circus/build/utils.js:259:10)
    at _callCircusTest (/Users/jenkins/jenkins/workspace/brave-browser-build-macos-arm64-beta/src/brave/node_modules/jest-circus/build/run.js:277:40)
    at processTicksAndRejections (node:internal/process/task_queues:104:5)
    at _runTest (/Users/jenkins/jenkins/workspace/brave-browser-build-macos-arm64-beta/src/brave/node_modules/jest-circus/build/run.js:209:3)
    at _runTestsForDescribeBlock (/Users/jenkins/jenkins/workspace/brave-browser-build-macos-arm64-beta/src/brave/node_modules/jest-circus/build/run.js:97:9)
    at run (/Users/jenkins/jenkins/workspace/brave-browser-build-macos-arm64-beta/src/brave/node_modules/jest-circus/build/run.js:31:3)
    at runAndTransformResultsToJestFormat (/Users/jenkins/jenkins/workspace/brave-browser-build-macos-arm64-beta/src/brave/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapterInit.js:135:21)
    at jestAdapter (/Users/jenkins/jenkins/workspace/brave-browser-build-macos-arm64-beta/src/brave/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapter.js:70:21)
    at runTestInternal (/Users/jenkins/jenkins/workspace/brave-browser-build-macos-arm64-beta/src/brave/node_modules/jest-runner/build/runTest.js:411:16)
    at runTest (/Users/jenkins/jenkins/workspace/brave-browser-build-macos-arm64-beta/src/brave/node_modules/jest-runner/build/runTest.js:499:34)
    at Object.worker (/Users/jenkins/jenkins/workspace/brave-browser-build-macos-arm64-beta/src/brave/node_modules/jest-runner/build/testWorker.js:133:12)
null
```
</details>
<details>
<summary>Previous issues</summary>

* #49321

[Find all](https://github.com/brave/brave-browser/issues?q=type%3Aissue+label%3Abot%2Ftype%2Ftest+in%3Atitle+%22Test+failure%3A+Device+is+busy.+Device+is+busy%22)
</details>

### LINKED ISSUE #54562: Test failure:  Extract accounts from locked device. Extract accounts from locked device
Greetings human!

Bad news. ` Extract accounts from locked device. Extract accounts from locked device` [failed on browser macos arm64 beta v1.90.106](https://ci.brave.com/job/brave-browser-build-macos-arm64/6252/testReport/junit/(root)/%20Extract%20accounts%20from%20locked%20device/test_javascript____Extract_accounts_from_locked_device).
<details>
<summary>Stack trace</summary>

```
Error: expect(received).resolves.toStrictEqual(expected) // deep equality
- Expected  - 2
+ Received  + 2
  Object {
-   "code": "",
-   "error": "braveWalletUnlockError",
+   "code": 0,
+   "error": "braveWalletBridgeNotReady",
    "success": false,
  }
    at Object.toStrictEqual (/Users/jenkins/jenkins/workspace/brave-browser-build-macos-arm64-beta/src/brave/node_modules/expect/build/index.js:194:22)
    at Object.<anonymous> (/Users/jenkins/jenkins/workspace/brave-browser-build-macos-arm64-beta/src/brave/components/brave_wallet_ui/common/hardware/trezor/trezor_bridge_keyring.test.ts:352:14)
    at Promise.then.completed (/Users/jenkins/jenkins/workspace/brave-browser-build-macos-arm64-beta/src/brave/node_modules/jest-circus/build/utils.js:333:28)
    at new Promise (<anonymous>)
    at callAsyncCircusFn (/Users/jenkins/jenkins/workspace/brave-browser-build-macos-arm64-beta/src/brave/node_modules/jest-circus/build/utils.js:259:10)
    at _callCircusTest (/Users/jenkins/jenkins/workspace/brave-browser-build-macos-arm64-beta/src/brave/node_modules/jest-circus/build/run.js:277:40)
    at processTicksAndRejections (node:internal/process/task_queues:104:5)
    at _runTest (/Users/jenkins/jenkins/workspace/brave-browser-build-macos-arm64-beta/src/brave/node_modules/jest-circus/build/run.js:209:3)
    at _runTestsForDescribeBlock (/Users/jenkins/jenkins/workspace/brave-browser-build-macos-arm64-beta/src/brave/node_modules/jest-circus/build/run.js:97:9)
    at run (/Users/jenkins/jenkins/workspace/brave-browser-build-macos-arm64-beta/src/brave/node_modules/jest-circus/build/run.js:31:3)
    at runAndTransformResultsToJestFormat (/Users/jenkins/jenkins/workspace/brave-browser-build-macos-arm64-beta/src/brave/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapterInit.js:135:21)
    at jestAdapter (/Users/jenkins/jenkins/workspace/brave-browser-build-macos-arm64-beta/src/brave/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapter.js:70:21)
    at runTestInternal (/Users/jenkins/jenkins/workspace/brave-browser-build-macos-arm64-beta/src/brave/node_modules/jest-runner/build/runTest.js:411:16)
    at runTest (/Users/jenkins/jenkins/workspace/brave-browser-build-macos-arm64-beta/src/brave/node_modules/jest-runner/build/runTest.js:499:34)
    at Object.worker (/Users/jenkins/jenkins/workspace/brave-browser-build-macos-arm64-beta/src/brave/node_modules/jest-runner/build/testWorker.js:133:12)
null
```
</details>
<details>
<summary>Previous issues</summary>

* #49322

[Find all](https://github.com/brave/brave-browser/issues?q=type%3Aissue+label%3Abot%2Ftype%2Ftest+in%3Atitle+%22Test+failure%3A+Extract+accounts+from+locked+device.+Extract+accounts+from+locked+device%22)
</details>

### LINKED ISSUE #54563: Test failure:  Extract accounts from unlocked device returned success. Extract accounts from unlocked device returned success
Greetings human!

Bad news. ` Extract accounts from unlocked device returned success. Extract accounts from unlocked device returned success` [failed on browser macos arm64 beta v1.90.106](https://ci.brave.com/job/brave-browser-build-macos-arm64/6252/testReport/junit/(root)/%20Extract%20accounts%20from%20unlocked%20device%20returned%20success/test_javascript____Extract_accounts_from_unlocked_device_returned_success).
<details>
<summary>Stack trace</summary>

```
Error: expect(received).resolves.toStrictEqual(expected) // deep equality
- Expected  - 11
+ Received  +  3
  Object {
-   "accounts": Array [
-     Object {
-       "address": "0x2F015C60E0be116B1f0CD534704Db9c92118FB6A",
-       "derivationPath": "m/44'/60'/0'/0/0",
-     },
-     Object {
-       "address": "0x8e926dF9926746ba352F4d479Fb5DE47382e83bE",
-       "derivationPath": "m/44'/60'/0'/0/1",
-     },
-   ],
-   "success": true,
+   "code": 0,
+   "error": "braveWalletBridgeNotReady",
+   "success": false,
  }
    at Object.toStrictEqual (/Users/jenkins/jenkins/workspace/brave-browser-build-macos-arm64-beta/src/brave/node_modules/expect/build/index.js:194:22)
    at Object.<anonymous> (/Users/jenkins/jenkins/workspace/brave-browser-build-macos-arm64-beta/src/brave/components/brave_wallet_ui/common/hardware/trezor/trezor_bridge_keyring.test.ts:403:14)
    at Promise.then.completed (/Users/jenkins/jenkins/workspace/brave-browser-build-macos-arm64-beta/src/brave/node_modules/jest-circus/build/utils.js:333:28)
    at new Promise (<anonymous>)
    at callAsyncCircusFn (/Users/jenkins/jenkins/workspace/brave-browser-build-macos-arm64-beta/src/brave/node_modules/jest-circus/build/utils.js:259:10)
    at _callCircusTest (/Users/jenkins/jenkins/workspace/brave-browser-build-macos-arm64-beta/src/brave/node_modules/jest-circus/build/run.js:277:40)
    at processTicksAndRejections (node:internal/process/task_queues:104:5)
    at _runTest (/Users/jenkins/jenkins/workspace/brave-browser-build-macos-arm64-beta/src/brave/node_modules/jest-circus/build/run.js:209:3)
    at _runTestsForDescribeBlock (/Users/jenkins/jenkins/workspace/brave-browser-build-macos-arm64-beta/src/brave/node_modules/jest-circus/build/run.js:97:9)
    at run (/Users/jenkins/jenkins/workspace/brave-browser-build-macos-arm64-beta/src/brave/node_modules/jest-circus/build/run.js:31:3)
    at runAndTransformResultsToJestFormat (/Users/jenkins/jenkins/workspace/brave-browser-build-macos-arm64-beta/src/brave/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapterInit.js:135:21)
    at jestAdapter (/Users/jenkins/jenkins/workspace/brave-browser-build-macos-arm64-beta/src/brave/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapter.js:70:21)
    at runTestInternal (/Users/jenkins/jenkins/workspace/brave-browser-build-macos-arm64-beta/src/brave/node_modules/jest-runner/build/runTest.js:411:16)
    at runTest (/Users/jenkins/jenkins/workspace/brave-browser-build-macos-arm64-beta/src/brave/node_modules/jest-runner/build/runTest.js:499:34)
    at Object.worker (/Users/jenkins/jenkins/workspace/brave-browser-build-macos-arm64-beta/src/brave/node_modules/jest-runner/build/testWorker.js:133:12)
null
```
</details>
<details>
<summary>Previous issues</summary>

* #49323

[Find all](https://github.com/brave/brave-browser/issues?q=type%3Aissue+label%3Abot%2Ftype%2Ftest+in%3Atitle+%22Test+failure%3A+Extract+accounts+from+unlocked+device+returned+success.+Extract+accounts+from+unlocked+device+returned+success%22)
</details>

### LINKED ISSUE #54564: Test failure:  Extracting accounts from unlocked device fail to access bridge. Extracting accounts from unlocked device fail to access bridge
Greetings human!

Bad news. ` Extracting accounts from unlocked device fail to access bridge. Extracting accounts from unlocked device fail to access bridge` [failed on browser macos arm64 beta v1.90.106](https://ci.brave.com/job/brave-browser-build-macos-arm64/6252/testReport/junit/(root)/%20Extracting%20accounts%20from%20unlocked%20device%20fail%20to%20access%20bridge/test_javascript____Extracting_accounts_from_unlocked_device_fail_to_access_bridge).
<details>
<summary>Stack trace</summary>

```
Error: expect(received).resolves.toStrictEqual(expected) // deep equality
- Expected  - 2
+ Received  + 2
  Object {
-   "code": "test_code",
-   "error": "braveWalletCreateBridgeError",
+   "code": 0,
+   "error": "braveWalletBridgeNotReady",
    "success": false,
  }
    at Object.toStrictEqual (/Users/jenkins/jenkins/workspace/brave-browser-build-macos-arm64-beta/src/brave/node_modules/expect/build/index.js:194:22)
    at Object.<anonymous> (/Users/jenkins/jenkins/workspace/brave-browser-build-macos-arm64-beta/src/brave/components/brave_wallet_ui/common/hardware/trezor/trezor_bridge_keyring.test.ts:372:14)
    at Promise.then.completed (/Users/jenkins/jenkins/workspace/brave-browser-build-macos-arm64-beta/src/brave/node_modules/jest-circus/build/utils.js:333:28)
    at new Promise (<anonymous>)
    at callAsyncCircusFn (/Users/jenkins/jenkins/workspace/brave-browser-build-macos-arm64-beta/src/brave/node_modules/jest-circus/build/utils.js:259:10)
    at _callCircusTest (/Users/jenkins/jenkins/workspace/brave-browser-build-macos-arm64-beta/src/brave/node_modules/jest-circus/build/run.js:277:40)
    at processTicksAndRejections (node:internal/process/task_queues:104:5)
    at _runTest (/Users/jenkins/jenkins/workspace/brave-browser-build-macos-arm64-beta/src/brave/node_modules/jest-circus/build/run.js:209:3)
    at _runTestsForDescribeBlock (/Users/jenkins/jenkins/workspace/brave-browser-build-macos-arm64-beta/src/brave/node_modules/jest-circus/build/run.js:97:9)
    at run (/Users/jenkins/jenkins/workspace/brave-browser-build-macos-arm64-beta/src/brave/node_modules/jest-circus/build/run.js:31:3)
    at runAndTransformResultsToJestFormat (/Users/jenkins/jenkins/workspace/brave-browser-build-macos-arm64-beta/src/brave/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapterInit.js:135:21)
    at jestAdapter (/Users/jenkins/jenkins/workspace/brave-browser-build-macos-arm64-beta/src/brave/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapter.js:70:21)
    at runTestInternal (/Users/jenkins/jenkins/workspace/brave-browser-build-macos-arm64-beta/src/brave/node_modules/jest-runner/build/runTest.js:411:16)
    at runTest (/Users/jenkins/jenkins/workspace/brave-browser-build-macos-arm64-beta/src/brave/node_modules/jest-runner/build/runTest.js:499:34)
    at Object.worker (/Users/jenkins/jenkins/workspace/brave-browser-build-macos-arm64-beta/src/brave/node_modules/jest-runner/build/testWorker.js:133:12)
null
```
</details>
<details>
<summary>Previous issues</summary>

* #49324

[Find all](https://github.com/brave/brave-browser/issues?q=type%3Aissue+label%3Abot%2Ftype%2Ftest+in%3Atitle+%22Test+failure%3A+Extracting+accounts+from+unlocked+device+fail+to+access+bridge.+Extracting+accounts+from+unlocked+device+fail+to%22)
</details>

### LINKED ISSUE #54565: Test failure:  Extracting accounts from unlocked device returned success without zero index. Extracting accounts from unlocked device returned success without zero index
Greetings human!

Bad news. ` Extracting accounts from unlocked device returned success without zero index. Extracting accounts from unlocked device returned success without zero index` [failed on browser macos arm64 beta v1.90.106](https://ci.brave.com/job/brave-browser-build-macos-arm64/6252/testReport/junit/(root)/%20Extracting%20accounts%20from%20unlocked%20device%20returned%20success%20without%20zero%20index/test_javascript____Extracting_accounts_from_unlocked_device_returned_success_without_zero_index).
<details>
<summary>Stack trace</summary>

```
Error: expect(received).resolves.toStrictEqual(expected) // deep equality
- Expected  - 11
+ Received  +  3
  Object {
-   "accounts": Array [
-     Object {
-       "address": "0x2F015C60E0be116B1f0CD534704Db9c92118FB6A",
-       "derivationPath": "m/44'/60'/0'/0/0",
-     },
-     Object {
-       "address": "0x8e926dF9926746ba352F4d479Fb5DE47382e83bE",
-       "derivationPath": "m/44'/60'/0'/0/1",
-     },
-   ],
-   "success": true,
+   "code": 0,
+   "error": "braveWalletBridgeNotReady",
+   "success": false,
  }
    at Object.toStrictEqual (/Users/jenkins/jenkins/workspace/brave-browser-build-macos-arm64-beta/src/brave/node_modules/expect/build/index.js:194:22)
    at Object.<anonymous> (/Users/jenkins/jenkins/workspace/brave-browser-build-macos-arm64-beta/src/brave/components/brave_wallet_ui/common/hardware/trezor/trezor_bridge_keyring.test.ts:442:14)
    at Promise.then.completed (/Users/jenkins/jenkins/workspace/brave-browser-build-macos-arm64-beta/src/brave/node_modules/jest-circus/build/utils.js:333:28)
    at new Promise (<anonymous>)
    at callAsyncCircusFn (/Users/jenkins/jenkins/workspace/brave-browser-build-macos-arm64-beta/src/brave/node_modules/jest-circus/build/utils.js:259:10)
    at _callCircusTest (/Users/jenkins/jenkins/workspace/brave-browser-build-macos-arm64-beta/src/brave/node_modules/jest-circus/build/run.js:277:40)
    at processTicksAndRejections (node:internal/process/task_queues:104:5)
    at _runTest (/Users/jenkins/jenkins/workspace/brave-browser-build-macos-arm64-beta/src/brave/node_modules/jest-circus/build/run.js:209:3)
    at _runTestsForDescribeBlock (/Users/jenkins/jenkins/workspace/brave-browser-build-macos-arm64-beta/src/brave/node_modules/jest-circus/build/run.js:97:9)
    at run (/Users/jenkins/jenkins/workspace/brave-browser-build-macos-arm64-beta/src/brave/node_modules/jest-circus/build/run.js:31:3)
    at runAndTransformResultsToJestFormat (/Users/jenkins/jenkins/workspace/brave-browser-build-macos-arm64-beta/src/brave/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapterInit.js:135:21)
    at jestAdapter (/Users/jenkins/jenkins/workspace/brave-browser-build-macos-arm64-beta/src/brave/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapter.js:70:21)
    at runTestInternal (/Users/jenkins/jenkins/workspace/brave-browser-build-macos-arm64-beta/src/brave/node_modules/jest-runner/build/runTest.js:411:16)
    at runTest (/Users/jenkins/jenkins/workspace/brave-browser-build-macos-arm64-beta/src/brave/node_modules/jest-runner/build/runTest.js:499:34)
    at Object.worker (/Users/jenkins/jenkins/workspace/brave-browser-build-macos-arm64-beta/src/brave/node_modules/jest-runner/build/testWorker.js:133:12)
null
```
</details>
<details>
<summary>Previous issues</summary>

* #49325

[Find all](https://github.com/brave/brave-browser/issues?q=type%3Aissue+label%3Abot%2Ftype%2Ftest+in%3Atitle+%22Test+failure%3A+Extracting+accounts+from+unlocked+device+returned+success+without+zero+index.+Extracting+accounts+from+unlocked%22)
</details>

### LINKED ISSUE #54566: Test failure:  Sign message from unlocked device failed. Sign message from unlocked device failed
Greetings human!

Bad news. ` Sign message from unlocked device failed. Sign message from unlocked device failed` [failed on browser macos arm64 beta v1.90.106](https://ci.brave.com/job/brave-browser-build-macos-arm64/6252/testReport/junit/(root)/%20Sign%20message%20from%20unlocked%20device%20failed/test_javascript____Sign_message_from_unlocked_device_failed).
<details>
<summary>Stack trace</summary>

```
Error: expect(received).resolves.toStrictEqual(expected) // deep equality
- Expected  - 2
+ Received  + 2
  Object {
-   "code": "1",
-   "error": "error",
+   "code": 0,
+   "error": "braveWalletBridgeNotReady",
    "success": false,
  }
    at Object.toStrictEqual (/Users/jenkins/jenkins/workspace/brave-browser-build-macos-arm64-beta/src/brave/node_modules/expect/build/index.js:194:22)
    at Object.<anonymous> (/Users/jenkins/jenkins/workspace/brave-browser-build-macos-arm64-beta/src/brave/components/brave_wallet_ui/common/hardware/trezor/trezor_bridge_keyring.test.ts:662:14)
    at Promise.then.completed (/Users/jenkins/jenkins/workspace/brave-browser-build-macos-arm64-beta/src/brave/node_modules/jest-circus/build/utils.js:333:28)
    at new Promise (<anonymous>)
    at callAsyncCircusFn (/Users/jenkins/jenkins/workspace/brave-browser-build-macos-arm64-beta/src/brave/node_modules/jest-circus/build/utils.js:259:10)
    at _callCircusTest (/Users/jenkins/jenkins/workspace/brave-browser-build-macos-arm64-beta/src/brave/node_modules/jest-circus/build/run.js:277:40)
    at processTicksAndRejections (node:internal/process/task_queues:104:5)
    at _runTest (/Users/jenkins/jenkins/workspace/brave-browser-build-macos-arm64-beta/src/brave/node_modules/jest-circus/build/run.js:209:3)
    at _runTestsForDescribeBlock (/Users/jenkins/jenkins/workspace/brave-browser-build-macos-arm64-beta/src/brave/node_modules/jest-circus/build/run.js:97:9)
    at run (/Users/jenkins/jenkins/workspace/brave-browser-build-macos-arm64-beta/src/brave/node_modules/jest-circus/build/run.js:31:3)
    at runAndTransformResultsToJestFormat (/Users/jenkins/jenkins/workspace/brave-browser-build-macos-arm64-beta/src/brave/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapterInit.js:135:21)
    at jestAdapter (/Users/jenkins/jenkins/workspace/brave-browser-build-macos-arm64-beta/src/brave/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapter.js:70:21)
    at runTestInternal (/Users/jenkins/jenkins/workspace/brave-browser-build-macos-arm64-beta/src/brave/node_modules/jest-runner/build/runTest.js:411:16)
    at runTest (/Users/jenkins/jenkins/workspace/brave-browser-build-macos-arm64-beta/src/brave/node_modules/jest-runner/build/runTest.js:499:34)
    at Object.worker (/Users/jenkins/jenkins/workspace/brave-browser-build-macos-arm64-beta/src/brave/node_modules/jest-runner/build/testWorker.js:133:12)
null
```
</details>
<details>
<summary>Previous issues</summary>

* #49326

[Find all](https://github.com/brave/brave-browser/issues?q=type%3Aissue+label%3Abot%2Ftype%2Ftest+in%3Atitle+%22Test+failure%3A+Sign+message+from+unlocked+device+failed.+Sign+message+from+unlocked+device+failed%22)
</details>

### LINKED ISSUE #54567: Test failure:  Sign message from unlocked device success. Sign message from unlocked device success
Greetings human!

Bad news. ` Sign message from unlocked device success. Sign message from unlocked device success` [failed on browser macos arm64 beta v1.90.106](https://ci.brave.com/job/brave-browser-build-macos-arm64/6252/testReport/junit/(root)/%20Sign%20message%20from%20unlocked%20device%20success/test_javascript____Sign_message_from_unlocked_device_success).
<details>
<summary>Stack trace</summary>

```
Error: expect(received).resolves.toStrictEqual(expected) // deep equality
- Expected  - 8
+ Received  + 3
  Object {
-   "signature": Object {
-     "bytes": Array [
-       3,
-       1,
-       4,
-     ],
-   },
-   "success": true,
+   "code": 0,
+   "error": "braveWalletBridgeNotReady",
+   "success": false,
  }
    at Object.toStrictEqual (/Users/jenkins/jenkins/workspace/brave-browser-build-macos-arm64-beta/src/brave/node_modules/expect/build/index.js:194:22)
    at Object.<anonymous> (/Users/jenkins/jenkins/workspace/brave-browser-build-macos-arm64-beta/src/brave/components/brave_wallet_ui/common/hardware/trezor/trezor_bridge_keyring.test.ts:643:14)
    at Promise.then.completed (/Users/jenkins/jenkins/workspace/brave-browser-build-macos-arm64-beta/src/brave/node_modules/jest-circus/build/utils.js:333:28)
    at new Promise (<anonymous>)
    at callAsyncCircusFn (/Users/jenkins/jenkins/workspace/brave-browser-build-macos-arm64-beta/src/brave/node_modules/jest-circus/build/utils.js:259:10)
    at _callCircusTest (/Users/jenkins/jenkins/workspace/brave-browser-build-macos-arm64-beta/src/brave/node_modules/jest-circus/build/run.js:277:40)
    at processTicksAndRejections (node:internal/process/task_queues:104:5)
    at _runTest (/Users/jenkins/jenkins/workspace/brave-browser-build-macos-arm64-beta/src/brave/node_modules/jest-circus/build/run.js:209:3)
    at _runTestsForDescribeBlock (/Users/jenkins/jenkins/workspace/brave-browser-build-macos-arm64-beta/src/brave/node_modules/jest-circus/build/run.js:97:9)
    at run (/Users/jenkins/jenkins/workspace/brave-browser-build-macos-arm64-beta/src/brave/node_modules/jest-circus/build/run.js:31:3)
    at runAndTransformResultsToJestFormat (/Users/jenkins/jenkins/workspace/brave-browser-build-macos-arm64-beta/src/brave/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapterInit.js:135:21)
    at jestAdapter (/Users/jenkins/jenkins/workspace/brave-browser-build-macos-arm64-beta/src/brave/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapter.js:70:21)
    at runTestInternal (/Users/jenkins/jenkins/workspace/brave-browser-build-macos-arm64-beta/src/brave/node_modules/jest-runner/build/runTest.js:411:16)
    at runTest (/Users/jenkins/jenkins/workspace/brave-browser-build-macos-arm64-beta/src/brave/node_modules/jest-runner/build/runTest.js:499:34)
    at Object.worker (/Users/jenkins/jenkins/workspace/brave-browser-build-macos-arm64-beta/src/brave/node_modules/jest-runner/build/testWorker.js:133:12)
null
```
</details>
<details>
<summary>Previous issues</summary>

* #49327

[Find all](https://github.com/brave/brave-browser/issues?q=type%3Aissue+label%3Abot%2Ftype%2Ftest+in%3Atitle+%22Test+failure%3A+Sign+message+from+unlocked+device+success.+Sign+message+from+unlocked+device+success%22)
</details>

### LINKED ISSUE #54568: Test failure:  Sign transaction failed from unlocked device. Sign transaction failed from unlocked device
Greetings human!

Bad news. ` Sign transaction failed from unlocked device. Sign transaction failed from unlocked device` [failed on browser macos arm64 beta v1.90.106](https://ci.brave.com/job/brave-browser-build-macos-arm64/6252/testReport/junit/(root)/%20Sign%20transaction%20failed%20from%20unlocked%20device/test_javascript____Sign_transaction_failed_from_unlocked_device).
<details>
<summary>Stack trace</summary>

```
Error: expect(received).resolves.toStrictEqual(expected) // deep equality
- Expected  - 2
+ Received  + 2
  Object {
-   "code": "Method_PermissionsNotGranted",
-   "error": "Permissions not granted",
+   "code": 0,
+   "error": "braveWalletBridgeNotReady",
    "success": false,
  }
    at Object.toStrictEqual (/Users/jenkins/jenkins/workspace/brave-browser-build-macos-arm64-beta/src/brave/node_modules/expect/build/index.js:194:22)
    at Object.<anonymous> (/Users/jenkins/jenkins/workspace/brave-browser-build-macos-arm64-beta/src/brave/components/brave_wallet_ui/common/hardware/trezor/trezor_bridge_keyring.test.ts:617:14)
    at Promise.then.completed (/Users/jenkins/jenkins/workspace/brave-browser-build-macos-arm64-beta/src/brave/node_modules/jest-circus/build/utils.js:333:28)
    at new Promise (<anonymous>)
    at callAsyncCircusFn (/Users/jenkins/jenkins/workspace/brave-browser-build-macos-arm64-beta/src/brave/node_modules/jest-circus/build/utils.js:259:10)
    at _callCircusTest (/Users/jenkins/jenkins/workspace/brave-browser-build-macos-arm64-beta/src/brave/node_modules/jest-circus/build/run.js:277:40)
    at processTicksAndRejections (node:internal/process/task_queues:104:5)
    at _runTest (/Users/jenkins/jenkins/workspace/brave-browser-build-macos-arm64-beta/src/brave/node_modules/jest-circus/build/run.js:209:3)
    at _runTestsForDescribeBlock (/Users/jenkins/jenkins/workspace/brave-browser-build-macos-arm64-beta/src/brave/node_modules/jest-circus/build/run.js:97:9)
    at run (/Users/jenkins/jenkins/workspace/brave-browser-build-macos-arm64-beta/src/brave/node_modules/jest-circus/build/run.js:31:3)
    at runAndTransformResultsToJestFormat (/Users/jenkins/jenkins/workspace/brave-browser-build-macos-arm64-beta/src/brave/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapterInit.js:135:21)
    at jestAdapter (/Users/jenkins/jenkins/workspace/brave-browser-build-macos-arm64-beta/src/brave/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapter.js:70:21)
    at runTestInternal (/Users/jenkins/jenkins/workspace/brave-browser-build-macos-arm64-beta/src/brave/node_modules/jest-runner/build/runTest.js:411:16)
    at runTest (/Users/jenkins/jenkins/workspace/brave-browser-build-macos-arm64-beta/src/brave/node_modules/jest-runner/build/runTest.js:499:34)
    at Object.worker (/Users/jenkins/jenkins/workspace/brave-browser-build-macos-arm64-beta/src/brave/node_modules/jest-runner/build/testWorker.js:133:12)
null
```
</details>
<details>
<summary>Previous issues</summary>

* #49328

[Find all](https://github.com/brave/brave-browser/issues?q=type%3Aissue+label%3Abot%2Ftype%2Ftest+in%3Atitle+%22Test+failure%3A+Sign+transaction+failed+from+unlocked+device.+Sign+transaction+failed+from+unlocked+device%22)
</details>

### LINKED ISSUE #54569: Test failure:  Sign transaction from unlocked device. Sign transaction from unlocked device
Greetings human!

Bad news. ` Sign transaction from unlocked device. Sign transaction from unlocked device` [failed on browser macos arm64 beta v1.90.106](https://ci.brave.com/job/brave-browser-build-macos-arm64/6252/testReport/junit/(root)/%20Sign%20transaction%20from%20unlocked%20device/test_javascript____Sign_transaction_from_unlocked_device).
<details>
<summary>Stack trace</summary>

```
Error: expect(received).resolves.toStrictEqual(expected) // deep equality
- Expected  - 15
+ Received  +  3
  Object {
-   "signature": Object {
-     "rBytes": Array [
-       2,
-       3,
-     ],
-     "sBytes": Array [
-       4,
-       5,
-       6,
-     ],
-     "vBytes": Array [
-       1,
-     ],
-   },
-   "success": true,
+   "code": 0,
+   "error": "braveWalletBridgeNotReady",
+   "success": false,
  }
    at Object.toStrictEqual (/Users/jenkins/jenkins/workspace/brave-browser-build-macos-arm64-beta/src/brave/node_modules/expect/build/index.js:194:22)
    at Object.<anonymous> (/Users/jenkins/jenkins/workspace/brave-browser-build-macos-arm64-beta/src/brave/components/brave_wallet_ui/common/hardware/trezor/trezor_bridge_keyring.test.ts:586:14)
    at Promise.then.completed (/Users/jenkins/jenkins/workspace/brave-browser-build-macos-arm64-beta/src/brave/node_modules/jest-circus/build/utils.js:333:28)
    at new Promise (<anonymous>)
    at callAsyncCircusFn (/Users/jenkins/jenkins/workspace/brave-browser-build-macos-arm64-beta/src/brave/node_modules/jest-circus/build/utils.js:259:10)
    at _callCircusTest (/Users/jenkins/jenkins/workspace/brave-browser-build-macos-arm64-beta/src/brave/node_modules/jest-circus/build/run.js:277:40)
    at processTicksAndRejections (node:internal/process/task_queues:104:5)
    at _runTest (/Users/jenkins/jenkins/workspace/brave-browser-build-macos-arm64-beta/src/brave/node_modules/jest-circus/build/run.js:209:3)
    at _runTestsForDescribeBlock (/Users/jenkins/jenkins/workspace/brave-browser-build-macos-arm64-beta/src/brave/node_modules/jest-circus/build/run.js:97:9)
    at run (/Users/jenkins/jenkins/workspace/brave-browser-build-macos-arm64-beta/src/brave/node_modules/jest-circus/build/run.js:31:3)
    at runAndTransformResultsToJestFormat (/Users/jenkins/jenkins/workspace/brave-browser-build-macos-arm64-beta/src/brave/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapterInit.js:135:21)
    at jestAdapter (/Users/jenkins/jenkins/workspace/brave-browser-build-macos-arm64-beta/src/brave/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapter.js:70:21)
    at runTestInternal (/Users/jenkins/jenkins/workspace/brave-browser-build-macos-arm64-beta/src/brave/node_modules/jest-runner/build/runTest.js:411:16)
    at runTest (/Users/jenkins/jenkins/workspace/brave-browser-build-macos-arm64-beta/src/brave/node_modules/jest-runner/build/runTest.js:499:34)
    at Object.worker (/Users/jenkins/jenkins/workspace/brave-browser-build-macos-arm64-beta/src/brave/node_modules/jest-runner/build/testWorker.js:133:12)
null
```
</details>
<details>
<summary>Previous issues</summary>

* #49329

[Find all](https://github.com/brave/brave-browser/issues?q=type%3Aissue+label%3Abot%2Ftype%2Ftest+in%3Atitle+%22Test+failure%3A+Sign+transaction+from+unlocked+device.+Sign+transaction+from+unlocked+device%22)
</details>

### LINKED ISSUE #54570: Test failure:  Sign typed from unlocked device, success. Sign typed from unlocked device, success
Greetings human!

Bad news. ` Sign typed from unlocked device, success. Sign typed from unlocked device, success` [failed on browser macos arm64 beta v1.90.106](https://ci.brave.com/job/brave-browser-build-macos-arm64/6252/testReport/junit/(root)/%20Sign%20typed%20from%20unlocked%20device,%20success/test_javascript____Sign_typed_from_unlocked_device__success).
<details>
<summary>Stack trace</summary>

```
Error: expect(received).resolves.toStrictEqual(expected) // deep equality
- Expected  - 8
+ Received  + 3
  Object {
-   "signature": Object {
-     "bytes": Array [
-       2,
-       7,
-       8,
-     ],
-   },
-   "success": true,
+   "code": 0,
+   "error": "braveWalletBridgeNotReady",
+   "success": false,
  }
    at Object.toStrictEqual (/Users/jenkins/jenkins/workspace/brave-browser-build-macos-arm64-beta/src/brave/node_modules/expect/build/index.js:194:22)
    at Object.<anonymous> (/Users/jenkins/jenkins/workspace/brave-browser-build-macos-arm64-beta/src/brave/components/brave_wallet_ui/common/hardware/trezor/trezor_bridge_keyring.test.ts:700:14)
    at Promise.then.completed (/Users/jenkins/jenkins/workspace/brave-browser-build-macos-arm64-beta/src/brave/node_modules/jest-circus/build/utils.js:333:28)
    at new Promise (<anonymous>)
    at callAsyncCircusFn (/Users/jenkins/jenkins/workspace/brave-browser-build-macos-arm64-beta/src/brave/node_modules/jest-circus/build/utils.js:259:10)
    at _callCircusTest (/Users/jenkins/jenkins/workspace/brave-browser-build-macos-arm64-beta/src/brave/node_modules/jest-circus/build/run.js:277:40)
    at processTicksAndRejections (node:internal/process/task_queues:104:5)
    at _runTest (/Users/jenkins/jenkins/workspace/brave-browser-build-macos-arm64-beta/src/brave/node_modules/jest-circus/build/run.js:209:3)
    at _runTestsForDescribeBlock (/Users/jenkins/jenkins/workspace/brave-browser-build-macos-arm64-beta/src/brave/node_modules/jest-circus/build/run.js:97:9)
    at run (/Users/jenkins/jenkins/workspace/brave-browser-build-macos-arm64-beta/src/brave/node_modules/jest-circus/build/run.js:31:3)
    at runAndTransformResultsToJestFormat (/Users/jenkins/jenkins/workspace/brave-browser-build-macos-arm64-beta/src/brave/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapterInit.js:135:21)
    at jestAdapter (/Users/jenkins/jenkins/workspace/brave-browser-build-macos-arm64-beta/src/brave/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapter.js:70:21)
    at runTestInternal (/Users/jenkins/jenkins/workspace/brave-browser-build-macos-arm64-beta/src/brave/node_modules/jest-runner/build/runTest.js:411:16)
    at runTest (/Users/jenkins/jenkins/workspace/brave-browser-build-macos-arm64-beta/src/brave/node_modules/jest-runner/build/runTest.js:499:34)
    at Object.worker (/Users/jenkins/jenkins/workspace/brave-browser-build-macos-arm64-beta/src/brave/node_modules/jest-runner/build/testWorker.js:133:12)
null
```
</details>
<details>
<summary>Previous issues</summary>

* #49330

[Find all](https://github.com/brave/brave-browser/issues?q=type%3Aissue+label%3Abot%2Ftype%2Ftest+in%3Atitle+%22Test+failure%3A+Sign+typed+from+unlocked+device%2C+success.+Sign+typed+from+unlocked+device%2C+success%22)
</details>

### PR DESCRIPTION
**Pull request by supermassive**
Made it so bridge iframe is injected in TrezorBridgeKeyring constructor to avoid race conditions.  

Resolves https://github.com/brave/brave-browser/issues/54573
Resolves https://github.com/brave/brave-browser/issues/54572
Resolves https://github.com/brave/brave-browser/issues/54571
Resolves https://github.com/brave/brave-browser/issues/54570
Resolves https://github.com/brave/brave-browser/issues/54569
Resolves https://github.com/brave/brave-browser/issues/54568
Resolves https://github.com/brave/brave-browser/issues/54567
Resolves https://github.com/brave/brave-browser/issues/54566
Resolves https://github.com/brave/brave-browser/issues/54565
Resolves https://github.com/brave/brave-browser/issues/54564
Resolves https://github.com/brave/brave-browser/issues/54563
Resolves https://github.com/brave/brave-browser/issues/54562
Resolves https://github.com/brave/brave-browser/issues/54561

### CODE REVIEW

File: components/brave_wallet_ui/common/hardware/trezor/trezor-bridge-transport.ts [hunk 1]
```diff
@@ -76,38 +69,17 @@ export class TrezorBridgeTransport extends MessagingTransport {
...
-
-  private readonly createBridge = () => {
-    return new Promise<HTMLIFrameElement>((resolve) => {
-      let element = document.createElement('iframe')
-      element.id = this.frameId
-      element.src = this.bridgeFrameUrl
-      element.style.display = 'none'
-      element.onload = () => {
-        resolve(element)
-      }
```
Comment (onyb) [inline components/brave_wallet_ui/common/hardware/trezor/trezor-bridge-transport.ts:88]: Doesn't look like we're doing this anymore after your changes.

File: components/brave_wallet_ui/common/hardware/trezor/trezor-bridge-transport.ts [hunk 2]
```diff
@@ -4,32 +4,28 @@
...
     super()
     this.bridgeFrameUrl = bridgeFrameUrl
-    this.frameId = crypto.randomUUID()
+    this.bridge = bridge
   }
 
-  private readonly frameId: string
   private readonly bridgeFrameUrl: string
-  private bridge?: HTMLIFrameElement
+  private readonly bridge: HTMLIFrameElement
```
Comment (onyb) [inline components/brave_wallet_ui/common/hardware/trezor/trezor-bridge-transport.ts:22]: Perhaps we should track if the bridge was loaded with a flag.

```ts
private bridgeLoaded = false
```

then in the constructor have:
```ts
bridge.onload = () => {
  this.bridgeLoaded = true
}
```

The flag could subsequently be used to throw `TrezorErrorsCodes.BridgeNotReady`.

Comment (supermassive) [reply components/brave_wallet_ui/common/hardware/trezor/trezor-bridge-transport.ts:22]: Made it so bridge frame is created and loaded first, then moved to TrezorBridgeKeyring

File: components/brave_wallet_ui/common/hardware/trezor/trezor-bridge-transport.ts (hunk 1 above)
Comment (supermassive) [reply components/brave_wallet_ui/common/hardware/trezor/trezor-bridge-transport.ts:88]: Thanks.
Promise is back

**Review by onyb — APPROVED** [review]

**Review by netzenbot — APPROVED** [review]

File: components/brave_wallet_ui/common/async/hardware.ts [hunk 3]
```diff
@@ -84,7 +83,7 @@ export async function signTrezorTransaction(
   apiProxy: WalletApiProxy,
   path: string,
   txInfo: Pick<SerializableTransactionInfo, 'id' | 'chainId' | 'txDataUnion'>,
-  deviceKeyring: TrezorBridgeKeyring = getTrezorHardwareKeyring(),
+  deviceKeyring: TrezorBridgeKeyring,
```
Comment (netzenbot) [inline components/brave_wallet_ui/common/async/hardware.ts:86]: `hardware.test.ts` line 412 calls `signTrezorTransaction(apiProxy, 'path', txInfo)` with only 3 arguments. Now that `deviceKeyring` has no default, that call is a TypeScript type error. The test file needs to be updated to pass a mock `TrezorBridgeKeyring`.
