### PR TITLE
SchedulePaint() on container list pref changes

### LINKED ISSUE #54744: [Containers] Changing icon/theme of container doesn't update on tab until hovered over
### Description

Changing icon/theme of Continers doesn't update on tab until hovered over

### Steps to reproduce

1. Enable containers
2. Add a few tabs to the container
3. Go to settings and update the icon/theme
4. Pinned tabs update the icon/theme only when you hover over it

### Actual result

Changing icon/theme of Continers doesn't update on tab until hovered over

### Expected result

Should update the icon/theme without hovering over the tabs

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

Brave | 1.91.56 Chromium: 147.0.7727.56 (Official Build) nightly (64-bit)
-- | --
Revision | 49a51b28544eb9eedd3feecb38a7a123e281eebd
OS | Windows 11 Version 25H2 (Build 26200.8037)

### Channel information

- [ ] release (stable)
- [ ] beta
- [x] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

cc: @rebron

### PR DESCRIPTION
**Pull request by sangwoo108**
Resolves https://github.com/brave/brave-browser/issues/54744

### CODE REVIEW

File: browser/ui/views/tabs/brave_tab.cc [hunk 1]
```diff
@@ -365,6 +373,29 @@ void BraveTab::LayoutSmallTabAccentIcon() {
...
+    return;
+  }
+
+  auto* containers_service =
+      ContainersServiceFactory::GetInstance()->GetForProfile(
+          controller_->GetBrowserWindowInterface()->GetProfile());
+
+  container_changed_subscription_ =
+      containers_service->RegisterContainerChangedCallback(base::BindRepeating(
+          &BraveTab::OnContainerChanged, base::Unretained(this)));
```
[the remark this answers is not in the document]
Comment (sangwoo108) [reply browser/ui/views/tabs/brave_tab.cc]: Safe to have this `Unretained` as it's RAII style callback registration.

File: components/containers/core/browser/containers_service.h [hunk 2]
```diff
@@ -89,6 +94,7 @@ class ContainersService : public KeyedService {
   raw_ref<PrefService> prefs_;
   std::unique_ptr<Delegate> delegate_;
   PrefChangeRegistrar pref_change_registrar_;
+  base::RepeatingClosureList container_changed_callback_list_;
```
Comment (goodov) [inline components/containers/core/browser/containers_service.h]: I like the simplicity of this, but let's please go with an observer here. Yes, it's a bit wordy in terms of buildflags adoption, but it's the right thing longterm. Please make it as a non-nested class to not depend on the service directly.

```
// containers_service_observer.h

class ContainersServiceObserver : public base::CheckedObserver {
 public:
  virtual ~ContainersServiceObserver() = default;

  // ...
  void OnContainersListChanged() {}
};
```

Comment (sangwoo108) [reply components/containers/core/browser/containers_service.h]: That must be more extensible. Done.

File: browser/ui/views/tabs/brave_tab.cc [hunk 3]
```diff
@@ -535,6 +574,16 @@ void BraveTab::MaybeUpdateHoverStatus(const ui::MouseEvent& event) {
   }
 }
 
+void BraveTab::OnPaint(gfx::Canvas* canvas) {
+  Tab::OnPaint(canvas);
+
+#if BUILDFLAG(ENABLE_CONTAINERS)
+  // In case we are showing large accent icon, we need to try  observing
+  // container pref changes.
+  MaybeObserveContainerChanges();
```
Comment (goodov) [inline browser/ui/views/tabs/brave_tab.cc]: won't this be called like at 60fps? Is the right place to register/unregister an observer?

File: components/containers/core/browser/containers_service.h [hunk 4]
```diff
@@ -67,6 +69,9 @@ class ContainersService : public KeyedService {
 
   void ScheduleOrphanedContainersCleanupForTesting();
 
+  void AddObserver(ContainersServiceObserver* observer);
```
Comment (goodov) [inline components/containers/core/browser/containers_service.h]: pls put these right after `void Shutdown()` and order in .cc file accordingly.

**Review by goodov — APPROVED** [review]
other than few comments lgtm

File: components/containers/core/browser/containers_service_observer.h [hunk 5]
```diff
@@ -0,0 +1,25 @@
...
+
+#include "base/observer_list_types.h"
+
+namespace containers {
+
+// Observes `ContainersService` for changes to the user-editable containers list
+// (backed by prefs).
+class ContainersServiceObserver : public base::CheckedObserver {
+ public:
+  ~ContainersServiceObserver() override = default;
```
Comment (goodov) [inline components/containers/core/browser/containers_service_observer.h]: nit: I think we don't need this here when we use CheckedObserver

File: browser/ui/views/tabs/brave_tab.cc (hunk 3 above)
Comment (sangwoo108) [reply browser/ui/views/tabs/brave_tab.cc]: Let me check if we can do this only once in the constructor. If the web contents bound to the tab outlives the tab, it should be fine to be in the constructor.

Comment (sangwoo108) [reply browser/ui/views/tabs/brave_tab.cc]: yeah seems working. Moved to the constructor.

Comment (sangwoo108) [reply browser/ui/views/tabs/brave_tab.cc]: Oh, sorry, I made mistake, it dosn't work at the constructor. Checking a little bit more.

File: components/containers/core/browser/containers_service_observer.h (hunk 5 above)
Comment (sangwoo108) [reply components/containers/core/browser/containers_service_observer.h]: Right, removed.

File: browser/ui/views/tabs/brave_tab.cc (hunk 3 above)
Comment (sangwoo108) [reply browser/ui/views/tabs/brave_tab.cc]: SetTabData seem to be better place.

File: components/containers/core/browser/containers_service.h (hunk 4 above)
Comment (sangwoo108) [reply components/containers/core/browser/containers_service.h]: Done!
