### PR TITLE
[iOS] Brave hiding logic not applying on headers for redirect requests

### LINKED ISSUE #54479: [iOS] Brave hiding logic not applying on server-side 302 redirects
### Description

iOS issue for https://github.com/brave/brave-browser/issues/54406, slightly different reproduce steps.

### Steps to reproduce

Enter `https://test-website-a.pages.dev/server-redirect/go` in omnibox

or

Enter `https://test-website-a.pages.dev/server-redirect/go` in 3rd party app (ex. iOS Notes app) and tap link to open in default browser

### Actual result

Brave is mentioned in `User-Agent` header field

### Expected result

Brave is not mentioned in `user-agent` field

Image

### Reproduces how often

Easily reproduced

### Brave version

-

### Device/iOS version

-

### Affected browser versions

- [x] latest AppStore
- [x] latest TestFlight
- [x] previous TestFlight

### Reproducibility

- [x] with Brave Shields disabled
- [ ] in the latest version of mobile Safari

### Miscellaneous information

This does not reproduce on iOS when trying to open the link via share sheet `Open in Brave` action, or if tapping on link on `https://test-website-a.pages.dev/server-redirect/` test page.

### PR DESCRIPTION
**Pull request by StephenHeaps**
Resolves https://github.com/brave/brave-browser/issues/54479

### Testplan

1. Enable `Cancel requests for user agent change` / `#should-cancel-requests-for-user-agent-change` feature flag and quit/relaunch the app
2. Enter `https://test-website-a.pages.dev/server-redirect/go` in omnibox
3. When final page is done loading, verify Brave is not mentioned
4. Reload the page, verify Brave is not mentioned
5. Open a new tab direct to `https://test-website-b.pages.dev/server-redirect/headers`
6. Verify Brave is not mentioned
7. Visit `https://stephenheaps.github.io/other/redirect.html`
8. Tap `Redirect` button
9. Verify Brave is not mentioned

### CODE REVIEW

File: ios/brave-ios/Sources/UserAgent/BraveUserAgentType+Extensions.swift [hunk 1]
```diff
@@ -0,0 +1,25 @@
...
+      isMobile ? UserAgent.mobileMasked : UserAgent.desktopMasked
+    case .version:
+      isMobile ? UserAgent.mobile : UserAgent.desktop
+    case .suffix:
+      isMobile ? UserAgent.safariMobileBraveSuffix : UserAgent.safariDesktopBraveSuffix
+    case .suffixComment:
+      isMobile
+        ? UserAgent.safariMobileBraveSuffixComment : UserAgent.safariDesktopBraveSuffixComment
+    @unknown default:
+      isMobile ? UserAgent.safariMobileBraveSuffix : UserAgent.safariDesktopBraveSuffix
```
Comment (netzenbot) [inline ios/brave-ios/Sources/UserAgent/BraveUserAgentType+Extensions.swift:24]: nit: This new public method has no doc comment. A brief summary explaining what it returns for each `BraveUserAgentType` case and what `isMobile` controls would help callers. See [DOC-004](https://github.com/brave/brave-core/tree/master/docs/best-practices/documentation.md#DOC-004).

File: ios/brave-ios/Sources/UserAgent/BraveUserAgentType+Extensions.swift [hunk 2]
```diff
@@ -0,0 +1,27 @@
+// Copyright (c) 2025 The Brave Authors. All rights reserved.
```
Comment (netzenbot) [inline ios/brave-ios/Sources/UserAgent/BraveUserAgentType+Extensions.swift]: nit: New files must use the current year in the copyright header. This file was created in 2026 but the copyright says 2025. See [CS-012](https://github.com/brave/brave-core/tree/master/docs/best-practices/coding-standards.md#CS-012).

**Review by nuo-xu — APPROVED** [review]

File: ios/brave-ios/Sources/Brave/Frontend/Browser/BrowserViewController/BVC+TabPolicyDecider.swift [hunk 3]
```diff
@@ -465,12 +466,35 @@ extension BrowserViewController {
...
     isAdBlockEnabled: Bool
   ) -> URLRequest? {
-    guard let requestURL = request.url else { return nil }
+    // Only redirect for main frames
+    guard let requestURL = request.url, isMainFrame else { return nil }
 
-    // For main frame only and if shields are enabled
+    if FeatureList.kShouldCancelRequestsForUserAgentChange.enabled,
+      let headerUserAgent = request.allHTTPHeaderFields?["User-Agent"],
+      case let userAgentForType = self.tab(tab, userAgentForType: .automatic, request: request),
```
Comment (kylehickinson) [inline ios/brave-ios/Sources/Brave/Frontend/Browser/BrowserViewController/BVC+TabPolicyDecider.swift]: Probably shouldn't call delegate methods directly, instead move the logic you need to somewhere shared and call from both spots

**Review by kylehickinson — APPROVED** [review]
Just semnatics nit re: delegate function call, the rest looks good

File: ios/brave-ios/Sources/Brave/Frontend/Browser/BrowserViewController/BVC+TabPolicyDecider.swift (hunk 3 above)
Comment (StephenHeaps) [reply ios/brave-ios/Sources/Brave/Frontend/Browser/BrowserViewController/BVC+TabPolicyDecider.swift]: [0d7996b](https://github.com/brave/brave-core/pull/35459/commits/0d7996bbcb029beb34e4fc7d45bf5b27a79117da)

**Comment by kjozwiak** [comment]
Verification **PASSED** on `iPhone 11` running `iOS 26.3.1` using the following build(s):

```
Brave | 1.91.65 Chromium: 147.0.7727.102(Official Build) nightly (64-bit) 
--- | ---
Revision | 6dbe200a4dc1...
OS | iOS
```

Using the STR/Cases outlined via https://github.com/brave/brave-core/pull/35459#issue-4256083924, ensured that `Brave` wasn't being mentioned as per the following:

**`Example`** | **`Example`** | **`Example`** | **`Example`** | **`Example`** | **`Example`**
---------------|-----------------|----------------|----------------|----------------|-----------------
IMG_1593 | IMG_1594 | IMG_1595 | IMG_1596 | IMG_1597 | IMG_1598
