### PR TITLE
[Wallet] [Swap] Migrate 0x to gate3

### LINKED ISSUE #51850: Migrate 0x swap provider to Gate3
### Description

We're gradually moving swap API integrations to gate3 which exposes a common request/response contract that's supposed to work for all third-party providers.

This issue tracks migration of 0x API integration in brave-core to use the gate3 constructs introduced in https://github.com/brave/brave-core/pull/32982.

Note that 0x integration may need to be enhanced as part of this migration - for ex, add Solana support.

### Steps to reproduce

1. Go to Swap
2. Select supported assets (on EVM) in source/destination fields
3. Select Squid as the swap provider
4. Enter the source amount

### Actual result

- 0x quote is fetched and displayed.
- User is able to review this swap and create an unapproved transaction.

### Expected result

- 0x quote is fetched and displayed via gate3.
- User is able to review this swap and create an unapproved transaction.
- Under Auto mode, user is able to find competing quotes from other swap providers - 0x being one of them.

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

1.85.120 Chromium: 143.0.7499.192 (Official Build) (x86_64) 

### Channel information

- [x] release (stable)
- [x] beta
- [x] nightly

### Reproducibility

- [x] with Brave Shields disabled
- [x] with Brave Rewards disabled
- [x] in the latest version of Chrome

### Miscellaneous information

_No response_

### PR DESCRIPTION
**Pull request by onyb**
### Summary

Migrates the 0x swap provider on Desktop (and Android via the shared WebUI) to the unified gate3 backend, mirroring the earlier Jupiter and LiFi migrations. Desktop / Android now hit `gate3.wallet.brave.com/api/swap/v1/quote/{indicative,firm}` with `provider: "ZERO_EX"` instead of calling 0x directly.

The legacy direct-0x integration is preserved behind a new `kZeroExLegacy` mojom enum value (parallel to `kJupiterLegacy`) for iOS, which still calls `api.0x.wallet.brave.com` directly.

Resolves https://github.com/brave/brave-browser/issues/51850

### New and improved Auto mode

Selecting **Auto** mode now fetches quotes for **all** supported providers in a single gate3 call and lists every route, auto-selecting the one that matches the user's preference — Cheapest vs Fastest. Previously, the C++ client ran a hardcoded provider cascade (Jupiter → LiFi → 0x → NEAR Intents → Squid) and only ever showed one route.

### CODE REVIEW

File: components/brave_wallet/browser/swap_service.cc [hunk 1]
```diff
@@ -386,21 +356,10 @@ void SwapService::GetQuote(mojom::SwapQuoteParamsPtr params,
...
-                     weak_ptr_factory_.GetWeakPtr());
-    return;
-  }
-
-  // EVM swaps are served via 0x only if the provider is set to kZeroEx.
-  if ((params->provider == mojom::SwapProvider::kZeroEx ||
-       params->provider == mojom::SwapProvider::kAuto) &&
-      has_zero_ex_support) {
+  // Legacy 0x API (direct, for iOS/Android).
+  if (params->provider == mojom::SwapProvider::kZeroExLegacy &&
```
Comment (supermassive) [inline components/brave_wallet/browser/swap_service.cc]: Why here and above for iOS/Android have to support direct communication?

**Review by supermassive — APPROVED** [review]

File: components/brave_wallet/browser/swap_service.cc (hunk 1 above)
Comment (onyb) [reply components/brave_wallet/browser/swap_service.cc]: Small correction: it's just iOS, since Android uses WebUI. Fixed here: https://github.com/brave/brave-core/pull/36000/commits/3bf69bf5ae491e2668527145b2b79035ff87d8ff

> Why here and above for iOS/Android have to support direct communication?

We'll remove legacy 0x and Jupiter implementations as soon as iOS adds support for gate3 swaps. There's an issue for this: https://github.com/brave/brave-browser/issues/54515

**Review by Douglashdaniel — APPROVED** [review]

**Review by netzenbot — APPROVED** [review]
