### PR TITLE
[AI Chat] Use brave:// URLs on android

### LINKED ISSUE #49938: [Android] Leo fullscreen URL displays chrome:// instead of brave://
### Description

When opening Leo the URL starts with chrome:// instead of brave://

Slack thread with context: https://bravesoftware.slack.com/archives/C05NDQP03AQ/p1759551651548459

Image

### Steps to reproduce

1. Open Leo
2. Check URL

### Actual result

The URL starts with chrome://

### Expected result

The URL starts with brave://

### Reproduces how often

Easily reproduced

### Brave version

1.82

### Device

N/A

### Channel information

- [x] release (stable)
- [x] beta
- [x] nightly

### Reproducibility

- [x] with Brave Shields disabled
- [x] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### PR DESCRIPTION
**Pull request by petemill**
- Resolves https://github.com/brave/brave-browser/issues/49938

This is a workaround whilst android does not rewrite chrome:// URLs for display
- https://github.com/brave/brave-browser/issues/51302

### CODE REVIEW

**Review by netzenbot — APPROVED** [review]

**Review by fallaciousreasoning — APPROVED** [review]
lgtm, sorry for force pushing to your branch! I reverted to your version as its a bit nicer!

File: components/ai_chat/core/common/ai_chat_urls.cc [hunk 1]
```diff
@@ -14,12 +14,33 @@
...
+  url = url.ReplaceComponents(replacements);
+#endif
+  return url;
+}
+
+}  // namespace
+
 GURL TabAssociatedConversationUrl() {
-  return GURL(base::StrCat({kAIChatUIURL, "tab"}));
+  return CreateAIChatUIURL("tab");
```
Comment (bridiver) [inline components/ai_chat/core/common/ai_chat_urls.cc:39]: Just want to be sure that this is display only? We should not be storing any URLs as brave or using brave anywhere where there might be security checks

Comment (petemill) [reply components/ai_chat/core/common/ai_chat_urls.cc:39]: We reverted this didn't we?

Comment (bridiver) [reply components/ai_chat/core/common/ai_chat_urls.cc:39]: Actually I think this is before my PR? If so it can probably be removed

Comment (petemill) [reply components/ai_chat/core/common/ai_chat_urls.cc:39]: This was reverted https://github.com/brave/brave-core/pull/34627
