### PR TITLE
Fix Brave hiding logic not applying on server-side 302 redirects.

### LINKED ISSUE #54406: Brave hiding logic not applying on server-side 302 redirects
### Description

We use a different user agent string (iOS) or `Sec-CH-UA` header (desktop/android) depending on if a site is on [brave-checks.txt](https://github.com/brave/adblock-lists/blob/master/brave-lists/brave-checks.txt), to either hide or show that we are Brave Browser. See https://github.com/brave/brave-browser/wiki/Detecting-Brave-(for-Websites).

When a server-side 302 redirect occurs, the redirected request's headers will contain the original request's user agent. If only one of either the original site or redirect site is on `brave-checks`, the redirected site will have incorrect `User-Agent` and `Sec-CH-UA` HTTP header in the request header.

### Steps to Reproduce 
1. Visit https://test-website-a.pages.dev/server-redirect/
2. Tap/click on `Navigate to header inspector via server-side 302 redirect` link

### Actual Result

Brave is mentioned in headers `user-agent` / `Sec-CH-UA` /`navigator.userAgent` 

### Expected Result

Brave is not mentioned in HTTP headers or JavaScript. Note that for the test website test-website-b.pages.dev, Brave should not be mentioned in [HTTP headers](https://github.com/brave/adblock-lists/pull/2838) or [JavaScript](https://github.com/brave/adblock-lists/pull/2839) because we explicitly added it for testing purposes.

### PR DESCRIPTION
**Pull request by boocmp**
Resolves https://github.com/brave/brave-browser/issues/54406

### CODE REVIEW

**Comment by bridiver** [comment]
The title of this PR is a bit confusing. How about "Fix Brave hiding logic not applying on server-side 302 redirects"

File: browser/net/brave_user_agent_network_delegate_helper.cc [hunk 1]
```diff
@@ -22,15 +23,17 @@ constexpr char kHeaderSecCHUAFullVersionList[] = "Sec-CH-UA-Full-Version-List";
 constexpr char kBraveBrand[] = "\"Brave\"";
 constexpr char kGoogleChromeBrand[] = "\"Google Chrome\"";
 
-void ReplaceBraveWithGoogleChromeInHeader(net::HttpRequestHeaders* headers,
-                                          const char* header_name) {
+bool ReplaceBraveWithGoogleChromeInHeader(net::HttpRequestHeaders* headers,
+                                          std::string_view header_name) {
```
Comment (bridiver) [inline browser/net/brave_user_agent_network_delegate_helper.cc:27]: Please avoid unrelated changes and push to follow-up code health tasks. It confuses what the actual fix is.

File: browser/net/brave_user_agent_network_delegate_helper_browsertest.cc [hunk 2]
```diff
@@ -45,100 +52,128 @@ class BraveUserAgentNetworkDelegateBrowserTest
...
+  }
+  if (request.relative_url == "/a.test/page_with_image.html") {
+    auto* response = new ::net::test_server::BasicHttpResponse();
+    response->set_content(
+        "<html><body><img src=\"https://b.test/b.test/image.png\" "
+        "/></body></html>");
+    response->set_content_type("text/html");
+    response->AddCustomHeader("Accept-CH", "Sec-CH-UA-Full-Version-List");
+    return std::unique_ptr<::net::test_server::HttpResponse>(response);
+  }
```
Comment (netzenbot) [inline browser/net/brave_user_agent_network_delegate_helper_browsertest.cc:164]: `EXPECT_TRUE(!captures.empty())` should be `ASSERT_FALSE(captures.empty())`. If the vector is empty, the loop body never runs and all header checks are silently skipped — the test passes with no meaningful verification. https://github.com/brave/brave-core/tree/master/docs/best-practices/testing-isolation.md#TI-034

File: browser/net/brave_user_agent_network_delegate_helper_browsertest.cc [hunk 3]
```diff
@@ -45,100 +52,128 @@ class BraveUserAgentNetworkDelegateBrowserTest
...
+  if (request.relative_url == "/a.test/page_with_image.html") {
+    auto* response = new ::net::test_server::BasicHttpResponse();
+    response->set_content(
+        "<html><body><img src=\"https://b.test/b.test/image.png\" "
+        "/></body></html>");
+    response->set_content_type("text/html");
+    response->AddCustomHeader("Accept-CH", "Sec-CH-UA-Full-Version-List");
+    return std::unique_ptr<::net::test_server::HttpResponse>(response);
```
Comment (netzenbot) [inline browser/net/brave_user_agent_network_delegate_helper_browsertest.cc:163]: nit: `ExpectHeaderBrands` only reads from `captures` — prefer `base::span<const HeaderCapture>` over `const std::vector<HeaderCapture>&` to accept any contiguous container and avoid forcing the caller to use `std::vector` specifically. See [CSA-017](https://github.com/brave/brave-core/tree/master/docs/best-practices/coding-standards-apis.md#CSA-017).

File: browser/net/brave_user_agent_network_delegate_helper_browsertest.cc [hunk 4]
```diff
@@ -195,20 +242,30 @@ void BraveUserAgentNetworkDelegateBrowserTest::RunBrandHeaderTest(
...
+
+IN_PROC_BROWSER_TEST_P(BraveUserAgentNetworkDelegateBrowserTest,
+                       SecCHUAHeadersAfterRedirectFromExceptedToNonExcepted) {
+  RunBrandHeaderTest("a.test", "/a.test/redirect_a_to_b.html");
+}
+
+IN_PROC_BROWSER_TEST_P(BraveUserAgentNetworkDelegateBrowserTest,
+                       SecCHUAHeadersAfterRedirectFromNonExceptedToExcepted) {
+  RunBrandHeaderTest("b.test", "/b.test/redirect_b_to_a.html");
 }
```
Comment (netzenbot) [inline browser/net/brave_user_agent_network_delegate_helper_browsertest.cc:267]: nit: `HandleCustomRequest` silently returns `nullptr` for unhandled paths. Consider `NOTREACHED() << request.relative_url` as the fallback so unexpected requests surface immediately in test output. https://github.com/brave/brave-core/tree/master/docs/best-practices/testing-isolation.md#TI-037

**Review by StephenHeaps — APPROVED** [review]

**Review by netzenbot — APPROVED** [review]

**Review by goodov — APPROVED** [review]
