### PR TITLE
never use removeparam rules from the default engine

### LINKED ISSUE #54080: Query filter not exempting same-origin requests
### Description

When running through the tests on the test page below, it seems like params are being stripped in all cases. 

https://fmarier.github.io/brave-testing/query-filter.html

https://github.com/brave/brave-browser/releases/tag/v1.90.27 (works)
https://github.com/brave/brave-browser/releases/tag/v1.90.28 (not working)

### Steps to reproduce

1. New install
2. Open private window
3. Run tests in https://fmarier.github.io/brave-testing/query-filter.html

### Actual result

Image

### Expected result

Image

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

https://github.com/brave/brave-browser/releases/tag/v1.90.27 (not reproducible)
https://github.com/brave/brave-browser/releases/tag/v1.90.28 (reproducible)

### Channel information

- [ ] release (stable)
- [ ] beta
- [x] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

_No response_

### PR DESCRIPTION
**Pull request by antonok-edm**
Resolves https://github.com/brave/brave-browser/issues/54080

Updated in accordance with https://github.com/brave/brave-browser/wiki/Blocking-goals-and-policy#url-parameters

### CODE REVIEW

**Review by fmarier — APPROVED** [review]

File: browser/brave_shields/ad_block_service_browsertest.cc [hunk 1]
```diff
@@ -1876,17 +1875,9 @@ IN_PROC_BROWSER_TEST_F(AdBlockServiceTest, MAYBE_DefaultRemoveparamFromCustom) {
...
-                contents->GetPrimaryPage(),
-                base::BindRepeating(content::FrameHasSourceUrl, frame_url)));
-
-  GURL redirected_frame_url = embedded_test_server()->GetURL(
-      "frame.com", "/cosmetic_frame.html?test=true");
-
   content::RenderFrameHost* inner_frame = content::FrameMatchingPredicate(
       contents->GetPrimaryPage(),
-      base::BindRepeating(content::FrameHasSourceUrl, redirected_frame_url));
+      base::BindRepeating(content::FrameHasSourceUrl, frame_url));
```
Comment (netzenbot) [inline browser/brave_shields/ad_block_service_browsertest.cc:1880]: The assertion `ASSERT_EQ("?test=true", EvalJs(inner_frame, "window.location.search"))` was left over from the old test, but `frame_url` here is `?evil=true&test=true`. Since the PR ensures removeparam from the default engine is never applied, the frame stays at the original URL with both params — so `window.location.search` will be `?evil=true&test=true`, not `?test=true`, and this assertion will fail. The expected string should be `"?evil=true&test=true"` (confirming the `evil` param was NOT removed). ([✅ Verify Observable Side Effects in Browser Tests](https://github.com/brave/brave-core/tree/master/docs/best-practices/testing-isolation.md#TI-029))

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Win 11 x64` using the following build(s):

```
Brave | 1.91.66 Chromium: 147.0.7727.102 (Official Build) nightly (64-bit)
-- | --
Revision | 311811faa906d8bc382ffbb94df981d0e5f36885
OS | Windows 11 Version 25H2 (Build 26200.8246)
```

Using the STR/Cases outlined via https://github.com/brave/brave-browser/issues/54080#issue-4173666813, went through all the cases via https://fmarier.github.io/brave-testing/query-filter.html and ensured that correct `parameters` are visible/added into the URLs as per the following:

**`Example`** | **`Example`** | **`Example`**
---------------|-----------------|-----------------
Screenshot 2026-04-16 230927 | Screenshot 2026-04-16 231136 | Screenshot 2026-04-16 230857
