### PR TITLE
[iOS] Hide URL bar correctly when find-in-page is active

### LINKED ISSUE #54973: [iOS] Incorrect address bar layout in Find in Page mode
### Description

the minimized address bar disappear when user start scrolling in Find in Page mode. 

### Steps to reproduce

1. open brave and visit a website
2. enable Find in Page
3. verify keyboard is up and a textfield on top for input. verify address bar becomes minimized with url displayed 
4. start scrolling down then up

### Actual result

the minimized address bar with url will disappear and regular address bar displayed behind Find in Page (it's more visible with liquid glass on)

### Expected result

the minimized address bar should stay entirely in Find in Page mode.

### Reproduces how often

Easily reproduced

### Brave version

all

### Device/iOS version

all

### Affected browser versions

- [ ] latest AppStore
- [ ] latest TestFlight
- [ ] previous TestFlight

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] in the latest version of mobile Safari

### Miscellaneous information

_No response_

### PR DESCRIPTION
**Pull request by kylehickinson**
This fixes a regression where the URL bar wouldn't hide/collapse correctly while find-in-page was active

Resolves https://github.com/brave/brave-browser/issues/54973

### CODE REVIEW

File: ios/brave-ios/Sources/Web/TabState.swift [hunk 1]
```diff
@@ -210,6 +210,8 @@ public protocol TabState: AnyObject {
   func takeSnapshot(rect: CGRect, handler: @escaping (UIImage?) -> Void)
   /// Creates a full page PDF of the web contents
   func createFullPagePDF() async throws -> Data?
```
Comment (netzenbot) [inline ios/brave-ios/Sources/Web/TabState.swift:212]: `isFindNavigatorVisible` is find-in-page feature state being added directly to the core `TabState` protocol. Per [IOS-041](https://github.com/brave/brave-core/tree/master/docs/best-practices/ios.md#IOS-041), feature-related data should live in a Tab Helper with `TabDataValues`, not in `TabState` itself. Consider using a tab helper to expose this state instead.

Comment (kylehickinson) [reply ios/brave-ios/Sources/Web/TabState.swift:212]: This is valid to be added to `TabState` as its a web-specific feature that exists on `WebState`

**Review by StephenHeaps — APPROVED** [review]
