### PR TITLE
[ads] Fix bugs in ObliviousHttpKeyConfig and ObliviousHttpClientImpl

### LINKED ISSUE #54903: [ads] Fix bugs in ObliviousHttpKeyConfig and ObliviousHttpClientImpl
When key rotation triggers Refetch, the cached key config is cleared so that requests fail fast rather than reaching the relay with an invalid config. However, any fetch callback still in flight from before the rotation is not cancelled, so it can fire after the clear and silently repopulate the config with the now-invalid key config. Requests made after rotation but before the fresh fetch completes then use the stale config and reach the relay with an invalid key.

Steps to Reproduce:

- Not reproducible manually. Key rotation is triggered server-side and cannot be initiated by a user or QA engineer.

### PR DESCRIPTION
**Pull request by tmancey**
Refetch cancels in-flight key config callbacks via InvalidateWeakPtrs before starting a new fetch so a stale response cannot overwrite the cleared config. OnCompleted uses an exhaustive switch on the mojo union tag with no default case. Unit tests cover both classes including happy and sad paths and the in-flight cancellation.

Resolves https://github.com/brave/brave-browser/issues/54903

### CODE REVIEW

File: components/brave_ads/core/browser/network/oblivious_http_client_impl_unittest.cc [hunk 1]
```diff
@@ -0,0 +1,118 @@
...
+#include "testing/gmock/include/gmock/gmock.h"
+#include "testing/gtest/include/gtest/gtest.h"
+#include "url/gurl.h"
+
+// npm run test -- brave_unit_tests --filter=BraveAds*
+
+namespace brave_ads {
+
+namespace {
+constexpr char kUrl[] = "https://example.com/resource";
```
Comment (aseren) [inline components/brave_ads/core/browser/network/oblivious_http_client_impl_unittest.cc:25]: std::string_view

**Review by aseren — APPROVED** [review]

File: components/brave_ads/core/browser/network/oblivious_http_client_impl_unittest.cc (hunk 1 above)
Comment (tmancey) [reply components/brave_ads/core/browser/network/oblivious_http_client_impl_unittest.cc:25]: Because CI is nearly finished I will followup with std::string_view code health across several files.
