### PR TITLE
Use uuids as default container ids.

### LINKED ISSUE #54483: [Containers] Add default Containers
### Description

Currently Containers are empty and users will need to add their own. 

We should default to several Container categories specifically:

- `Personal` label with blue color and home icon
- `Work` label with red color and briefcase icon
- `Social` label with purple and smiley face icon
- `School` label with green and cap icon

**Figma for icon reference and colors:**
https://www.figma.com/design/qOIex7poMN1YbnepQJEvIo/%F0%9F%93%A6-Containers?node-id=2003-16238&t=PRAHBq2haSwl2ZvD-1

### Steps to reproduce

1. Use Nightly 1.91.43 and higher and ensure Containers are enabled
2. Go to: brave://settings/braveContent and notice Container settings
3. See Description and Actual/Expected result.

### Actual result

Image

### Expected result

Image

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

1.91.43 and higher

### Channel information

- [ ] release (stable)
- [ ] beta
- [x] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

_No response_

### PR DESCRIPTION
**Pull request by goodov**
Use uuids for predefined containers. Plain strings are fine, but using uuids for now will allow us keep the same format for all containers, potentially avoiding a class of problems down the line. That's not a restriction currently, but if we can have uuids (even fixed ones), let's use them.

Resolves https://github.com/brave/brave-browser/issues/54483

### CODE REVIEW

**Comment by goodov** [comment]
@sangwoo108 discussed this with @bsclifton, I just should've went for this from start, but haven't thought about pre-generating uuids by hand 😅.

these ones were generated by calling new-guid in powershell

image

**Review by sangwoo108 — APPROVED** [review]

**Comment by sangwoo108** [comment]
LGTM!

File: components/containers/core/browser/default_containers_list.h [hunk 1]
```diff
@@ -6,12 +6,25 @@
...
 #include "brave/components/containers/core/mojom/containers.mojom.h"
 
 namespace containers {
 
+// The default containers have fixed ids to work correctly within the Sync
+// chain. If a user renames/changes icon/color, the underlying id will remain
+// the same on all devices even if the device is not Synced yet.
+//
+// DO NOT CHANGE THESE IDs, only deprecate and add new ones if necessary.
+constexpr auto kDefaultContainerIds = std::to_array({
```
Comment (bsclifton) [inline components/containers/core/browser/default_containers_list.h:21]: is this OK? or would it be acceptable to have a flatmap?

Something like: 
```
auto kDefaultContainerMap = base::MakeFixedFlatMap<std::string_view, std::string_view>({
    {"personal", "0053d88e-7b26-4bfa-9175-783e1bfcba97"},
    // etc
```

File: components/containers/core/browser/default_containers_list.cc [hunk 2]
```diff
@@ -21,29 +21,29 @@ std::vector<mojom::ContainerPtr> CreateDefaultContainersList() {
...
       mojom::Icon::kSocial,
       color_provider->GetColor(nala::kColorPrimitivePurple60)));
   default_containers.push_back(mojom::Container::New(
-      "school", l10n_util::GetStringUTF8(IDS_CONTAINERS_DEFAULT_SCHOOL_NAME),
+      kDefaultContainerIds[3],
+      l10n_util::GetStringUTF8(IDS_CONTAINERS_DEFAULT_SCHOOL_NAME),
       mojom::Icon::kSchool,
       color_provider->GetColor(nala::kColorPrimitiveGreen60)));
 
+  DCHECK_EQ(default_containers.size(), kDefaultContainerIds.size());
```
[the remark this answers is not in the document]
Comment (goodov) [reply components/containers/core/browser/default_containers_list.cc:45]: this is covered with tests. It's not a security critical invariant, just a sanity check.

File: components/containers/core/browser/default_containers_list.h (hunk 1 above)
Comment (goodov) [reply components/containers/core/browser/default_containers_list.h:21]: we don't have "personal" now, only those ids, so that's fine.
