### PR TITLE
[ads][CodeHealth] Fix async race in integration tests for database tables

### LINKED ISSUE #55123: Test failure: BraveAdsConversionsDatabaseTableIntegrationTest.GetConversionsFromCatalogResponse
Greetings human!

Bad news. `BraveAdsConversionsDatabaseTableIntegrationTest.GetConversionsFromCatalogResponse` [failed on browser windows x86 beta v1.91.132](https://ci.brave.com/job/brave-browser-build-windows-x86/5768/testReport/junit/(root)/BraveAdsConversionsDatabaseTableIntegrationTest/windows_x86___test_unit___GetConversionsFromCatalogResponse).
<details>
<summary>Stack trace</summary>

```
[ RUN      ] BraveAdsConversionsDatabaseTableIntegrationTest.GetConversionsFromCatalogResponse
SIMULATED PROFILE PATH: C:\Windows\SystemTemp\scoped_dir996_1455645600
..\..\brave\components\brave_ads\core\internal\creatives\conversions\creative_set_conversion_database_table_test.cc(43): error: Value of: creative_set_conversions
Expected: has a size that is equal to 2
  Actual: {}, whose size 0 doesn't match
Stack trace:
	brave_unit_tests!brave_ads::BraveAdsConversionsDatabaseTableIntegrationTest_GetConversionsFromCatalogResponse_Test::TestBody [0x140155a+24a] (D:\ws\x86-beta\src\brave\components\brave_ads\core\internal\creatives\conversions\creative_set_conversion_database_table_test.cc:43)
[  FAILED  ] BraveAdsConversionsDatabaseTableIntegrationTest.GetConversionsFromCatalogResponse (2687 ms)

[  FAILED  ] BraveAdsConversionsDatabaseTableIntegrationTest.GetConversionsFromCatalogResponse
```
</details>

### PR DESCRIPTION
**Pull request by tmancey**
Integration tests that query catalog-saved data directly after setup were racing against the two-step async DB save chain on slow machines. Poll with RunUntil until rows appear instead of querying once.

Resolves https://github.com/brave/brave-browser/issues/55123

### CODE REVIEW

File: components/brave_ads/core/internal/creatives/conversions/creative_set_conversion_database_table_test.cc [hunk 1]
```diff
@@ -35,12 +36,17 @@ TEST_F(BraveAdsConversionsDatabaseTableIntegrationTest,
...
-      test_future.GetCallback<bool, const CreativeSetConversionList&>());
-  const auto [success, creative_set_conversions] = test_future.Take();
-  EXPECT_TRUE(success);
-  EXPECT_THAT(creative_set_conversions, ::testing::SizeIs(2));
+  ASSERT_TRUE(base::test::RunUntil([&] {
+    base::test::TestFuture<bool, CreativeSetConversionList> test_future;
+    database_table.GetUnexpired(
+        test_future.GetCallback<bool, const CreativeSetConversionList&>());
+    const auto [success, creative_set_conversions] = test_future.Take();
+    if (!success || creative_set_conversions.empty()) {
```
Comment (aseren) [inline components/brave_ads/core/internal/creatives/conversions/creative_set_conversion_database_table_test.cc:44]: we just can replace this if statement with:
`EXPECT_TRUE(success);`

`creative_set_conversions.empty()` is already checked in `EXPECT_THAT(creative_set_conversions, ::testing::SizeIs(2));`

**Review by aseren — APPROVED** [review]
approved with a comment

File: components/brave_ads/core/internal/creatives/conversions/creative_set_conversion_database_table_test.cc (hunk 1 above)
Comment (tmancey) [reply components/brave_ads/core/internal/creatives/conversions/creative_set_conversion_database_table_test.cc:44]: We need to return false until the database table is populated, if its empty it means we are still waiting.
